/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ActionTypeResponse,
} from '../models/index';
import {
    ActionTypeResponseFromJSON,
    ActionTypeResponseToJSON,
} from '../models/index';

/**
 * ActionTypesApi - interface
 * 
 * @export
 * @interface ActionTypesApiInterface
 */
export interface ActionTypesApiInterface {
    /**
     * 
     * @summary Returns all available action types. Display labels are the responsibility of the presentation layer; use the Name field as the ActionType value when submitting a suggestion.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActionTypesApiInterface
     */
    getActionTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ActionTypeResponse>>>;

    /**
     * Returns all available action types. Display labels are the responsibility of the presentation layer; use the Name field as the ActionType value when submitting a suggestion.
     */
    getActionTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ActionTypeResponse>>;

}

/**
 * 
 */
export class ActionTypesApi extends runtime.BaseAPI implements ActionTypesApiInterface {

    /**
     * Returns all available action types. Display labels are the responsibility of the presentation layer; use the Name field as the ActionType value when submitting a suggestion.
     */
    async getActionTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ActionTypeResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/action-types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActionTypeResponseFromJSON));
    }

    /**
     * Returns all available action types. Display labels are the responsibility of the presentation layer; use the Name field as the ActionType value when submitting a suggestion.
     */
    async getActionTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ActionTypeResponse>> {
        const response = await this.getActionTypesRaw(initOverrides);
        return await response.value();
    }

}
