/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ActionOpportunitiesFeedViewModel,
  ApiEnvelopeOfActionOpportunityResponse,
  CreateActionOpportunityRequest,
  ProblemDetails,
} from '../models/index';
import {
    ActionOpportunitiesFeedViewModelFromJSON,
    ActionOpportunitiesFeedViewModelToJSON,
    ApiEnvelopeOfActionOpportunityResponseFromJSON,
    ApiEnvelopeOfActionOpportunityResponseToJSON,
    CreateActionOpportunityRequestFromJSON,
    CreateActionOpportunityRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface CreateActionOpportunityOperationRequest {
    createActionOpportunityRequest: CreateActionOpportunityRequest;
}

export interface GetActionOpportunitiesRequest {
    searchTerm?: string | null;
    status?: string | null;
    parentIdeaId?: string | null;
    sortBy?: string | null;
    page?: number;
    pageSize?: number;
}

export interface GetActionOpportunityDetailsRequest {
    actionOpportunityId: string;
}

/**
 * ActionOpportunitiesApi - interface
 * 
 * @export
 * @interface ActionOpportunitiesApiInterface
 */
export interface ActionOpportunitiesApiInterface {
    /**
     * 
     * @summary Creates a new action opportunity from an idea.
     * @param {CreateActionOpportunityRequest} createActionOpportunityRequest The action opportunity creation request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActionOpportunitiesApiInterface
     */
    createActionOpportunityRaw(requestParameters: CreateActionOpportunityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEnvelopeOfActionOpportunityResponse>>;

    /**
     * Creates a new action opportunity from an idea.
     */
    createActionOpportunity(requestParameters: CreateActionOpportunityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEnvelopeOfActionOpportunityResponse>;

    /**
     * 
     * @summary Gets all action opportunities with optional filtering and pagination.
     * @param {string} [searchTerm] Search term for title and description.
     * @param {string} [status] Status filter: emerging, in-progress, completed.
     * @param {string} [parentIdeaId] Filter by parent idea ID.
     * @param {string} [sortBy] Sort option: recent, updated, title, participants, progress.
     * @param {number} [page] Page number (1-based).
     * @param {number} [pageSize] Number of items per page (default: 20, max: 100).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActionOpportunitiesApiInterface
     */
    getActionOpportunitiesRaw(requestParameters: GetActionOpportunitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActionOpportunitiesFeedViewModel>>;

    /**
     * Gets all action opportunities with optional filtering and pagination.
     */
    getActionOpportunities(requestParameters: GetActionOpportunitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActionOpportunitiesFeedViewModel>;

    /**
     * 
     * @summary Gets detailed information about a specific action opportunity.
     * @param {string} actionOpportunityId The unique identifier of the action opportunity.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActionOpportunitiesApiInterface
     */
    getActionOpportunityDetailsRaw(requestParameters: GetActionOpportunityDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEnvelopeOfActionOpportunityResponse>>;

    /**
     * Gets detailed information about a specific action opportunity.
     */
    getActionOpportunityDetails(requestParameters: GetActionOpportunityDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEnvelopeOfActionOpportunityResponse>;

}

/**
 * 
 */
export class ActionOpportunitiesApi extends runtime.BaseAPI implements ActionOpportunitiesApiInterface {

    /**
     * Creates a new action opportunity from an idea.
     */
    async createActionOpportunityRaw(requestParameters: CreateActionOpportunityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEnvelopeOfActionOpportunityResponse>> {
        if (requestParameters['createActionOpportunityRequest'] == null) {
            throw new runtime.RequiredError(
                'createActionOpportunityRequest',
                'Required parameter "createActionOpportunityRequest" was null or undefined when calling createActionOpportunity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/action-opportunities`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateActionOpportunityRequestToJSON(requestParameters['createActionOpportunityRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiEnvelopeOfActionOpportunityResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new action opportunity from an idea.
     */
    async createActionOpportunity(requestParameters: CreateActionOpportunityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEnvelopeOfActionOpportunityResponse> {
        const response = await this.createActionOpportunityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets all action opportunities with optional filtering and pagination.
     */
    async getActionOpportunitiesRaw(requestParameters: GetActionOpportunitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActionOpportunitiesFeedViewModel>> {
        const queryParameters: any = {};

        if (requestParameters['searchTerm'] != null) {
            queryParameters['searchTerm'] = requestParameters['searchTerm'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['parentIdeaId'] != null) {
            queryParameters['parentIdeaId'] = requestParameters['parentIdeaId'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/action-opportunities`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionOpportunitiesFeedViewModelFromJSON(jsonValue));
    }

    /**
     * Gets all action opportunities with optional filtering and pagination.
     */
    async getActionOpportunities(requestParameters: GetActionOpportunitiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActionOpportunitiesFeedViewModel> {
        const response = await this.getActionOpportunitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets detailed information about a specific action opportunity.
     */
    async getActionOpportunityDetailsRaw(requestParameters: GetActionOpportunityDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEnvelopeOfActionOpportunityResponse>> {
        if (requestParameters['actionOpportunityId'] == null) {
            throw new runtime.RequiredError(
                'actionOpportunityId',
                'Required parameter "actionOpportunityId" was null or undefined when calling getActionOpportunityDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/action-opportunities/{actionOpportunityId}`;
        urlPath = urlPath.replace(`{${"actionOpportunityId"}}`, encodeURIComponent(String(requestParameters['actionOpportunityId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiEnvelopeOfActionOpportunityResponseFromJSON(jsonValue));
    }

    /**
     * Gets detailed information about a specific action opportunity.
     */
    async getActionOpportunityDetails(requestParameters: GetActionOpportunityDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEnvelopeOfActionOpportunityResponse> {
        const response = await this.getActionOpportunityDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
