/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseOfPaginatedResponseOfCommonsListItemResponse,
  ApiResponseOfString,
  ProblemDetails,
  ProposeCommonsRequest,
  SortDescriptor,
} from '../models/index';
import {
    ApiResponseOfPaginatedResponseOfCommonsListItemResponseFromJSON,
    ApiResponseOfPaginatedResponseOfCommonsListItemResponseToJSON,
    ApiResponseOfStringFromJSON,
    ApiResponseOfStringToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ProposeCommonsRequestFromJSON,
    ProposeCommonsRequestToJSON,
    SortDescriptorFromJSON,
    SortDescriptorToJSON,
} from '../models/index';

export interface GetCommonsRequest {
    pageNumber?: number;
    pageSize?: number;
    sort?: Array<SortDescriptor>;
}

export interface ProposeCommonsOperationRequest {
    proposeCommonsRequest: ProposeCommonsRequest;
}

/**
 * CommonsApi - interface
 * 
 * @export
 * @interface CommonsApiInterface
 */
export interface CommonsApiInterface {
    /**
     * 
     * @summary Retrieves a paginated list of commons by forwarding the request to the commons API client.
     * @param {number} [pageNumber] The current page number (1-based).
     * @param {number} [pageSize] The requested page size.
     * @param {Array<SortDescriptor>} [sort] Parsed sort descriptors bound from the querystring parameter named \&#39;sort\&#39;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommonsApiInterface
     */
    getCommonsRaw(requestParameters: GetCommonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfPaginatedResponseOfCommonsListItemResponse>>;

    /**
     * Retrieves a paginated list of commons by forwarding the request to the commons API client.
     */
    getCommons(requestParameters: GetCommonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfPaginatedResponseOfCommonsListItemResponse>;

    /**
     * 
     * @summary Forwards a request to propose a new commons to the commons API.
     * @param {ProposeCommonsRequest} proposeCommonsRequest The request containing the name and description of the commons to propose.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommonsApiInterface
     */
    proposeCommonsRaw(requestParameters: ProposeCommonsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>>;

    /**
     * Forwards a request to propose a new commons to the commons API.
     */
    proposeCommons(requestParameters: ProposeCommonsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString>;

}

/**
 * 
 */
export class CommonsApi extends runtime.BaseAPI implements CommonsApiInterface {

    /**
     * Retrieves a paginated list of commons by forwarding the request to the commons API client.
     */
    async getCommonsRaw(requestParameters: GetCommonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfPaginatedResponseOfCommonsListItemResponse>> {
        const queryParameters: any = {};

        if (requestParameters['pageNumber'] != null) {
            queryParameters['Page.Number'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['Page.Size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/commons`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfPaginatedResponseOfCommonsListItemResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of commons by forwarding the request to the commons API client.
     */
    async getCommons(requestParameters: GetCommonsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfPaginatedResponseOfCommonsListItemResponse> {
        const response = await this.getCommonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Forwards a request to propose a new commons to the commons API.
     */
    async proposeCommonsRaw(requestParameters: ProposeCommonsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>> {
        if (requestParameters['proposeCommonsRequest'] == null) {
            throw new runtime.RequiredError(
                'proposeCommonsRequest',
                'Required parameter "proposeCommonsRequest" was null or undefined when calling proposeCommons().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/commons`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProposeCommonsRequestToJSON(requestParameters['proposeCommonsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringFromJSON(jsonValue));
    }

    /**
     * Forwards a request to propose a new commons to the commons API.
     */
    async proposeCommons(requestParameters: ProposeCommonsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString> {
        const response = await this.proposeCommonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
