/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePostRequest,
  CreateReplyRequest,
  CursorDirection,
  PostRepliesViewModel,
  PostsViewModel,
  ProblemDetails,
} from '../models/index';
import {
    CreatePostRequestFromJSON,
    CreatePostRequestToJSON,
    CreateReplyRequestFromJSON,
    CreateReplyRequestToJSON,
    CursorDirectionFromJSON,
    CursorDirectionToJSON,
    PostRepliesViewModelFromJSON,
    PostRepliesViewModelToJSON,
    PostsViewModelFromJSON,
    PostsViewModelToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface CreatePostOperationRequest {
    threadId: string;
    createPostRequest: CreatePostRequest;
}

export interface CreateReplyOperationRequest {
    threadId: string;
    postId: string;
    createReplyRequest: CreateReplyRequest;
}

export interface GetPostRepliesRequest {
    threadId: string;
    postId: string;
    cursor?: string | null;
    limit?: number;
    direction?: CursorDirection;
}

export interface GetPostsByEntityRequest {
    entityType: string;
    entityId: string;
    cursor?: string | null;
    limit?: number;
    direction?: CursorDirection;
}

export interface GetPostsByThreadIdRequest {
    threadId: string;
    cursor?: string | null;
    limit?: number;
    direction?: CursorDirection;
}

/**
 * DiscourseApi - interface
 * 
 * @export
 * @interface DiscourseApiInterface
 */
export interface DiscourseApiInterface {
    /**
     * 
     * @summary Creates a new root post in a specific thread.
     * @param {string} threadId The ID of the thread to post to.
     * @param {CreatePostRequest} createPostRequest The post creation request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscourseApiInterface
     */
    createPostRaw(requestParameters: CreatePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Creates a new root post in a specific thread.
     */
    createPost(requestParameters: CreatePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * 
     * @summary Creates a new reply to a specific post.
     * @param {string} threadId The ID of the thread.
     * @param {string} postId The ID of the post to reply to.
     * @param {CreateReplyRequest} createReplyRequest The reply creation request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscourseApiInterface
     */
    createReplyRaw(requestParameters: CreateReplyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Creates a new reply to a specific post.
     */
    createReply(requestParameters: CreateReplyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * 
     * @summary Gets replies to a specific post with cursor-based pagination.
     * @param {string} threadId The ID of the thread.
     * @param {string} postId The ID of the post to get replies for.
     * @param {string} [cursor] Cursor for pagination (null for first page).
     * @param {number} [limit] Maximum number of replies to return (default: 5).
     * @param {CursorDirection} [direction] Direction of pagination (default: forward).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscourseApiInterface
     */
    getPostRepliesRaw(requestParameters: GetPostRepliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostRepliesViewModel>>;

    /**
     * Gets replies to a specific post with cursor-based pagination.
     */
    getPostReplies(requestParameters: GetPostRepliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostRepliesViewModel>;

    /**
     * 
     * @summary Gets root posts for a thread identified by entity with cursor-based pagination.
     * @param {string} entityType The type of entity (e.g., \&quot;idea\&quot;, \&quot;signal\&quot;, \&quot;action\&quot;).
     * @param {string} entityId The ID of the entity.
     * @param {string} [cursor] Cursor for pagination (null for first page).
     * @param {number} [limit] Maximum number of posts to return (default: 5).
     * @param {CursorDirection} [direction] Direction of pagination (default: forward).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscourseApiInterface
     */
    getPostsByEntityRaw(requestParameters: GetPostsByEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsViewModel>>;

    /**
     * Gets root posts for a thread identified by entity with cursor-based pagination.
     */
    getPostsByEntity(requestParameters: GetPostsByEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsViewModel>;

    /**
     * 
     * @summary Gets root posts for a specific thread with cursor-based pagination.
     * @param {string} threadId The ID of the thread.
     * @param {string} [cursor] Cursor for pagination (null for first page).
     * @param {number} [limit] Maximum number of posts to return (default: 5).
     * @param {CursorDirection} [direction] Direction of pagination (default: forward).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscourseApiInterface
     */
    getPostsByThreadIdRaw(requestParameters: GetPostsByThreadIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsViewModel>>;

    /**
     * Gets root posts for a specific thread with cursor-based pagination.
     */
    getPostsByThreadId(requestParameters: GetPostsByThreadIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsViewModel>;

}

/**
 * 
 */
export class DiscourseApi extends runtime.BaseAPI implements DiscourseApiInterface {

    /**
     * Creates a new root post in a specific thread.
     */
    async createPostRaw(requestParameters: CreatePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling createPost().'
            );
        }

        if (requestParameters['createPostRequest'] == null) {
            throw new runtime.RequiredError(
                'createPostRequest',
                'Required parameter "createPostRequest" was null or undefined when calling createPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/discourse/threads/{threadId}/posts`;
        urlPath = urlPath.replace(`{${"threadId"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePostRequestToJSON(requestParameters['createPostRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Creates a new root post in a specific thread.
     */
    async createPost(requestParameters: CreatePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new reply to a specific post.
     */
    async createReplyRaw(requestParameters: CreateReplyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling createReply().'
            );
        }

        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling createReply().'
            );
        }

        if (requestParameters['createReplyRequest'] == null) {
            throw new runtime.RequiredError(
                'createReplyRequest',
                'Required parameter "createReplyRequest" was null or undefined when calling createReply().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/discourse/threads/{threadId}/posts/{postId}/replies`;
        urlPath = urlPath.replace(`{${"threadId"}}`, encodeURIComponent(String(requestParameters['threadId'])));
        urlPath = urlPath.replace(`{${"postId"}}`, encodeURIComponent(String(requestParameters['postId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateReplyRequestToJSON(requestParameters['createReplyRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Creates a new reply to a specific post.
     */
    async createReply(requestParameters: CreateReplyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createReplyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets replies to a specific post with cursor-based pagination.
     */
    async getPostRepliesRaw(requestParameters: GetPostRepliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostRepliesViewModel>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getPostReplies().'
            );
        }

        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getPostReplies().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/discourse/threads/{threadId}/posts/{postId}/replies`;
        urlPath = urlPath.replace(`{${"threadId"}}`, encodeURIComponent(String(requestParameters['threadId'])));
        urlPath = urlPath.replace(`{${"postId"}}`, encodeURIComponent(String(requestParameters['postId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostRepliesViewModelFromJSON(jsonValue));
    }

    /**
     * Gets replies to a specific post with cursor-based pagination.
     */
    async getPostReplies(requestParameters: GetPostRepliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostRepliesViewModel> {
        const response = await this.getPostRepliesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets root posts for a thread identified by entity with cursor-based pagination.
     */
    async getPostsByEntityRaw(requestParameters: GetPostsByEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsViewModel>> {
        if (requestParameters['entityType'] == null) {
            throw new runtime.RequiredError(
                'entityType',
                'Required parameter "entityType" was null or undefined when calling getPostsByEntity().'
            );
        }

        if (requestParameters['entityId'] == null) {
            throw new runtime.RequiredError(
                'entityId',
                'Required parameter "entityId" was null or undefined when calling getPostsByEntity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/discourse/threads/by-entity/{entityType}/{entityId}/posts`;
        urlPath = urlPath.replace(`{${"entityType"}}`, encodeURIComponent(String(requestParameters['entityType'])));
        urlPath = urlPath.replace(`{${"entityId"}}`, encodeURIComponent(String(requestParameters['entityId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsViewModelFromJSON(jsonValue));
    }

    /**
     * Gets root posts for a thread identified by entity with cursor-based pagination.
     */
    async getPostsByEntity(requestParameters: GetPostsByEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsViewModel> {
        const response = await this.getPostsByEntityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets root posts for a specific thread with cursor-based pagination.
     */
    async getPostsByThreadIdRaw(requestParameters: GetPostsByThreadIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsViewModel>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getPostsByThreadId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/discourse/threads/{threadId}/posts`;
        urlPath = urlPath.replace(`{${"threadId"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsViewModelFromJSON(jsonValue));
    }

    /**
     * Gets root posts for a specific thread with cursor-based pagination.
     */
    async getPostsByThreadId(requestParameters: GetPostsByThreadIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsViewModel> {
        const response = await this.getPostsByThreadIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
