/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseOfEmergingPatternsFeedViewModel,
} from '../models/index';
import {
    ApiResponseOfEmergingPatternsFeedViewModelFromJSON,
    ApiResponseOfEmergingPatternsFeedViewModelToJSON,
} from '../models/index';

/**
 * EmergingPatternsApi - interface
 * 
 * @export
 * @interface EmergingPatternsApiInterface
 */
export interface EmergingPatternsApiInterface {
    /**
     * 
     * @summary Returns all currently identified emerging signal patterns.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmergingPatternsApiInterface
     */
    getEmergingPatternsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfEmergingPatternsFeedViewModel>>;

    /**
     * Returns all currently identified emerging signal patterns.
     */
    getEmergingPatterns(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfEmergingPatternsFeedViewModel>;

}

/**
 * 
 */
export class EmergingPatternsApi extends runtime.BaseAPI implements EmergingPatternsApiInterface {

    /**
     * Returns all currently identified emerging signal patterns.
     */
    async getEmergingPatternsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfEmergingPatternsFeedViewModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/emerging-patterns`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfEmergingPatternsFeedViewModelFromJSON(jsonValue));
    }

    /**
     * Returns all currently identified emerging signal patterns.
     */
    async getEmergingPatterns(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfEmergingPatternsFeedViewModel> {
        const response = await this.getEmergingPatternsRaw(initOverrides);
        return await response.value();
    }

}
