/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseOfIdeaDetailViewModel,
  ApiResponseOfIdeasFeedViewModel,
  ApiResponseOfString,
  AuthorIdeaRequest,
  ProblemDetails,
  SortDescriptor,
} from '../models/index';
import {
    ApiResponseOfIdeaDetailViewModelFromJSON,
    ApiResponseOfIdeaDetailViewModelToJSON,
    ApiResponseOfIdeasFeedViewModelFromJSON,
    ApiResponseOfIdeasFeedViewModelToJSON,
    ApiResponseOfStringFromJSON,
    ApiResponseOfStringToJSON,
    AuthorIdeaRequestFromJSON,
    AuthorIdeaRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SortDescriptorFromJSON,
    SortDescriptorToJSON,
} from '../models/index';

export interface AuthorIdeaOperationRequest {
    authorIdeaRequest: AuthorIdeaRequest;
}

export interface GetIdeaRequest {
    ideaId: string;
}

export interface GetIdeasRequest {
    filterSearchTerm?: string | null;
    filterStatus?: string | null;
    pageNumber?: number;
    pageSize?: number;
    sort?: Array<SortDescriptor>;
}

/**
 * IdeasApi - interface
 * 
 * @export
 * @interface IdeasApiInterface
 */
export interface IdeasApiInterface {
    /**
     * 
     * @summary Creates a new idea.
     * @param {AuthorIdeaRequest} authorIdeaRequest The idea creation request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdeasApiInterface
     */
    authorIdeaRaw(requestParameters: AuthorIdeaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>>;

    /**
     * Creates a new idea.
     */
    authorIdea(requestParameters: AuthorIdeaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString>;

    /**
     * 
     * @summary Gets detailed information about a specific idea.
     * @param {string} ideaId The unique identifier of the idea.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdeasApiInterface
     */
    getIdeaRaw(requestParameters: GetIdeaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIdeaDetailViewModel>>;

    /**
     * Gets detailed information about a specific idea.
     */
    getIdea(requestParameters: GetIdeaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIdeaDetailViewModel>;

    /**
     * 
     * @summary Gets all ideas with optional filtering and pagination.
     * @param {string} [filterSearchTerm] Optional free-text search term to match against idea title or description.
     * @param {string} [filterStatus] Optional status filter (e.g., \&quot;Draft\&quot;, \&quot;Published\&quot;).
     * @param {number} [pageNumber] The current page number (1-based).
     * @param {number} [pageSize] The requested page size.
     * @param {Array<SortDescriptor>} [sort] Parsed sort descriptors bound from the querystring parameter named \&#39;sort\&#39;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdeasApiInterface
     */
    getIdeasRaw(requestParameters: GetIdeasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIdeasFeedViewModel>>;

    /**
     * Gets all ideas with optional filtering and pagination.
     */
    getIdeas(requestParameters: GetIdeasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIdeasFeedViewModel>;

}

/**
 * 
 */
export class IdeasApi extends runtime.BaseAPI implements IdeasApiInterface {

    /**
     * Creates a new idea.
     */
    async authorIdeaRaw(requestParameters: AuthorIdeaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>> {
        if (requestParameters['authorIdeaRequest'] == null) {
            throw new runtime.RequiredError(
                'authorIdeaRequest',
                'Required parameter "authorIdeaRequest" was null or undefined when calling authorIdea().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/ideas`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorIdeaRequestToJSON(requestParameters['authorIdeaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringFromJSON(jsonValue));
    }

    /**
     * Creates a new idea.
     */
    async authorIdea(requestParameters: AuthorIdeaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString> {
        const response = await this.authorIdeaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets detailed information about a specific idea.
     */
    async getIdeaRaw(requestParameters: GetIdeaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIdeaDetailViewModel>> {
        if (requestParameters['ideaId'] == null) {
            throw new runtime.RequiredError(
                'ideaId',
                'Required parameter "ideaId" was null or undefined when calling getIdea().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/ideas/{ideaId}`;
        urlPath = urlPath.replace(`{${"ideaId"}}`, encodeURIComponent(String(requestParameters['ideaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfIdeaDetailViewModelFromJSON(jsonValue));
    }

    /**
     * Gets detailed information about a specific idea.
     */
    async getIdea(requestParameters: GetIdeaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIdeaDetailViewModel> {
        const response = await this.getIdeaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets all ideas with optional filtering and pagination.
     */
    async getIdeasRaw(requestParameters: GetIdeasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIdeasFeedViewModel>> {
        const queryParameters: any = {};

        if (requestParameters['filterSearchTerm'] != null) {
            queryParameters['Filter.SearchTerm'] = requestParameters['filterSearchTerm'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['Filter.Status'] = requestParameters['filterStatus'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['Page.Number'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['Page.Size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/ideas`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfIdeasFeedViewModelFromJSON(jsonValue));
    }

    /**
     * Gets all ideas with optional filtering and pagination.
     */
    async getIdeas(requestParameters: GetIdeasRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIdeasFeedViewModel> {
        const response = await this.getIdeasRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
