/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseOfParticipantProfileResponse,
  ProblemDetails,
} from '../models/index';
import {
    ApiResponseOfParticipantProfileResponseFromJSON,
    ApiResponseOfParticipantProfileResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface GetParticipantProfileRequest {
    pseudonym: string;
}

/**
 * ProfilesApi - interface
 * 
 * @export
 * @interface ProfilesApiInterface
 */
export interface ProfilesApiInterface {
    /**
     * 
     * @summary Returns the public profile of a participant identified by their pseudonym.
     * @param {string} pseudonym The participant\&#39;s globally unique pseudonym.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfilesApiInterface
     */
    getParticipantProfileRaw(requestParameters: GetParticipantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfParticipantProfileResponse>>;

    /**
     * Returns the public profile of a participant identified by their pseudonym.
     */
    getParticipantProfile(requestParameters: GetParticipantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfParticipantProfileResponse>;

}

/**
 * 
 */
export class ProfilesApi extends runtime.BaseAPI implements ProfilesApiInterface {

    /**
     * Returns the public profile of a participant identified by their pseudonym.
     */
    async getParticipantProfileRaw(requestParameters: GetParticipantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfParticipantProfileResponse>> {
        if (requestParameters['pseudonym'] == null) {
            throw new runtime.RequiredError(
                'pseudonym',
                'Required parameter "pseudonym" was null or undefined when calling getParticipantProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/profiles/{pseudonym}`;
        urlPath = urlPath.replace(`{${"pseudonym"}}`, encodeURIComponent(String(requestParameters['pseudonym'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfParticipantProfileResponseFromJSON(jsonValue));
    }

    /**
     * Returns the public profile of a participant identified by their pseudonym.
     */
    async getParticipantProfile(requestParameters: GetParticipantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfParticipantProfileResponse> {
        const response = await this.getParticipantProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
