/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AmplifySignalRequest,
  ApiResponseOfAmplifySignalResponse,
  ApiResponseOfDeamplifySignalResponse,
  ApiResponseOfSignalAmplificationTrendResponse,
  ApiResponseOfSignalDetailViewModel,
  ApiResponseOfSignalsFeedViewModel,
  ApiResponseOfString,
  CaptureSignalRequest,
  ProblemDetails,
  SortDescriptor,
  SuggestActionRequest,
} from '../models/index';
import {
    AmplifySignalRequestFromJSON,
    AmplifySignalRequestToJSON,
    ApiResponseOfAmplifySignalResponseFromJSON,
    ApiResponseOfAmplifySignalResponseToJSON,
    ApiResponseOfDeamplifySignalResponseFromJSON,
    ApiResponseOfDeamplifySignalResponseToJSON,
    ApiResponseOfSignalAmplificationTrendResponseFromJSON,
    ApiResponseOfSignalAmplificationTrendResponseToJSON,
    ApiResponseOfSignalDetailViewModelFromJSON,
    ApiResponseOfSignalDetailViewModelToJSON,
    ApiResponseOfSignalsFeedViewModelFromJSON,
    ApiResponseOfSignalsFeedViewModelToJSON,
    ApiResponseOfStringFromJSON,
    ApiResponseOfStringToJSON,
    CaptureSignalRequestFromJSON,
    CaptureSignalRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SortDescriptorFromJSON,
    SortDescriptorToJSON,
    SuggestActionRequestFromJSON,
    SuggestActionRequestToJSON,
} from '../models/index';

export interface AmplifySignalOperationRequest {
    signalId: string;
    amplifySignalRequest: AmplifySignalRequest;
}

export interface CaptureSignalOperationRequest {
    captureSignalRequest: CaptureSignalRequest;
}

export interface DeamplifySignalRequest {
    signalId: string;
}

export interface GetSignalAmplificationTrendRequest {
    signalId: string;
}

export interface GetSignalDetailsRequest {
    signalId: string;
}

export interface GetSignalsRequest {
    pageNumber?: number;
    pageSize?: number;
    filterTimeRange?: string | null;
    filterAmplificationLevel?: string | null;
    filterSearchTerm?: string | null;
    filterTags?: Array<string>;
    sort?: Array<SortDescriptor>;
}

export interface SuggestActionOperationRequest {
    signalId: string;
    suggestActionRequest: SuggestActionRequest;
}

/**
 * SignalsApi - interface
 * 
 * @export
 * @interface SignalsApiInterface
 */
export interface SignalsApiInterface {
    /**
     * 
     * @summary Amplifies a signal by a participant.
     * @param {string} signalId The ID of the signal to amplify.
     * @param {AmplifySignalRequest} amplifySignalRequest The amplification request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignalsApiInterface
     */
    amplifySignalRaw(requestParameters: AmplifySignalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfAmplifySignalResponse>>;

    /**
     * Amplifies a signal by a participant.
     */
    amplifySignal(requestParameters: AmplifySignalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfAmplifySignalResponse>;

    /**
     * 
     * @summary Creates a new signal.
     * @param {CaptureSignalRequest} captureSignalRequest The signal creation request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignalsApiInterface
     */
    captureSignalRaw(requestParameters: CaptureSignalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>>;

    /**
     * Creates a new signal.
     */
    captureSignal(requestParameters: CaptureSignalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString>;

    /**
     * 
     * @summary Removes a user\'s amplification from a signal.
     * @param {string} signalId The ID of the signal to deamplify.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignalsApiInterface
     */
    deamplifySignalRaw(requestParameters: DeamplifySignalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfDeamplifySignalResponse>>;

    /**
     * Removes a user\'s amplification from a signal.
     */
    deamplifySignal(requestParameters: DeamplifySignalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfDeamplifySignalResponse>;

    /**
     * 
     * @summary Gets amplification trend data for a specific signal.
     * @param {string} signalId The unique identifier of the signal.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignalsApiInterface
     */
    getSignalAmplificationTrendRaw(requestParameters: GetSignalAmplificationTrendRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSignalAmplificationTrendResponse>>;

    /**
     * Gets amplification trend data for a specific signal.
     */
    getSignalAmplificationTrend(requestParameters: GetSignalAmplificationTrendRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSignalAmplificationTrendResponse>;

    /**
     * 
     * @summary Gets detailed information about a specific signal including amplification history.
     * @param {string} signalId The unique identifier of the signal.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignalsApiInterface
     */
    getSignalDetailsRaw(requestParameters: GetSignalDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSignalDetailViewModel>>;

    /**
     * Gets detailed information about a specific signal including amplification history.
     */
    getSignalDetails(requestParameters: GetSignalDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSignalDetailViewModel>;

    /**
     * 
     * @summary Gets all signals with optional filtering and pagination.
     * @param {number} [pageNumber] The current page number (1-based).
     * @param {number} [pageSize] The requested page size.
     * @param {string} [filterTimeRange] Optional time window to filter signals, for example \&quot;24h\&quot; or \&quot;7d\&quot;.
     * @param {string} [filterAmplificationLevel] Optional amplification level filter (e.g., \&quot;low\&quot;, \&quot;medium\&quot;, \&quot;high\&quot;).
     * @param {string} [filterSearchTerm] Optional free-text search term to match against signal content.
     * @param {Array<string>} [filterTags] Optional collection of tags to filter results by.
     * @param {Array<SortDescriptor>} [sort] Parsed sort descriptors bound from the querystring parameter named \&#39;sort\&#39;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignalsApiInterface
     */
    getSignalsRaw(requestParameters: GetSignalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSignalsFeedViewModel>>;

    /**
     * Gets all signals with optional filtering and pagination.
     */
    getSignals(requestParameters: GetSignalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSignalsFeedViewModel>;

    /**
     * 
     * @summary Suggests an action on a signal.
     * @param {string} signalId The ID of the signal.
     * @param {SuggestActionRequest} suggestActionRequest The action suggestion request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignalsApiInterface
     */
    suggestActionRaw(requestParameters: SuggestActionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Suggests an action on a signal.
     */
    suggestAction(requestParameters: SuggestActionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class SignalsApi extends runtime.BaseAPI implements SignalsApiInterface {

    /**
     * Amplifies a signal by a participant.
     */
    async amplifySignalRaw(requestParameters: AmplifySignalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfAmplifySignalResponse>> {
        if (requestParameters['signalId'] == null) {
            throw new runtime.RequiredError(
                'signalId',
                'Required parameter "signalId" was null or undefined when calling amplifySignal().'
            );
        }

        if (requestParameters['amplifySignalRequest'] == null) {
            throw new runtime.RequiredError(
                'amplifySignalRequest',
                'Required parameter "amplifySignalRequest" was null or undefined when calling amplifySignal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/signals/{signalId}/amplifications`;
        urlPath = urlPath.replace(`{${"signalId"}}`, encodeURIComponent(String(requestParameters['signalId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AmplifySignalRequestToJSON(requestParameters['amplifySignalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfAmplifySignalResponseFromJSON(jsonValue));
    }

    /**
     * Amplifies a signal by a participant.
     */
    async amplifySignal(requestParameters: AmplifySignalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfAmplifySignalResponse> {
        const response = await this.amplifySignalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new signal.
     */
    async captureSignalRaw(requestParameters: CaptureSignalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>> {
        if (requestParameters['captureSignalRequest'] == null) {
            throw new runtime.RequiredError(
                'captureSignalRequest',
                'Required parameter "captureSignalRequest" was null or undefined when calling captureSignal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/signals`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CaptureSignalRequestToJSON(requestParameters['captureSignalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringFromJSON(jsonValue));
    }

    /**
     * Creates a new signal.
     */
    async captureSignal(requestParameters: CaptureSignalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString> {
        const response = await this.captureSignalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes a user\'s amplification from a signal.
     */
    async deamplifySignalRaw(requestParameters: DeamplifySignalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfDeamplifySignalResponse>> {
        if (requestParameters['signalId'] == null) {
            throw new runtime.RequiredError(
                'signalId',
                'Required parameter "signalId" was null or undefined when calling deamplifySignal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/signals/{signalId}/amplifications`;
        urlPath = urlPath.replace(`{${"signalId"}}`, encodeURIComponent(String(requestParameters['signalId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfDeamplifySignalResponseFromJSON(jsonValue));
    }

    /**
     * Removes a user\'s amplification from a signal.
     */
    async deamplifySignal(requestParameters: DeamplifySignalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfDeamplifySignalResponse> {
        const response = await this.deamplifySignalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets amplification trend data for a specific signal.
     */
    async getSignalAmplificationTrendRaw(requestParameters: GetSignalAmplificationTrendRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSignalAmplificationTrendResponse>> {
        if (requestParameters['signalId'] == null) {
            throw new runtime.RequiredError(
                'signalId',
                'Required parameter "signalId" was null or undefined when calling getSignalAmplificationTrend().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/signals/{signalId}/amplification-trend`;
        urlPath = urlPath.replace(`{${"signalId"}}`, encodeURIComponent(String(requestParameters['signalId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfSignalAmplificationTrendResponseFromJSON(jsonValue));
    }

    /**
     * Gets amplification trend data for a specific signal.
     */
    async getSignalAmplificationTrend(requestParameters: GetSignalAmplificationTrendRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSignalAmplificationTrendResponse> {
        const response = await this.getSignalAmplificationTrendRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets detailed information about a specific signal including amplification history.
     */
    async getSignalDetailsRaw(requestParameters: GetSignalDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSignalDetailViewModel>> {
        if (requestParameters['signalId'] == null) {
            throw new runtime.RequiredError(
                'signalId',
                'Required parameter "signalId" was null or undefined when calling getSignalDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/signals/{signalId}`;
        urlPath = urlPath.replace(`{${"signalId"}}`, encodeURIComponent(String(requestParameters['signalId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfSignalDetailViewModelFromJSON(jsonValue));
    }

    /**
     * Gets detailed information about a specific signal including amplification history.
     */
    async getSignalDetails(requestParameters: GetSignalDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSignalDetailViewModel> {
        const response = await this.getSignalDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets all signals with optional filtering and pagination.
     */
    async getSignalsRaw(requestParameters: GetSignalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSignalsFeedViewModel>> {
        const queryParameters: any = {};

        if (requestParameters['pageNumber'] != null) {
            queryParameters['Page.Number'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['Page.Size'] = requestParameters['pageSize'];
        }

        if (requestParameters['filterTimeRange'] != null) {
            queryParameters['Filter.TimeRange'] = requestParameters['filterTimeRange'];
        }

        if (requestParameters['filterAmplificationLevel'] != null) {
            queryParameters['Filter.AmplificationLevel'] = requestParameters['filterAmplificationLevel'];
        }

        if (requestParameters['filterSearchTerm'] != null) {
            queryParameters['Filter.SearchTerm'] = requestParameters['filterSearchTerm'];
        }

        if (requestParameters['filterTags'] != null) {
            queryParameters['Filter.Tags'] = requestParameters['filterTags'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/signals`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfSignalsFeedViewModelFromJSON(jsonValue));
    }

    /**
     * Gets all signals with optional filtering and pagination.
     */
    async getSignals(requestParameters: GetSignalsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSignalsFeedViewModel> {
        const response = await this.getSignalsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Suggests an action on a signal.
     */
    async suggestActionRaw(requestParameters: SuggestActionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['signalId'] == null) {
            throw new runtime.RequiredError(
                'signalId',
                'Required parameter "signalId" was null or undefined when calling suggestAction().'
            );
        }

        if (requestParameters['suggestActionRequest'] == null) {
            throw new runtime.RequiredError(
                'suggestActionRequest',
                'Required parameter "suggestActionRequest" was null or undefined when calling suggestAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/signals/{signalId}/suggested-actions`;
        urlPath = urlPath.replace(`{${"signalId"}}`, encodeURIComponent(String(requestParameters['signalId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SuggestActionRequestToJSON(requestParameters['suggestActionRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Suggests an action on a signal.
     */
    async suggestAction(requestParameters: SuggestActionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.suggestActionRaw(requestParameters, initOverrides);
    }

}
