/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseOfIReadOnlyListOfSocietyInviteLinkViewResponse,
  ApiResponseOfPaginatedResponseOfSocietyMemberResponse,
  ApiResponseOfSocietiesFeedViewModel,
  ApiResponseOfSocietyDetailViewModel,
  ApiResponseOfString,
  ApiResponseOfStringOf,
  CreateSocietyInviteLinkRequest,
  CreateSocietyRequest,
  DeclareSocietyAffectedByCommonsRequest,
  JoinSocietyRequest,
  ProblemDetails,
  SortDescriptor,
} from '../models/index';
import {
    ApiResponseOfIReadOnlyListOfSocietyInviteLinkViewResponseFromJSON,
    ApiResponseOfIReadOnlyListOfSocietyInviteLinkViewResponseToJSON,
    ApiResponseOfPaginatedResponseOfSocietyMemberResponseFromJSON,
    ApiResponseOfPaginatedResponseOfSocietyMemberResponseToJSON,
    ApiResponseOfSocietiesFeedViewModelFromJSON,
    ApiResponseOfSocietiesFeedViewModelToJSON,
    ApiResponseOfSocietyDetailViewModelFromJSON,
    ApiResponseOfSocietyDetailViewModelToJSON,
    ApiResponseOfStringFromJSON,
    ApiResponseOfStringToJSON,
    ApiResponseOfStringOfFromJSON,
    ApiResponseOfStringOfToJSON,
    CreateSocietyInviteLinkRequestFromJSON,
    CreateSocietyInviteLinkRequestToJSON,
    CreateSocietyRequestFromJSON,
    CreateSocietyRequestToJSON,
    DeclareSocietyAffectedByCommonsRequestFromJSON,
    DeclareSocietyAffectedByCommonsRequestToJSON,
    JoinSocietyRequestFromJSON,
    JoinSocietyRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SortDescriptorFromJSON,
    SortDescriptorToJSON,
} from '../models/index';

export interface CreateSocietyOperationRequest {
    createSocietyRequest: CreateSocietyRequest;
}

export interface CreateSocietyInviteLinkOperationRequest {
    societyId: string;
    createSocietyInviteLinkRequest: CreateSocietyInviteLinkRequest;
}

export interface DeclareSocietyAffectedByCommonsOperationRequest {
    societyId: string;
    declareSocietyAffectedByCommonsRequest: DeclareSocietyAffectedByCommonsRequest;
}

export interface GetMySocietyInviteLinksRequest {
    societyId: string;
}

export interface GetSocietiesRequest {
    filterTag?: string | null;
    filterHasGeographicBounds?: boolean | null;
    pageNumber?: number;
    pageSize?: number;
    sort?: Array<SortDescriptor>;
}

export interface GetSocietyRequest {
    societyId: string;
}

export interface GetSocietyMembersRequest {
    societyId: string;
    filter?: object;
    pageNumber?: number;
    pageSize?: number;
    sort?: Array<SortDescriptor>;
}

export interface JoinSocietyOperationRequest {
    societyId: string;
    joinSocietyRequest: JoinSocietyRequest;
}

export interface LeaveSocietyRequest {
    societyId: string;
}

/**
 * SocietiesApi - interface
 * 
 * @export
 * @interface SocietiesApiInterface
 */
export interface SocietiesApiInterface {
    /**
     * 
     * @summary Creates a new society.
     * @param {CreateSocietyRequest} createSocietyRequest The society creation request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    createSocietyRaw(requestParameters: CreateSocietyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>>;

    /**
     * Creates a new society.
     */
    createSociety(requestParameters: CreateSocietyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString>;

    /**
     * 
     * @summary Creates an invite link for the specified society. The caller must be an active member. Membership is verified downstream in CorePlatform.API.
     * @param {string} societyId The unique identifier of the society.
     * @param {CreateSocietyInviteLinkRequest} createSocietyInviteLinkRequest The invite link creation request containing an optional note.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    createSocietyInviteLinkRaw(requestParameters: CreateSocietyInviteLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>>;

    /**
     * Creates an invite link for the specified society. The caller must be an active member. Membership is verified downstream in CorePlatform.API.
     */
    createSocietyInviteLink(requestParameters: CreateSocietyInviteLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString>;

    /**
     * 
     * @summary Declares that a society is affected by a commons.
     * @param {string} societyId The unique identifier of the society.
     * @param {DeclareSocietyAffectedByCommonsRequest} declareSocietyAffectedByCommonsRequest The declaration request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    declareSocietyAffectedByCommonsRaw(requestParameters: DeclareSocietyAffectedByCommonsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Declares that a society is affected by a commons.
     */
    declareSocietyAffectedByCommons(requestParameters: DeclareSocietyAffectedByCommonsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Gets the IDs of all societies the authenticated participant is an active member of. Returns an empty array for unauthenticated requests.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    getMySocietyIdsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfStringOf>>;

    /**
     * Gets the IDs of all societies the authenticated participant is an active member of. Returns an empty array for unauthenticated requests.
     */
    getMySocietyIds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfStringOf>;

    /**
     * 
     * @summary Gets all invite links created by the authenticated participant for the specified society.
     * @param {string} societyId The unique identifier of the society.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    getMySocietyInviteLinksRaw(requestParameters: GetMySocietyInviteLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIReadOnlyListOfSocietyInviteLinkViewResponse>>;

    /**
     * Gets all invite links created by the authenticated participant for the specified society.
     */
    getMySocietyInviteLinks(requestParameters: GetMySocietyInviteLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIReadOnlyListOfSocietyInviteLinkViewResponse>;

    /**
     * 
     * @summary Gets a paginated list of societies with optional filtering.
     * @param {string} [filterTag] Gets or sets a tag to filter societies by; only societies with this tag are returned.
     * @param {boolean} [filterHasGeographicBounds] Gets or sets a value indicating whether to filter to only societies that have geographic bounds. When null, no geographic filtering is applied.
     * @param {number} [pageNumber] The current page number (1-based).
     * @param {number} [pageSize] The requested page size.
     * @param {Array<SortDescriptor>} [sort] Parsed sort descriptors bound from the querystring parameter named \&#39;sort\&#39;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    getSocietiesRaw(requestParameters: GetSocietiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSocietiesFeedViewModel>>;

    /**
     * Gets a paginated list of societies with optional filtering.
     */
    getSocieties(requestParameters: GetSocietiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSocietiesFeedViewModel>;

    /**
     * 
     * @summary Gets detailed information about a specific society.
     * @param {string} societyId The unique identifier of the society.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    getSocietyRaw(requestParameters: GetSocietyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSocietyDetailViewModel>>;

    /**
     * Gets detailed information about a specific society.
     */
    getSociety(requestParameters: GetSocietyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSocietyDetailViewModel>;

    /**
     * 
     * @summary Gets the active members of a specific society.
     * @param {string} societyId The unique identifier of the society.
     * @param {object} [filter] Typed filter payload bound from the filter.* prefix (e.g., filter.status).
     * @param {number} [pageNumber] The current page number (1-based).
     * @param {number} [pageSize] The requested page size.
     * @param {Array<SortDescriptor>} [sort] Parsed sort descriptors bound from the querystring parameter named \&#39;sort\&#39;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    getSocietyMembersRaw(requestParameters: GetSocietyMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfPaginatedResponseOfSocietyMemberResponse>>;

    /**
     * Gets the active members of a specific society.
     */
    getSocietyMembers(requestParameters: GetSocietyMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfPaginatedResponseOfSocietyMemberResponse>;

    /**
     * 
     * @summary Joins a society on behalf of the authenticated participant.
     * @param {string} societyId The unique identifier of the society to join.
     * @param {JoinSocietyRequest} joinSocietyRequest The join request containing the social contract ID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    joinSocietyRaw(requestParameters: JoinSocietyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>>;

    /**
     * Joins a society on behalf of the authenticated participant.
     */
    joinSociety(requestParameters: JoinSocietyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString>;

    /**
     * 
     * @summary Removes the authenticated participant\'s membership from a society.
     * @param {string} societyId The unique identifier of the society to leave.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocietiesApiInterface
     */
    leaveSocietyRaw(requestParameters: LeaveSocietyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Removes the authenticated participant\'s membership from a society.
     */
    leaveSociety(requestParameters: LeaveSocietyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class SocietiesApi extends runtime.BaseAPI implements SocietiesApiInterface {

    /**
     * Creates a new society.
     */
    async createSocietyRaw(requestParameters: CreateSocietyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>> {
        if (requestParameters['createSocietyRequest'] == null) {
            throw new runtime.RequiredError(
                'createSocietyRequest',
                'Required parameter "createSocietyRequest" was null or undefined when calling createSociety().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/societies`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSocietyRequestToJSON(requestParameters['createSocietyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringFromJSON(jsonValue));
    }

    /**
     * Creates a new society.
     */
    async createSociety(requestParameters: CreateSocietyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString> {
        const response = await this.createSocietyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates an invite link for the specified society. The caller must be an active member. Membership is verified downstream in CorePlatform.API.
     */
    async createSocietyInviteLinkRaw(requestParameters: CreateSocietyInviteLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>> {
        if (requestParameters['societyId'] == null) {
            throw new runtime.RequiredError(
                'societyId',
                'Required parameter "societyId" was null or undefined when calling createSocietyInviteLink().'
            );
        }

        if (requestParameters['createSocietyInviteLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'createSocietyInviteLinkRequest',
                'Required parameter "createSocietyInviteLinkRequest" was null or undefined when calling createSocietyInviteLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/societies/{societyId}/invite-links`;
        urlPath = urlPath.replace(`{${"societyId"}}`, encodeURIComponent(String(requestParameters['societyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSocietyInviteLinkRequestToJSON(requestParameters['createSocietyInviteLinkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringFromJSON(jsonValue));
    }

    /**
     * Creates an invite link for the specified society. The caller must be an active member. Membership is verified downstream in CorePlatform.API.
     */
    async createSocietyInviteLink(requestParameters: CreateSocietyInviteLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString> {
        const response = await this.createSocietyInviteLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Declares that a society is affected by a commons.
     */
    async declareSocietyAffectedByCommonsRaw(requestParameters: DeclareSocietyAffectedByCommonsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['societyId'] == null) {
            throw new runtime.RequiredError(
                'societyId',
                'Required parameter "societyId" was null or undefined when calling declareSocietyAffectedByCommons().'
            );
        }

        if (requestParameters['declareSocietyAffectedByCommonsRequest'] == null) {
            throw new runtime.RequiredError(
                'declareSocietyAffectedByCommonsRequest',
                'Required parameter "declareSocietyAffectedByCommonsRequest" was null or undefined when calling declareSocietyAffectedByCommons().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/societies/{societyId}/commons-links`;
        urlPath = urlPath.replace(`{${"societyId"}}`, encodeURIComponent(String(requestParameters['societyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeclareSocietyAffectedByCommonsRequestToJSON(requestParameters['declareSocietyAffectedByCommonsRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Declares that a society is affected by a commons.
     */
    async declareSocietyAffectedByCommons(requestParameters: DeclareSocietyAffectedByCommonsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.declareSocietyAffectedByCommonsRaw(requestParameters, initOverrides);
    }

    /**
     * Gets the IDs of all societies the authenticated participant is an active member of. Returns an empty array for unauthenticated requests.
     */
    async getMySocietyIdsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfStringOf>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/societies/memberships/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringOfFromJSON(jsonValue));
    }

    /**
     * Gets the IDs of all societies the authenticated participant is an active member of. Returns an empty array for unauthenticated requests.
     */
    async getMySocietyIds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfStringOf> {
        const response = await this.getMySocietyIdsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Gets all invite links created by the authenticated participant for the specified society.
     */
    async getMySocietyInviteLinksRaw(requestParameters: GetMySocietyInviteLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIReadOnlyListOfSocietyInviteLinkViewResponse>> {
        if (requestParameters['societyId'] == null) {
            throw new runtime.RequiredError(
                'societyId',
                'Required parameter "societyId" was null or undefined when calling getMySocietyInviteLinks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/societies/{societyId}/invite-links/mine`;
        urlPath = urlPath.replace(`{${"societyId"}}`, encodeURIComponent(String(requestParameters['societyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfIReadOnlyListOfSocietyInviteLinkViewResponseFromJSON(jsonValue));
    }

    /**
     * Gets all invite links created by the authenticated participant for the specified society.
     */
    async getMySocietyInviteLinks(requestParameters: GetMySocietyInviteLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIReadOnlyListOfSocietyInviteLinkViewResponse> {
        const response = await this.getMySocietyInviteLinksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets a paginated list of societies with optional filtering.
     */
    async getSocietiesRaw(requestParameters: GetSocietiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSocietiesFeedViewModel>> {
        const queryParameters: any = {};

        if (requestParameters['filterTag'] != null) {
            queryParameters['Filter.Tag'] = requestParameters['filterTag'];
        }

        if (requestParameters['filterHasGeographicBounds'] != null) {
            queryParameters['Filter.HasGeographicBounds'] = requestParameters['filterHasGeographicBounds'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['Page.Number'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['Page.Size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/societies`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfSocietiesFeedViewModelFromJSON(jsonValue));
    }

    /**
     * Gets a paginated list of societies with optional filtering.
     */
    async getSocieties(requestParameters: GetSocietiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSocietiesFeedViewModel> {
        const response = await this.getSocietiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets detailed information about a specific society.
     */
    async getSocietyRaw(requestParameters: GetSocietyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfSocietyDetailViewModel>> {
        if (requestParameters['societyId'] == null) {
            throw new runtime.RequiredError(
                'societyId',
                'Required parameter "societyId" was null or undefined when calling getSociety().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/societies/{societyId}`;
        urlPath = urlPath.replace(`{${"societyId"}}`, encodeURIComponent(String(requestParameters['societyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfSocietyDetailViewModelFromJSON(jsonValue));
    }

    /**
     * Gets detailed information about a specific society.
     */
    async getSociety(requestParameters: GetSocietyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfSocietyDetailViewModel> {
        const response = await this.getSocietyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets the active members of a specific society.
     */
    async getSocietyMembersRaw(requestParameters: GetSocietyMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfPaginatedResponseOfSocietyMemberResponse>> {
        if (requestParameters['societyId'] == null) {
            throw new runtime.RequiredError(
                'societyId',
                'Required parameter "societyId" was null or undefined when calling getSocietyMembers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['Filter'] = requestParameters['filter'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['Page.Number'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['Page.Size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/societies/{societyId}/members`;
        urlPath = urlPath.replace(`{${"societyId"}}`, encodeURIComponent(String(requestParameters['societyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfPaginatedResponseOfSocietyMemberResponseFromJSON(jsonValue));
    }

    /**
     * Gets the active members of a specific society.
     */
    async getSocietyMembers(requestParameters: GetSocietyMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfPaginatedResponseOfSocietyMemberResponse> {
        const response = await this.getSocietyMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Joins a society on behalf of the authenticated participant.
     */
    async joinSocietyRaw(requestParameters: JoinSocietyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>> {
        if (requestParameters['societyId'] == null) {
            throw new runtime.RequiredError(
                'societyId',
                'Required parameter "societyId" was null or undefined when calling joinSociety().'
            );
        }

        if (requestParameters['joinSocietyRequest'] == null) {
            throw new runtime.RequiredError(
                'joinSocietyRequest',
                'Required parameter "joinSocietyRequest" was null or undefined when calling joinSociety().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/societies/{societyId}/memberships`;
        urlPath = urlPath.replace(`{${"societyId"}}`, encodeURIComponent(String(requestParameters['societyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinSocietyRequestToJSON(requestParameters['joinSocietyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringFromJSON(jsonValue));
    }

    /**
     * Joins a society on behalf of the authenticated participant.
     */
    async joinSociety(requestParameters: JoinSocietyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString> {
        const response = await this.joinSocietyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the authenticated participant\'s membership from a society.
     */
    async leaveSocietyRaw(requestParameters: LeaveSocietyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['societyId'] == null) {
            throw new runtime.RequiredError(
                'societyId',
                'Required parameter "societyId" was null or undefined when calling leaveSociety().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/societies/{societyId}/memberships/me`;
        urlPath = urlPath.replace(`{${"societyId"}}`, encodeURIComponent(String(requestParameters['societyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the authenticated participant\'s membership from a society.
     */
    async leaveSociety(requestParameters: LeaveSocietyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.leaveSocietyRaw(requestParameters, initOverrides);
    }

}
