/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse,
  ApiResponseOfResolvedInviteLinkResponse,
  ApiResponseOfString,
  CreateTrustInviteLinkRequest,
  ProblemDetails,
} from '../models/index';
import {
    ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseFromJSON,
    ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseToJSON,
    ApiResponseOfResolvedInviteLinkResponseFromJSON,
    ApiResponseOfResolvedInviteLinkResponseToJSON,
    ApiResponseOfStringFromJSON,
    ApiResponseOfStringToJSON,
    CreateTrustInviteLinkRequestFromJSON,
    CreateTrustInviteLinkRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface CreateTrustInviteLinkOperationRequest {
    createTrustInviteLinkRequest: CreateTrustInviteLinkRequest;
}

export interface ResolveTrustInviteLinkRequest {
    token?: string;
}

export interface RevokeTrustInviteLinkRequest {
    id: string;
}

/**
 * TrustInviteLinksApi - interface
 * 
 * @export
 * @interface TrustInviteLinksApiInterface
 */
export interface TrustInviteLinksApiInterface {
    /**
     * 
     * @summary Creates an invite link for the authenticated participant.
     * @param {CreateTrustInviteLinkRequest} createTrustInviteLinkRequest The invite link creation request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrustInviteLinksApiInterface
     */
    createTrustInviteLinkRaw(requestParameters: CreateTrustInviteLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>>;

    /**
     * Creates an invite link for the authenticated participant.
     */
    createTrustInviteLink(requestParameters: CreateTrustInviteLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString>;

    /**
     * 
     * @summary Gets all invite links for the authenticated participant, sorted by creation date descending.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrustInviteLinksApiInterface
     */
    getMyTrustInviteLinksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse>>;

    /**
     * Gets all invite links for the authenticated participant, sorted by creation date descending.
     */
    getMyTrustInviteLinks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse>;

    /**
     * 
     * @summary Resolves an invite link token to the inviter\'s user ID. Accessible without authentication.
     * @param {string} [token] The URL-safe base64url token from the invite link.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrustInviteLinksApiInterface
     */
    resolveTrustInviteLinkRaw(requestParameters: ResolveTrustInviteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfResolvedInviteLinkResponse>>;

    /**
     * Resolves an invite link token to the inviter\'s user ID. Accessible without authentication.
     */
    resolveTrustInviteLink(requestParameters: ResolveTrustInviteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfResolvedInviteLinkResponse>;

    /**
     * 
     * @summary Revokes an invite link owned by the authenticated participant.
     * @param {string} id The ID of the invite link to revoke.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrustInviteLinksApiInterface
     */
    revokeTrustInviteLinkRaw(requestParameters: RevokeTrustInviteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Revokes an invite link owned by the authenticated participant.
     */
    revokeTrustInviteLink(requestParameters: RevokeTrustInviteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class TrustInviteLinksApi extends runtime.BaseAPI implements TrustInviteLinksApiInterface {

    /**
     * Creates an invite link for the authenticated participant.
     */
    async createTrustInviteLinkRaw(requestParameters: CreateTrustInviteLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>> {
        if (requestParameters['createTrustInviteLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'createTrustInviteLinkRequest',
                'Required parameter "createTrustInviteLinkRequest" was null or undefined when calling createTrustInviteLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/invite-links`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTrustInviteLinkRequestToJSON(requestParameters['createTrustInviteLinkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringFromJSON(jsonValue));
    }

    /**
     * Creates an invite link for the authenticated participant.
     */
    async createTrustInviteLink(requestParameters: CreateTrustInviteLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString> {
        const response = await this.createTrustInviteLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets all invite links for the authenticated participant, sorted by creation date descending.
     */
    async getMyTrustInviteLinksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/invite-links`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseFromJSON(jsonValue));
    }

    /**
     * Gets all invite links for the authenticated participant, sorted by creation date descending.
     */
    async getMyTrustInviteLinks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse> {
        const response = await this.getMyTrustInviteLinksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Resolves an invite link token to the inviter\'s user ID. Accessible without authentication.
     */
    async resolveTrustInviteLinkRaw(requestParameters: ResolveTrustInviteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfResolvedInviteLinkResponse>> {
        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/invite-links/resolve`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfResolvedInviteLinkResponseFromJSON(jsonValue));
    }

    /**
     * Resolves an invite link token to the inviter\'s user ID. Accessible without authentication.
     */
    async resolveTrustInviteLink(requestParameters: ResolveTrustInviteLinkRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfResolvedInviteLinkResponse> {
        const response = await this.resolveTrustInviteLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revokes an invite link owned by the authenticated participant.
     */
    async revokeTrustInviteLinkRaw(requestParameters: RevokeTrustInviteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeTrustInviteLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/invite-links/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revokes an invite link owned by the authenticated participant.
     */
    async revokeTrustInviteLink(requestParameters: RevokeTrustInviteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeTrustInviteLinkRaw(requestParameters, initOverrides);
    }

}
