/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseOfIReadOnlyListOfUserGroupListItemResponse,
  ApiResponseOfPaginatedResponseOfUserGroupListItemResponse,
  ApiResponseOfPaginatedResponseOfUserGroupMemberResponse,
  ApiResponseOfString,
  ApiResponseOfUserGroupDetailResponse,
  ApiResponseOfUserGroupListItemResponseOf,
  FormUserGroupRequest,
  ProblemDetails,
  SortDescriptor,
} from '../models/index';
import {
    ApiResponseOfIReadOnlyListOfUserGroupListItemResponseFromJSON,
    ApiResponseOfIReadOnlyListOfUserGroupListItemResponseToJSON,
    ApiResponseOfPaginatedResponseOfUserGroupListItemResponseFromJSON,
    ApiResponseOfPaginatedResponseOfUserGroupListItemResponseToJSON,
    ApiResponseOfPaginatedResponseOfUserGroupMemberResponseFromJSON,
    ApiResponseOfPaginatedResponseOfUserGroupMemberResponseToJSON,
    ApiResponseOfStringFromJSON,
    ApiResponseOfStringToJSON,
    ApiResponseOfUserGroupDetailResponseFromJSON,
    ApiResponseOfUserGroupDetailResponseToJSON,
    ApiResponseOfUserGroupListItemResponseOfFromJSON,
    ApiResponseOfUserGroupListItemResponseOfToJSON,
    FormUserGroupRequestFromJSON,
    FormUserGroupRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SortDescriptorFromJSON,
    SortDescriptorToJSON,
} from '../models/index';

export interface FormUserGroupOperationRequest {
    formUserGroupRequest: FormUserGroupRequest;
}

export interface GetUserGroupDetailRequest {
    id: string;
}

export interface GetUserGroupMembersRequest {
    id: string;
    pageNumber?: number;
    pageSize?: number;
    sort?: Array<SortDescriptor>;
}

export interface GetUserGroupsForCommonsRequest {
    commonsId?: string;
    pageNumber?: number;
    pageSize?: number;
    sort?: Array<SortDescriptor>;
}

export interface GetUserGroupsForParticipantRequest {
    participantId?: string;
}

/**
 * UserGroupsApi - interface
 * 
 * @export
 * @interface UserGroupsApiInterface
 */
export interface UserGroupsApiInterface {
    /**
     * 
     * @summary Forwards a request to form a new user group to the user groups API.
     * @param {FormUserGroupRequest} formUserGroupRequest The request containing the details of the user group to form.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserGroupsApiInterface
     */
    formUserGroupRaw(requestParameters: FormUserGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>>;

    /**
     * Forwards a request to form a new user group to the user groups API.
     */
    formUserGroup(requestParameters: FormUserGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString>;

    /**
     * 
     * @summary Retrieves all user groups that the authenticated participant is a member of.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserGroupsApiInterface
     */
    getMyUserGroupsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIReadOnlyListOfUserGroupListItemResponse>>;

    /**
     * Retrieves all user groups that the authenticated participant is a member of.
     */
    getMyUserGroups(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIReadOnlyListOfUserGroupListItemResponse>;

    /**
     * 
     * @summary Retrieves the detail of a specific user group by its ID.
     * @param {string} id The ID of the user group.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserGroupsApiInterface
     */
    getUserGroupDetailRaw(requestParameters: GetUserGroupDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfUserGroupDetailResponse>>;

    /**
     * Retrieves the detail of a specific user group by its ID.
     */
    getUserGroupDetail(requestParameters: GetUserGroupDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfUserGroupDetailResponse>;

    /**
     * 
     * @summary Retrieves a paginated list of members belonging to the specified user group.
     * @param {string} id The ID of the user group.
     * @param {number} [pageNumber] The current page number (1-based).
     * @param {number} [pageSize] The requested page size.
     * @param {Array<SortDescriptor>} [sort] Parsed sort descriptors bound from the querystring parameter named \&#39;sort\&#39;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserGroupsApiInterface
     */
    getUserGroupMembersRaw(requestParameters: GetUserGroupMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfPaginatedResponseOfUserGroupMemberResponse>>;

    /**
     * Retrieves a paginated list of members belonging to the specified user group.
     */
    getUserGroupMembers(requestParameters: GetUserGroupMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfPaginatedResponseOfUserGroupMemberResponse>;

    /**
     * 
     * @summary Retrieves a paginated list of user groups governing the specified commons.
     * @param {string} [commonsId] The ID of the commons to filter by.
     * @param {number} [pageNumber] The current page number (1-based).
     * @param {number} [pageSize] The requested page size.
     * @param {Array<SortDescriptor>} [sort] Parsed sort descriptors bound from the querystring parameter named \&#39;sort\&#39;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserGroupsApiInterface
     */
    getUserGroupsForCommonsRaw(requestParameters: GetUserGroupsForCommonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfPaginatedResponseOfUserGroupListItemResponse>>;

    /**
     * Retrieves a paginated list of user groups governing the specified commons.
     */
    getUserGroupsForCommons(requestParameters: GetUserGroupsForCommonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfPaginatedResponseOfUserGroupListItemResponse>;

    /**
     * 
     * @summary Retrieves all user groups that the specified participant is a member of.
     * @param {string} [participantId] The participant ID to filter by.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserGroupsApiInterface
     */
    getUserGroupsForParticipantRaw(requestParameters: GetUserGroupsForParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfUserGroupListItemResponseOf>>;

    /**
     * Retrieves all user groups that the specified participant is a member of.
     */
    getUserGroupsForParticipant(requestParameters: GetUserGroupsForParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfUserGroupListItemResponseOf>;

}

/**
 * 
 */
export class UserGroupsApi extends runtime.BaseAPI implements UserGroupsApiInterface {

    /**
     * Forwards a request to form a new user group to the user groups API.
     */
    async formUserGroupRaw(requestParameters: FormUserGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfString>> {
        if (requestParameters['formUserGroupRequest'] == null) {
            throw new runtime.RequiredError(
                'formUserGroupRequest',
                'Required parameter "formUserGroupRequest" was null or undefined when calling formUserGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/usergroups`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FormUserGroupRequestToJSON(requestParameters['formUserGroupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfStringFromJSON(jsonValue));
    }

    /**
     * Forwards a request to form a new user group to the user groups API.
     */
    async formUserGroup(requestParameters: FormUserGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfString> {
        const response = await this.formUserGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all user groups that the authenticated participant is a member of.
     */
    async getMyUserGroupsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfIReadOnlyListOfUserGroupListItemResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/usergroups/mine`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfIReadOnlyListOfUserGroupListItemResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves all user groups that the authenticated participant is a member of.
     */
    async getMyUserGroups(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfIReadOnlyListOfUserGroupListItemResponse> {
        const response = await this.getMyUserGroupsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the detail of a specific user group by its ID.
     */
    async getUserGroupDetailRaw(requestParameters: GetUserGroupDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfUserGroupDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUserGroupDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/usergroups/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfUserGroupDetailResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the detail of a specific user group by its ID.
     */
    async getUserGroupDetail(requestParameters: GetUserGroupDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfUserGroupDetailResponse> {
        const response = await this.getUserGroupDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a paginated list of members belonging to the specified user group.
     */
    async getUserGroupMembersRaw(requestParameters: GetUserGroupMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfPaginatedResponseOfUserGroupMemberResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUserGroupMembers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageNumber'] != null) {
            queryParameters['Page.Number'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['Page.Size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/usergroups/{id}/members`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfPaginatedResponseOfUserGroupMemberResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of members belonging to the specified user group.
     */
    async getUserGroupMembers(requestParameters: GetUserGroupMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfPaginatedResponseOfUserGroupMemberResponse> {
        const response = await this.getUserGroupMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a paginated list of user groups governing the specified commons.
     */
    async getUserGroupsForCommonsRaw(requestParameters: GetUserGroupsForCommonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfPaginatedResponseOfUserGroupListItemResponse>> {
        const queryParameters: any = {};

        if (requestParameters['commonsId'] != null) {
            queryParameters['commonsId'] = requestParameters['commonsId'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['Page.Number'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['Page.Size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/usergroups`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfPaginatedResponseOfUserGroupListItemResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of user groups governing the specified commons.
     */
    async getUserGroupsForCommons(requestParameters: GetUserGroupsForCommonsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfPaginatedResponseOfUserGroupListItemResponse> {
        const response = await this.getUserGroupsForCommonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all user groups that the specified participant is a member of.
     */
    async getUserGroupsForParticipantRaw(requestParameters: GetUserGroupsForParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseOfUserGroupListItemResponseOf>> {
        const queryParameters: any = {};

        if (requestParameters['participantId'] != null) {
            queryParameters['participantId'] = requestParameters['participantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/usergroups/for-participant`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseOfUserGroupListItemResponseOfFromJSON(jsonValue));
    }

    /**
     * Retrieves all user groups that the specified participant is a member of.
     */
    async getUserGroupsForParticipant(requestParameters: GetUserGroupsForParticipantRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseOfUserGroupListItemResponseOf> {
        const response = await this.getUserGroupsForParticipantRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
