/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for action opportunity list items.
 * @export
 * @interface ActionOpportunityListResponse
 */
export interface ActionOpportunityListResponse {
    /**
     * The unique identifier of the action opportunity.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    id?: string;
    /**
     * The title of the action opportunity.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    title?: string;
    /**
     * A brief description of the action opportunity.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    description?: string;
    /**
     * The status of the action opportunity.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    status?: string;
    /**
     * The ID of the parent idea that spawned this action opportunity.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    parentIdeaId?: string;
    /**
     * The title of the parent idea.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    parentIdeaTitle?: string;
    /**
     * The ID of the creator.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    creatorId?: string;
    /**
     * The name of the creator.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    creatorName?: string;
    /**
     * The creation timestamp in ISO 8601 format.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    createdAt?: string;
    /**
     * The last update timestamp in ISO 8601 format.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    updatedAt?: string;
    /**
     * The number of participants committed to this action opportunity.
     * @type {number}
     * @memberof ActionOpportunityListResponse
     */
    participantCount?: number;
    /**
     * The current progress percentage (0-100).
     * @type {number}
     * @memberof ActionOpportunityListResponse
     */
    progressPercentage?: number;
    /**
     * Whether the current user has committed to this action opportunity.
     * @type {boolean}
     * @memberof ActionOpportunityListResponse
     */
    isCommitted?: boolean;
    /**
     * The current user's commitment type if committed.
     * @type {string}
     * @memberof ActionOpportunityListResponse
     */
    userCommitmentType?: string | null;
}

/**
 * Check if a given object implements the ActionOpportunityListResponse interface.
 */
export function instanceOfActionOpportunityListResponse(value: object): value is ActionOpportunityListResponse {
    return true;
}

export function ActionOpportunityListResponseFromJSON(json: any): ActionOpportunityListResponse {
    return ActionOpportunityListResponseFromJSONTyped(json, false);
}

export function ActionOpportunityListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionOpportunityListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'parentIdeaId': json['parentIdeaId'] == null ? undefined : json['parentIdeaId'],
        'parentIdeaTitle': json['parentIdeaTitle'] == null ? undefined : json['parentIdeaTitle'],
        'creatorId': json['creatorId'] == null ? undefined : json['creatorId'],
        'creatorName': json['creatorName'] == null ? undefined : json['creatorName'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'participantCount': json['participantCount'] == null ? undefined : json['participantCount'],
        'progressPercentage': json['progressPercentage'] == null ? undefined : json['progressPercentage'],
        'isCommitted': json['isCommitted'] == null ? undefined : json['isCommitted'],
        'userCommitmentType': json['userCommitmentType'] == null ? undefined : json['userCommitmentType'],
    };
}

export function ActionOpportunityListResponseToJSON(json: any): ActionOpportunityListResponse {
    return ActionOpportunityListResponseToJSONTyped(json, false);
}

export function ActionOpportunityListResponseToJSONTyped(value?: ActionOpportunityListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'parentIdeaId': value['parentIdeaId'],
        'parentIdeaTitle': value['parentIdeaTitle'],
        'creatorId': value['creatorId'],
        'creatorName': value['creatorName'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'participantCount': value['participantCount'],
        'progressPercentage': value['progressPercentage'],
        'isCommitted': value['isCommitted'],
        'userCommitmentType': value['userCommitmentType'],
    };
}

