/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model representing an available action type in the catalog.
 * @export
 * @interface ActionTypeResponse
 */
export interface ActionTypeResponse {
    /**
     * The stable integer identifier used in events and API calls.
     * @type {number}
     * @memberof ActionTypeResponse
     */
    id?: number;
    /**
     * The code name of the action type (e.g. MakeACall).
     * Use this value as ActionType when submitting a suggested action.
     * Display labels for this name are the responsibility of the presentation layer.
     * @type {string}
     * @memberof ActionTypeResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the ActionTypeResponse interface.
 */
export function instanceOfActionTypeResponse(value: object): value is ActionTypeResponse {
    return true;
}

export function ActionTypeResponseFromJSON(json: any): ActionTypeResponse {
    return ActionTypeResponseFromJSONTyped(json, false);
}

export function ActionTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ActionTypeResponseToJSON(json: any): ActionTypeResponse {
    return ActionTypeResponseToJSONTyped(json, false);
}

export function ActionTypeResponseToJSONTyped(value?: ActionTypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

