/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a response for an amendments list item.
 * @export
 * @interface AmendmentsListItemResponse
 */
export interface AmendmentsListItemResponse {
    /**
     * Gets the amendment identifier.
     * @type {string}
     * @memberof AmendmentsListItemResponse
     */
    id?: string;
    /**
     * Gets the identifier of the idea this amendment belongs to.
     * @type {string}
     * @memberof AmendmentsListItemResponse
     */
    ideaId?: string;
    /**
     * Gets a value indicating whether the content was authored by the current user.
     * @type {boolean}
     * @memberof AmendmentsListItemResponse
     */
    authoredByCurrentUser?: boolean;
    /**
     * Gets the author identifier.
     * @type {string}
     * @memberof AmendmentsListItemResponse
     */
    authorPseudonym?: string;
    /**
     * Gets the amendment title.
     * @type {string}
     * @memberof AmendmentsListItemResponse
     */
    amendmentTitle?: string;
    /**
     * Gets the amendment description.
     * @type {string}
     * @memberof AmendmentsListItemResponse
     */
    amendmentDescription?: string;
    /**
     * Gets the status of the amendment.
     * @type {string}
     * @memberof AmendmentsListItemResponse
     */
    status?: string;
    /**
     * Gets the number of opponents for this amendment.
     * @type {number}
     * @memberof AmendmentsListItemResponse
     */
    opponentCount?: number;
    /**
     * Gets a value indicating whether the current user has opposed the item.
     * @type {boolean}
     * @memberof AmendmentsListItemResponse
     */
    opposedByCurrentUser?: boolean;
    /**
     * Gets the number of supporters for this amendment.
     * @type {number}
     * @memberof AmendmentsListItemResponse
     */
    supporterCount?: number;
    /**
     * Gets the number of items or features supported by the current user.
     * @type {boolean}
     * @memberof AmendmentsListItemResponse
     */
    supportedByCurrentUser?: boolean;
    /**
     * Gets when the amendment was created.
     * @type {Date}
     * @memberof AmendmentsListItemResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the AmendmentsListItemResponse interface.
 */
export function instanceOfAmendmentsListItemResponse(value: object): value is AmendmentsListItemResponse {
    return true;
}

export function AmendmentsListItemResponseFromJSON(json: any): AmendmentsListItemResponse {
    return AmendmentsListItemResponseFromJSONTyped(json, false);
}

export function AmendmentsListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmendmentsListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ideaId': json['ideaId'] == null ? undefined : json['ideaId'],
        'authoredByCurrentUser': json['authoredByCurrentUser'] == null ? undefined : json['authoredByCurrentUser'],
        'authorPseudonym': json['authorPseudonym'] == null ? undefined : json['authorPseudonym'],
        'amendmentTitle': json['amendmentTitle'] == null ? undefined : json['amendmentTitle'],
        'amendmentDescription': json['amendmentDescription'] == null ? undefined : json['amendmentDescription'],
        'status': json['status'] == null ? undefined : json['status'],
        'opponentCount': json['opponentCount'] == null ? undefined : json['opponentCount'],
        'opposedByCurrentUser': json['opposedByCurrentUser'] == null ? undefined : json['opposedByCurrentUser'],
        'supporterCount': json['supporterCount'] == null ? undefined : json['supporterCount'],
        'supportedByCurrentUser': json['supportedByCurrentUser'] == null ? undefined : json['supportedByCurrentUser'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function AmendmentsListItemResponseToJSON(json: any): AmendmentsListItemResponse {
    return AmendmentsListItemResponseToJSONTyped(json, false);
}

export function AmendmentsListItemResponseToJSONTyped(value?: AmendmentsListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ideaId': value['ideaId'],
        'authoredByCurrentUser': value['authoredByCurrentUser'],
        'authorPseudonym': value['authorPseudonym'],
        'amendmentTitle': value['amendmentTitle'],
        'amendmentDescription': value['amendmentDescription'],
        'status': value['status'],
        'opponentCount': value['opponentCount'],
        'opposedByCurrentUser': value['opposedByCurrentUser'],
        'supporterCount': value['supporterCount'],
        'supportedByCurrentUser': value['supportedByCurrentUser'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

