/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrendPointResponse } from './TrendPointResponse';
import {
    TrendPointResponseFromJSON,
    TrendPointResponseFromJSONTyped,
    TrendPointResponseToJSON,
    TrendPointResponseToJSONTyped,
} from './TrendPointResponse';

/**
 * Response model for amendment support trend data.
 * @export
 * @interface AmendmentTrendResponse
 */
export interface AmendmentTrendResponse {
    /**
     * Gets the amendment identifier.
     * @type {string}
     * @memberof AmendmentTrendResponse
     */
    amendmentId?: string;
    /**
     * Gets the collection of trend data points showing supporter/opponent counts over time.
     * @type {Array<TrendPointResponse>}
     * @memberof AmendmentTrendResponse
     */
    dataPoints?: Array<TrendPointResponse>;
}

/**
 * Check if a given object implements the AmendmentTrendResponse interface.
 */
export function instanceOfAmendmentTrendResponse(value: object): value is AmendmentTrendResponse {
    return true;
}

export function AmendmentTrendResponseFromJSON(json: any): AmendmentTrendResponse {
    return AmendmentTrendResponseFromJSONTyped(json, false);
}

export function AmendmentTrendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmendmentTrendResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amendmentId': json['amendmentId'] == null ? undefined : json['amendmentId'],
        'dataPoints': json['dataPoints'] == null ? undefined : ((json['dataPoints'] as Array<any>).map(TrendPointResponseFromJSON)),
    };
}

export function AmendmentTrendResponseToJSON(json: any): AmendmentTrendResponse {
    return AmendmentTrendResponseToJSONTyped(json, false);
}

export function AmendmentTrendResponseToJSONTyped(value?: AmendmentTrendResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amendmentId': value['amendmentId'],
        'dataPoints': value['dataPoints'] == null ? undefined : ((value['dataPoints'] as Array<any>).map(TrendPointResponseToJSON)),
    };
}

