/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for a project amendment.
 * @export
 * @interface Amendment
 */
export interface Amendment {
    /**
     * The amendment identifier.
     * @type {string}
     * @memberof Amendment
     */
    id?: string;
    /**
     * The participant who proposed the amendment.
     * @type {string}
     * @memberof Amendment
     */
    proposedById?: string;
    /**
     * When the amendment was proposed.
     * @type {Date}
     * @memberof Amendment
     */
    proposedAt?: Date;
    /**
     * The amendment status.
     * @type {string}
     * @memberof Amendment
     */
    status?: string;
    /**
     * The participant contesting the amendment, when contested.
     * @type {string}
     * @memberof Amendment
     */
    contestedById?: string | null;
    /**
     * When the amendment was contested, when contested.
     * @type {Date}
     * @memberof Amendment
     */
    contestedAt?: Date | null;
    /**
     * When the amendment status was last changed.
     * @type {Date}
     * @memberof Amendment
     */
    lastStatusChangedAt?: Date;
}

/**
 * Check if a given object implements the Amendment interface.
 */
export function instanceOfAmendment(value: object): value is Amendment {
    return true;
}

export function AmendmentFromJSON(json: any): Amendment {
    return AmendmentFromJSONTyped(json, false);
}

export function AmendmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Amendment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'proposedById': json['proposedById'] == null ? undefined : json['proposedById'],
        'proposedAt': json['proposedAt'] == null ? undefined : (new Date(json['proposedAt'])),
        'status': json['status'] == null ? undefined : json['status'],
        'contestedById': json['contestedById'] == null ? undefined : json['contestedById'],
        'contestedAt': json['contestedAt'] == null ? undefined : (new Date(json['contestedAt'])),
        'lastStatusChangedAt': json['lastStatusChangedAt'] == null ? undefined : (new Date(json['lastStatusChangedAt'])),
    };
}

export function AmendmentToJSON(json: any): Amendment {
    return AmendmentToJSONTyped(json, false);
}

export function AmendmentToJSONTyped(value?: Amendment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'proposedById': value['proposedById'],
        'proposedAt': value['proposedAt'] == null ? undefined : ((value['proposedAt']).toISOString()),
        'status': value['status'],
        'contestedById': value['contestedById'],
        'contestedAt': value['contestedAt'] === null ? null : ((value['contestedAt'] as any)?.toISOString()),
        'lastStatusChangedAt': value['lastStatusChangedAt'] == null ? undefined : ((value['lastStatusChangedAt']).toISOString()),
    };
}

