/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * View model for idea amendments, tailored for frontend display.
 * @export
 * @interface AmendmentViewModel
 */
export interface AmendmentViewModel {
    /**
     * The unique identifier of the amendment.
     * @type {string}
     * @memberof AmendmentViewModel
     */
    id?: string;
    /**
     * The title of the amendment.
     * @type {string}
     * @memberof AmendmentViewModel
     */
    title?: string;
    /**
     * A short description of the amendment for display in lists.
     * @type {string}
     * @memberof AmendmentViewModel
     */
    shortDescription?: string;
    /**
     * The proposed title for the idea.
     * @type {string}
     * @memberof AmendmentViewModel
     */
    proposedTitle?: string;
    /**
     * The proposed body/content for the idea.
     * @type {string}
     * @memberof AmendmentViewModel
     */
    proposedBody?: string;
    /**
     * Gets or sets a value indicating whether the proposal was made by the current user.
     * @type {boolean}
     * @memberof AmendmentViewModel
     */
    proposedByCurrentUser?: boolean;
    /**
     * The pseudonym of the proposer.
     * @type {string}
     * @memberof AmendmentViewModel
     */
    proposerPseudonym?: string;
    /**
     * The status of the amendment: open, approved, rejected, withdrawn, outdated.
     * @type {string}
     * @memberof AmendmentViewModel
     */
    status?: string;
    /**
     * The version number of the target idea this amendment applies to.
     * @type {number}
     * @memberof AmendmentViewModel
     */
    targetVersionNumber?: number;
    /**
     * The creation timestamp in ISO 8601 format.
     * @type {string}
     * @memberof AmendmentViewModel
     */
    propsedAt?: string;
    /**
     * The total number of supporters.
     * @type {number}
     * @memberof AmendmentViewModel
     */
    supporterCount?: number;
    /**
     * The total number of opponents.
     * @type {number}
     * @memberof AmendmentViewModel
     */
    opponentCount?: number;
    /**
     * The acceptance timestamp in ISO 8601 format (if approved).
     * @type {string}
     * @memberof AmendmentViewModel
     */
    acceptedOn?: string | null;
    /**
     * The rejection timestamp in ISO 8601 format (if rejected).
     * @type {string}
     * @memberof AmendmentViewModel
     */
    rejectedOn?: string | null;
    /**
     * Whether the current user has supported this amendment.
     * @type {boolean}
     * @memberof AmendmentViewModel
     */
    supportedByCurrentUser?: boolean;
    /**
     * Whether the current user has opposed this amendment.
     * @type {boolean}
     * @memberof AmendmentViewModel
     */
    opposedByCurrentUser?: boolean;
}

/**
 * Check if a given object implements the AmendmentViewModel interface.
 */
export function instanceOfAmendmentViewModel(value: object): value is AmendmentViewModel {
    return true;
}

export function AmendmentViewModelFromJSON(json: any): AmendmentViewModel {
    return AmendmentViewModelFromJSONTyped(json, false);
}

export function AmendmentViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmendmentViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'shortDescription': json['shortDescription'] == null ? undefined : json['shortDescription'],
        'proposedTitle': json['proposedTitle'] == null ? undefined : json['proposedTitle'],
        'proposedBody': json['proposedBody'] == null ? undefined : json['proposedBody'],
        'proposedByCurrentUser': json['proposedByCurrentUser'] == null ? undefined : json['proposedByCurrentUser'],
        'proposerPseudonym': json['proposerPseudonym'] == null ? undefined : json['proposerPseudonym'],
        'status': json['status'] == null ? undefined : json['status'],
        'targetVersionNumber': json['targetVersionNumber'] == null ? undefined : json['targetVersionNumber'],
        'propsedAt': json['propsedAt'] == null ? undefined : json['propsedAt'],
        'supporterCount': json['supporterCount'] == null ? undefined : json['supporterCount'],
        'opponentCount': json['opponentCount'] == null ? undefined : json['opponentCount'],
        'acceptedOn': json['acceptedOn'] == null ? undefined : json['acceptedOn'],
        'rejectedOn': json['rejectedOn'] == null ? undefined : json['rejectedOn'],
        'supportedByCurrentUser': json['supportedByCurrentUser'] == null ? undefined : json['supportedByCurrentUser'],
        'opposedByCurrentUser': json['opposedByCurrentUser'] == null ? undefined : json['opposedByCurrentUser'],
    };
}

export function AmendmentViewModelToJSON(json: any): AmendmentViewModel {
    return AmendmentViewModelToJSONTyped(json, false);
}

export function AmendmentViewModelToJSONTyped(value?: AmendmentViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'shortDescription': value['shortDescription'],
        'proposedTitle': value['proposedTitle'],
        'proposedBody': value['proposedBody'],
        'proposedByCurrentUser': value['proposedByCurrentUser'],
        'proposerPseudonym': value['proposerPseudonym'],
        'status': value['status'],
        'targetVersionNumber': value['targetVersionNumber'],
        'propsedAt': value['propsedAt'],
        'supporterCount': value['supporterCount'],
        'opponentCount': value['opponentCount'],
        'acceptedOn': value['acceptedOn'],
        'rejectedOn': value['rejectedOn'],
        'supportedByCurrentUser': value['supportedByCurrentUser'],
        'opposedByCurrentUser': value['opposedByCurrentUser'],
    };
}

