/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for an amendment supporter.
 * @export
 * @interface AmendmentSupporterResponse
 */
export interface AmendmentSupporterResponse {
    /**
     * Gets the unique identifier of the supporter record.
     * @type {string}
     * @memberof AmendmentSupporterResponse
     */
    id?: string;
    /**
     * Gets the pseudonym of the supporter.
     * @type {string}
     * @memberof AmendmentSupporterResponse
     */
    pseudonym?: string;
    /**
     * Gets the reason provided by the supporter for supporting the amendment.
     * @type {string}
     * @memberof AmendmentSupporterResponse
     */
    reason?: string;
    /**
     * Gets when the support was added.
     * @type {string}
     * @memberof AmendmentSupporterResponse
     */
    supportedAt?: string;
}

/**
 * Check if a given object implements the AmendmentSupporterResponse interface.
 */
export function instanceOfAmendmentSupporterResponse(value: object): value is AmendmentSupporterResponse {
    return true;
}

export function AmendmentSupporterResponseFromJSON(json: any): AmendmentSupporterResponse {
    return AmendmentSupporterResponseFromJSONTyped(json, false);
}

export function AmendmentSupporterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmendmentSupporterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'pseudonym': json['pseudonym'] == null ? undefined : json['pseudonym'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'supportedAt': json['supportedAt'] == null ? undefined : json['supportedAt'],
    };
}

export function AmendmentSupporterResponseToJSON(json: any): AmendmentSupporterResponse {
    return AmendmentSupporterResponseToJSONTyped(json, false);
}

export function AmendmentSupporterResponseToJSONTyped(value?: AmendmentSupporterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pseudonym': value['pseudonym'],
        'reason': value['reason'],
        'supportedAt': value['supportedAt'],
    };
}

