/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for amendment voting operations (support, oppose, withdraw support, withdraw opposition).
 * @export
 * @interface AmendmentVoteResponse
 */
export interface AmendmentVoteResponse {
    /**
     * The updated number of supporters for this amendment.
     * @type {number}
     * @memberof AmendmentVoteResponse
     */
    supporterCount?: number;
    /**
     * The updated number of opponents for this amendment.
     * @type {number}
     * @memberof AmendmentVoteResponse
     */
    opponentCount?: number;
}

/**
 * Check if a given object implements the AmendmentVoteResponse interface.
 */
export function instanceOfAmendmentVoteResponse(value: object): value is AmendmentVoteResponse {
    return true;
}

export function AmendmentVoteResponseFromJSON(json: any): AmendmentVoteResponse {
    return AmendmentVoteResponseFromJSONTyped(json, false);
}

export function AmendmentVoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmendmentVoteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'supporterCount': json['supporterCount'] == null ? undefined : json['supporterCount'],
        'opponentCount': json['opponentCount'] == null ? undefined : json['opponentCount'],
    };
}

export function AmendmentVoteResponseToJSON(json: any): AmendmentVoteResponse {
    return AmendmentVoteResponseToJSONTyped(json, false);
}

export function AmendmentVoteResponseToJSONTyped(value?: AmendmentVoteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supporterCount': value['supporterCount'],
        'opponentCount': value['opponentCount'],
    };
}

