/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * View model for signal amplifications.
 * @export
 * @interface AmplificationViewModel
 */
export interface AmplificationViewModel {
    /**
     * The unique identifier of the amplification.
     * @type {string}
     * @memberof AmplificationViewModel
     */
    id?: string;
    /**
     * The pseudonym of the person who amplified the signal.
     * @type {string}
     * @memberof AmplificationViewModel
     */
    amplifierPseudonym?: string;
    /**
     * The amplification timestamp in ISO 8601 format.
     * @type {string}
     * @memberof AmplificationViewModel
     */
    amplifiedAt?: string;
    /**
     * Optional comment provided with the amplification.
     * @type {string}
     * @memberof AmplificationViewModel
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the AmplificationViewModel interface.
 */
export function instanceOfAmplificationViewModel(value: object): value is AmplificationViewModel {
    return true;
}

export function AmplificationViewModelFromJSON(json: any): AmplificationViewModel {
    return AmplificationViewModelFromJSONTyped(json, false);
}

export function AmplificationViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmplificationViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'amplifierPseudonym': json['amplifierPseudonym'] == null ? undefined : json['amplifierPseudonym'],
        'amplifiedAt': json['amplifiedAt'] == null ? undefined : json['amplifiedAt'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function AmplificationViewModelToJSON(json: any): AmplificationViewModel {
    return AmplificationViewModelToJSONTyped(json, false);
}

export function AmplificationViewModelToJSONTyped(value?: AmplificationViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amplifierPseudonym': value['amplifierPseudonym'],
        'amplifiedAt': value['amplifiedAt'],
        'comment': value['comment'],
    };
}

