/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostsViewModel } from './PostsViewModel';
import {
    PostsViewModelFromJSON,
    PostsViewModelFromJSONTyped,
    PostsViewModelToJSON,
    PostsViewModelToJSONTyped,
} from './PostsViewModel';

/**
 * Generic API response envelope that wraps data with metadata.
 * @export
 * @interface ApiEnvelopeOfPostsViewModel
 */
export interface ApiEnvelopeOfPostsViewModel {
    /**
     * Unique identifier for the request.
     * @type {string}
     * @memberof ApiEnvelopeOfPostsViewModel
     */
    requestId?: string;
    /**
     * Timestamp when the response was generated.
     * @type {Date}
     * @memberof ApiEnvelopeOfPostsViewModel
     */
    timestamp?: Date;
    /**
     * 
     * @type {PostsViewModel}
     * @memberof ApiEnvelopeOfPostsViewModel
     */
    data?: PostsViewModel | null;
}

/**
 * Check if a given object implements the ApiEnvelopeOfPostsViewModel interface.
 */
export function instanceOfApiEnvelopeOfPostsViewModel(value: object): value is ApiEnvelopeOfPostsViewModel {
    return true;
}

export function ApiEnvelopeOfPostsViewModelFromJSON(json: any): ApiEnvelopeOfPostsViewModel {
    return ApiEnvelopeOfPostsViewModelFromJSONTyped(json, false);
}

export function ApiEnvelopeOfPostsViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEnvelopeOfPostsViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'data': json['data'] == null ? undefined : PostsViewModelFromJSON(json['data']),
    };
}

export function ApiEnvelopeOfPostsViewModelToJSON(json: any): ApiEnvelopeOfPostsViewModel {
    return ApiEnvelopeOfPostsViewModelToJSONTyped(json, false);
}

export function ApiEnvelopeOfPostsViewModelToJSONTyped(value?: ApiEnvelopeOfPostsViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestId': value['requestId'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'data': PostsViewModelToJSON(value['data']),
    };
}

