/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfUserGroupMemberResponse } from './PaginatedResponseOfUserGroupMemberResponse';
import {
    PaginatedResponseOfUserGroupMemberResponseFromJSON,
    PaginatedResponseOfUserGroupMemberResponseFromJSONTyped,
    PaginatedResponseOfUserGroupMemberResponseToJSON,
    PaginatedResponseOfUserGroupMemberResponseToJSONTyped,
} from './PaginatedResponseOfUserGroupMemberResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfPaginatedResponseOfUserGroupMemberResponse
 */
export interface ApiResponseOfPaginatedResponseOfUserGroupMemberResponse {
    /**
     * 
     * @type {PaginatedResponseOfUserGroupMemberResponse}
     * @memberof ApiResponseOfPaginatedResponseOfUserGroupMemberResponse
     */
    data?: PaginatedResponseOfUserGroupMemberResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfPaginatedResponseOfUserGroupMemberResponse interface.
 */
export function instanceOfApiResponseOfPaginatedResponseOfUserGroupMemberResponse(value: object): value is ApiResponseOfPaginatedResponseOfUserGroupMemberResponse {
    return true;
}

export function ApiResponseOfPaginatedResponseOfUserGroupMemberResponseFromJSON(json: any): ApiResponseOfPaginatedResponseOfUserGroupMemberResponse {
    return ApiResponseOfPaginatedResponseOfUserGroupMemberResponseFromJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfUserGroupMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfPaginatedResponseOfUserGroupMemberResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PaginatedResponseOfUserGroupMemberResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfPaginatedResponseOfUserGroupMemberResponseToJSON(json: any): ApiResponseOfPaginatedResponseOfUserGroupMemberResponse {
    return ApiResponseOfPaginatedResponseOfUserGroupMemberResponseToJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfUserGroupMemberResponseToJSONTyped(value?: ApiResponseOfPaginatedResponseOfUserGroupMemberResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaginatedResponseOfUserGroupMemberResponseToJSON(value['data']),
    };
}

