/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProposeAmendmentResponse } from './ProposeAmendmentResponse';
import {
    ProposeAmendmentResponseFromJSON,
    ProposeAmendmentResponseFromJSONTyped,
    ProposeAmendmentResponseToJSON,
    ProposeAmendmentResponseToJSONTyped,
} from './ProposeAmendmentResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfProposeAmendmentResponse
 */
export interface ApiResponseOfProposeAmendmentResponse {
    /**
     * 
     * @type {ProposeAmendmentResponse}
     * @memberof ApiResponseOfProposeAmendmentResponse
     */
    data?: ProposeAmendmentResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfProposeAmendmentResponse interface.
 */
export function instanceOfApiResponseOfProposeAmendmentResponse(value: object): value is ApiResponseOfProposeAmendmentResponse {
    return true;
}

export function ApiResponseOfProposeAmendmentResponseFromJSON(json: any): ApiResponseOfProposeAmendmentResponse {
    return ApiResponseOfProposeAmendmentResponseFromJSONTyped(json, false);
}

export function ApiResponseOfProposeAmendmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfProposeAmendmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ProposeAmendmentResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfProposeAmendmentResponseToJSON(json: any): ApiResponseOfProposeAmendmentResponse {
    return ApiResponseOfProposeAmendmentResponseToJSONTyped(json, false);
}

export function ApiResponseOfProposeAmendmentResponseToJSONTyped(value?: ApiResponseOfProposeAmendmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ProposeAmendmentResponseToJSON(value['data']),
    };
}

