/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeamplifySignalResponse } from './DeamplifySignalResponse';
import {
    DeamplifySignalResponseFromJSON,
    DeamplifySignalResponseFromJSONTyped,
    DeamplifySignalResponseToJSON,
    DeamplifySignalResponseToJSONTyped,
} from './DeamplifySignalResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfDeamplifySignalResponse
 */
export interface ApiResponseOfDeamplifySignalResponse {
    /**
     * 
     * @type {DeamplifySignalResponse}
     * @memberof ApiResponseOfDeamplifySignalResponse
     */
    data?: DeamplifySignalResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfDeamplifySignalResponse interface.
 */
export function instanceOfApiResponseOfDeamplifySignalResponse(value: object): value is ApiResponseOfDeamplifySignalResponse {
    return true;
}

export function ApiResponseOfDeamplifySignalResponseFromJSON(json: any): ApiResponseOfDeamplifySignalResponse {
    return ApiResponseOfDeamplifySignalResponseFromJSONTyped(json, false);
}

export function ApiResponseOfDeamplifySignalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfDeamplifySignalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DeamplifySignalResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfDeamplifySignalResponseToJSON(json: any): ApiResponseOfDeamplifySignalResponse {
    return ApiResponseOfDeamplifySignalResponseToJSONTyped(json, false);
}

export function ApiResponseOfDeamplifySignalResponseToJSONTyped(value?: ApiResponseOfDeamplifySignalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DeamplifySignalResponseToJSON(value['data']),
    };
}

