/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConcernListItemResponse } from './ConcernListItemResponse';
import {
    ConcernListItemResponseFromJSON,
    ConcernListItemResponseFromJSONTyped,
    ConcernListItemResponseToJSON,
    ConcernListItemResponseToJSONTyped,
} from './ConcernListItemResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfIReadOnlyListOfConcernListItemResponse
 */
export interface ApiResponseOfIReadOnlyListOfConcernListItemResponse {
    /**
     * Gets or sets the response data.
     * @type {Array<ConcernListItemResponse>}
     * @memberof ApiResponseOfIReadOnlyListOfConcernListItemResponse
     */
    data?: Array<ConcernListItemResponse> | null;
}

/**
 * Check if a given object implements the ApiResponseOfIReadOnlyListOfConcernListItemResponse interface.
 */
export function instanceOfApiResponseOfIReadOnlyListOfConcernListItemResponse(value: object): value is ApiResponseOfIReadOnlyListOfConcernListItemResponse {
    return true;
}

export function ApiResponseOfIReadOnlyListOfConcernListItemResponseFromJSON(json: any): ApiResponseOfIReadOnlyListOfConcernListItemResponse {
    return ApiResponseOfIReadOnlyListOfConcernListItemResponseFromJSONTyped(json, false);
}

export function ApiResponseOfIReadOnlyListOfConcernListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfIReadOnlyListOfConcernListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ConcernListItemResponseFromJSON)),
    };
}

export function ApiResponseOfIReadOnlyListOfConcernListItemResponseToJSON(json: any): ApiResponseOfIReadOnlyListOfConcernListItemResponse {
    return ApiResponseOfIReadOnlyListOfConcernListItemResponseToJSONTyped(json, false);
}

export function ApiResponseOfIReadOnlyListOfConcernListItemResponseToJSONTyped(value?: ApiResponseOfIReadOnlyListOfConcernListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ConcernListItemResponseToJSON)),
    };
}

