/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfSocietyMemberResponse } from './PaginatedResponseOfSocietyMemberResponse';
import {
    PaginatedResponseOfSocietyMemberResponseFromJSON,
    PaginatedResponseOfSocietyMemberResponseFromJSONTyped,
    PaginatedResponseOfSocietyMemberResponseToJSON,
    PaginatedResponseOfSocietyMemberResponseToJSONTyped,
} from './PaginatedResponseOfSocietyMemberResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfPaginatedResponseOfSocietyMemberResponse
 */
export interface ApiResponseOfPaginatedResponseOfSocietyMemberResponse {
    /**
     * 
     * @type {PaginatedResponseOfSocietyMemberResponse}
     * @memberof ApiResponseOfPaginatedResponseOfSocietyMemberResponse
     */
    data?: PaginatedResponseOfSocietyMemberResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfPaginatedResponseOfSocietyMemberResponse interface.
 */
export function instanceOfApiResponseOfPaginatedResponseOfSocietyMemberResponse(value: object): value is ApiResponseOfPaginatedResponseOfSocietyMemberResponse {
    return true;
}

export function ApiResponseOfPaginatedResponseOfSocietyMemberResponseFromJSON(json: any): ApiResponseOfPaginatedResponseOfSocietyMemberResponse {
    return ApiResponseOfPaginatedResponseOfSocietyMemberResponseFromJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfSocietyMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfPaginatedResponseOfSocietyMemberResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PaginatedResponseOfSocietyMemberResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfPaginatedResponseOfSocietyMemberResponseToJSON(json: any): ApiResponseOfPaginatedResponseOfSocietyMemberResponse {
    return ApiResponseOfPaginatedResponseOfSocietyMemberResponseToJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfSocietyMemberResponseToJSONTyped(value?: ApiResponseOfPaginatedResponseOfSocietyMemberResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaginatedResponseOfSocietyMemberResponseToJSON(value['data']),
    };
}

