/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdeasFeedViewModel } from './IdeasFeedViewModel';
import {
    IdeasFeedViewModelFromJSON,
    IdeasFeedViewModelFromJSONTyped,
    IdeasFeedViewModelToJSON,
    IdeasFeedViewModelToJSONTyped,
} from './IdeasFeedViewModel';

/**
 * 
 * @export
 * @interface ApiResponseOfIdeasFeedViewModel
 */
export interface ApiResponseOfIdeasFeedViewModel {
    /**
     * 
     * @type {IdeasFeedViewModel}
     * @memberof ApiResponseOfIdeasFeedViewModel
     */
    data?: IdeasFeedViewModel | null;
}

/**
 * Check if a given object implements the ApiResponseOfIdeasFeedViewModel interface.
 */
export function instanceOfApiResponseOfIdeasFeedViewModel(value: object): value is ApiResponseOfIdeasFeedViewModel {
    return true;
}

export function ApiResponseOfIdeasFeedViewModelFromJSON(json: any): ApiResponseOfIdeasFeedViewModel {
    return ApiResponseOfIdeasFeedViewModelFromJSONTyped(json, false);
}

export function ApiResponseOfIdeasFeedViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfIdeasFeedViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : IdeasFeedViewModelFromJSON(json['data']),
    };
}

export function ApiResponseOfIdeasFeedViewModelToJSON(json: any): ApiResponseOfIdeasFeedViewModel {
    return ApiResponseOfIdeasFeedViewModelToJSONTyped(json, false);
}

export function ApiResponseOfIdeasFeedViewModelToJSONTyped(value?: ApiResponseOfIdeasFeedViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': IdeasFeedViewModelToJSON(value['data']),
    };
}

