/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroupDetailResponse } from './UserGroupDetailResponse';
import {
    UserGroupDetailResponseFromJSON,
    UserGroupDetailResponseFromJSONTyped,
    UserGroupDetailResponseToJSON,
    UserGroupDetailResponseToJSONTyped,
} from './UserGroupDetailResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfUserGroupDetailResponse
 */
export interface ApiResponseOfUserGroupDetailResponse {
    /**
     * 
     * @type {UserGroupDetailResponse}
     * @memberof ApiResponseOfUserGroupDetailResponse
     */
    data?: UserGroupDetailResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfUserGroupDetailResponse interface.
 */
export function instanceOfApiResponseOfUserGroupDetailResponse(value: object): value is ApiResponseOfUserGroupDetailResponse {
    return true;
}

export function ApiResponseOfUserGroupDetailResponseFromJSON(json: any): ApiResponseOfUserGroupDetailResponse {
    return ApiResponseOfUserGroupDetailResponseFromJSONTyped(json, false);
}

export function ApiResponseOfUserGroupDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfUserGroupDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : UserGroupDetailResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfUserGroupDetailResponseToJSON(json: any): ApiResponseOfUserGroupDetailResponse {
    return ApiResponseOfUserGroupDetailResponseToJSONTyped(json, false);
}

export function ApiResponseOfUserGroupDetailResponseToJSONTyped(value?: ApiResponseOfUserGroupDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UserGroupDetailResponseToJSON(value['data']),
    };
}

