/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrustInviteLinkViewResponse } from './TrustInviteLinkViewResponse';
import {
    TrustInviteLinkViewResponseFromJSON,
    TrustInviteLinkViewResponseFromJSONTyped,
    TrustInviteLinkViewResponseToJSON,
    TrustInviteLinkViewResponseToJSONTyped,
} from './TrustInviteLinkViewResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse
 */
export interface ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse {
    /**
     * Gets or sets the response data.
     * @type {Array<TrustInviteLinkViewResponse>}
     * @memberof ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse
     */
    data?: Array<TrustInviteLinkViewResponse> | null;
}

/**
 * Check if a given object implements the ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse interface.
 */
export function instanceOfApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse(value: object): value is ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse {
    return true;
}

export function ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseFromJSON(json: any): ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse {
    return ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseFromJSONTyped(json, false);
}

export function ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TrustInviteLinkViewResponseFromJSON)),
    };
}

export function ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseToJSON(json: any): ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse {
    return ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseToJSONTyped(json, false);
}

export function ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponseToJSONTyped(value?: ApiResponseOfIReadOnlyListOfTrustInviteLinkViewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TrustInviteLinkViewResponseToJSON)),
    };
}

