/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AmplifySignalResponse } from './AmplifySignalResponse';
import {
    AmplifySignalResponseFromJSON,
    AmplifySignalResponseFromJSONTyped,
    AmplifySignalResponseToJSON,
    AmplifySignalResponseToJSONTyped,
} from './AmplifySignalResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfAmplifySignalResponse
 */
export interface ApiResponseOfAmplifySignalResponse {
    /**
     * 
     * @type {AmplifySignalResponse}
     * @memberof ApiResponseOfAmplifySignalResponse
     */
    data?: AmplifySignalResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfAmplifySignalResponse interface.
 */
export function instanceOfApiResponseOfAmplifySignalResponse(value: object): value is ApiResponseOfAmplifySignalResponse {
    return true;
}

export function ApiResponseOfAmplifySignalResponseFromJSON(json: any): ApiResponseOfAmplifySignalResponse {
    return ApiResponseOfAmplifySignalResponseFromJSONTyped(json, false);
}

export function ApiResponseOfAmplifySignalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfAmplifySignalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AmplifySignalResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfAmplifySignalResponseToJSON(json: any): ApiResponseOfAmplifySignalResponse {
    return ApiResponseOfAmplifySignalResponseToJSONTyped(json, false);
}

export function ApiResponseOfAmplifySignalResponseToJSONTyped(value?: ApiResponseOfAmplifySignalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AmplifySignalResponseToJSON(value['data']),
    };
}

