/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroupListItemResponse } from './UserGroupListItemResponse';
import {
    UserGroupListItemResponseFromJSON,
    UserGroupListItemResponseFromJSONTyped,
    UserGroupListItemResponseToJSON,
    UserGroupListItemResponseToJSONTyped,
} from './UserGroupListItemResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfIReadOnlyListOfUserGroupListItemResponse
 */
export interface ApiResponseOfIReadOnlyListOfUserGroupListItemResponse {
    /**
     * Gets or sets the response data.
     * @type {Array<UserGroupListItemResponse>}
     * @memberof ApiResponseOfIReadOnlyListOfUserGroupListItemResponse
     */
    data?: Array<UserGroupListItemResponse> | null;
}

/**
 * Check if a given object implements the ApiResponseOfIReadOnlyListOfUserGroupListItemResponse interface.
 */
export function instanceOfApiResponseOfIReadOnlyListOfUserGroupListItemResponse(value: object): value is ApiResponseOfIReadOnlyListOfUserGroupListItemResponse {
    return true;
}

export function ApiResponseOfIReadOnlyListOfUserGroupListItemResponseFromJSON(json: any): ApiResponseOfIReadOnlyListOfUserGroupListItemResponse {
    return ApiResponseOfIReadOnlyListOfUserGroupListItemResponseFromJSONTyped(json, false);
}

export function ApiResponseOfIReadOnlyListOfUserGroupListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfIReadOnlyListOfUserGroupListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(UserGroupListItemResponseFromJSON)),
    };
}

export function ApiResponseOfIReadOnlyListOfUserGroupListItemResponseToJSON(json: any): ApiResponseOfIReadOnlyListOfUserGroupListItemResponse {
    return ApiResponseOfIReadOnlyListOfUserGroupListItemResponseToJSONTyped(json, false);
}

export function ApiResponseOfIReadOnlyListOfUserGroupListItemResponseToJSONTyped(value?: ApiResponseOfIReadOnlyListOfUserGroupListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(UserGroupListItemResponseToJSON)),
    };
}

