/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SignalAmplificationTrendResponse } from './SignalAmplificationTrendResponse';
import {
    SignalAmplificationTrendResponseFromJSON,
    SignalAmplificationTrendResponseFromJSONTyped,
    SignalAmplificationTrendResponseToJSON,
    SignalAmplificationTrendResponseToJSONTyped,
} from './SignalAmplificationTrendResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfSignalAmplificationTrendResponse
 */
export interface ApiResponseOfSignalAmplificationTrendResponse {
    /**
     * 
     * @type {SignalAmplificationTrendResponse}
     * @memberof ApiResponseOfSignalAmplificationTrendResponse
     */
    data?: SignalAmplificationTrendResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfSignalAmplificationTrendResponse interface.
 */
export function instanceOfApiResponseOfSignalAmplificationTrendResponse(value: object): value is ApiResponseOfSignalAmplificationTrendResponse {
    return true;
}

export function ApiResponseOfSignalAmplificationTrendResponseFromJSON(json: any): ApiResponseOfSignalAmplificationTrendResponse {
    return ApiResponseOfSignalAmplificationTrendResponseFromJSONTyped(json, false);
}

export function ApiResponseOfSignalAmplificationTrendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfSignalAmplificationTrendResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : SignalAmplificationTrendResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfSignalAmplificationTrendResponseToJSON(json: any): ApiResponseOfSignalAmplificationTrendResponse {
    return ApiResponseOfSignalAmplificationTrendResponseToJSONTyped(json, false);
}

export function ApiResponseOfSignalAmplificationTrendResponseToJSONTyped(value?: ApiResponseOfSignalAmplificationTrendResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SignalAmplificationTrendResponseToJSON(value['data']),
    };
}

