/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmergingPatternsFeedViewModel } from './EmergingPatternsFeedViewModel';
import {
    EmergingPatternsFeedViewModelFromJSON,
    EmergingPatternsFeedViewModelFromJSONTyped,
    EmergingPatternsFeedViewModelToJSON,
    EmergingPatternsFeedViewModelToJSONTyped,
} from './EmergingPatternsFeedViewModel';

/**
 * 
 * @export
 * @interface ApiResponseOfEmergingPatternsFeedViewModel
 */
export interface ApiResponseOfEmergingPatternsFeedViewModel {
    /**
     * 
     * @type {EmergingPatternsFeedViewModel}
     * @memberof ApiResponseOfEmergingPatternsFeedViewModel
     */
    data?: EmergingPatternsFeedViewModel | null;
}

/**
 * Check if a given object implements the ApiResponseOfEmergingPatternsFeedViewModel interface.
 */
export function instanceOfApiResponseOfEmergingPatternsFeedViewModel(value: object): value is ApiResponseOfEmergingPatternsFeedViewModel {
    return true;
}

export function ApiResponseOfEmergingPatternsFeedViewModelFromJSON(json: any): ApiResponseOfEmergingPatternsFeedViewModel {
    return ApiResponseOfEmergingPatternsFeedViewModelFromJSONTyped(json, false);
}

export function ApiResponseOfEmergingPatternsFeedViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfEmergingPatternsFeedViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : EmergingPatternsFeedViewModelFromJSON(json['data']),
    };
}

export function ApiResponseOfEmergingPatternsFeedViewModelToJSON(json: any): ApiResponseOfEmergingPatternsFeedViewModel {
    return ApiResponseOfEmergingPatternsFeedViewModelToJSONTyped(json, false);
}

export function ApiResponseOfEmergingPatternsFeedViewModelToJSONTyped(value?: ApiResponseOfEmergingPatternsFeedViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EmergingPatternsFeedViewModelToJSON(value['data']),
    };
}

