/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResolvedInviteLinkResponse } from './ResolvedInviteLinkResponse';
import {
    ResolvedInviteLinkResponseFromJSON,
    ResolvedInviteLinkResponseFromJSONTyped,
    ResolvedInviteLinkResponseToJSON,
    ResolvedInviteLinkResponseToJSONTyped,
} from './ResolvedInviteLinkResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfResolvedInviteLinkResponse
 */
export interface ApiResponseOfResolvedInviteLinkResponse {
    /**
     * 
     * @type {ResolvedInviteLinkResponse}
     * @memberof ApiResponseOfResolvedInviteLinkResponse
     */
    data?: ResolvedInviteLinkResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfResolvedInviteLinkResponse interface.
 */
export function instanceOfApiResponseOfResolvedInviteLinkResponse(value: object): value is ApiResponseOfResolvedInviteLinkResponse {
    return true;
}

export function ApiResponseOfResolvedInviteLinkResponseFromJSON(json: any): ApiResponseOfResolvedInviteLinkResponse {
    return ApiResponseOfResolvedInviteLinkResponseFromJSONTyped(json, false);
}

export function ApiResponseOfResolvedInviteLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfResolvedInviteLinkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ResolvedInviteLinkResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfResolvedInviteLinkResponseToJSON(json: any): ApiResponseOfResolvedInviteLinkResponse {
    return ApiResponseOfResolvedInviteLinkResponseToJSONTyped(json, false);
}

export function ApiResponseOfResolvedInviteLinkResponseToJSONTyped(value?: ApiResponseOfResolvedInviteLinkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ResolvedInviteLinkResponseToJSON(value['data']),
    };
}

