/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiResponseOfString
 */
export interface ApiResponseOfString {
    /**
     * Gets or sets the response data.
     * @type {string}
     * @memberof ApiResponseOfString
     */
    data?: string | null;
}

/**
 * Check if a given object implements the ApiResponseOfString interface.
 */
export function instanceOfApiResponseOfString(value: object): value is ApiResponseOfString {
    return true;
}

export function ApiResponseOfStringFromJSON(json: any): ApiResponseOfString {
    return ApiResponseOfStringFromJSONTyped(json, false);
}

export function ApiResponseOfStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfString {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ApiResponseOfStringToJSON(json: any): ApiResponseOfString {
    return ApiResponseOfStringToJSONTyped(json, false);
}

export function ApiResponseOfStringToJSONTyped(value?: ApiResponseOfString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

