/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfAmendmentsListItemResponse } from './PaginatedResponseOfAmendmentsListItemResponse';
import {
    PaginatedResponseOfAmendmentsListItemResponseFromJSON,
    PaginatedResponseOfAmendmentsListItemResponseFromJSONTyped,
    PaginatedResponseOfAmendmentsListItemResponseToJSON,
    PaginatedResponseOfAmendmentsListItemResponseToJSONTyped,
} from './PaginatedResponseOfAmendmentsListItemResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse
 */
export interface ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse {
    /**
     * 
     * @type {PaginatedResponseOfAmendmentsListItemResponse}
     * @memberof ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse
     */
    data?: PaginatedResponseOfAmendmentsListItemResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse interface.
 */
export function instanceOfApiResponseOfPaginatedResponseOfAmendmentsListItemResponse(value: object): value is ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse {
    return true;
}

export function ApiResponseOfPaginatedResponseOfAmendmentsListItemResponseFromJSON(json: any): ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse {
    return ApiResponseOfPaginatedResponseOfAmendmentsListItemResponseFromJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfAmendmentsListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PaginatedResponseOfAmendmentsListItemResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfPaginatedResponseOfAmendmentsListItemResponseToJSON(json: any): ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse {
    return ApiResponseOfPaginatedResponseOfAmendmentsListItemResponseToJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfAmendmentsListItemResponseToJSONTyped(value?: ApiResponseOfPaginatedResponseOfAmendmentsListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaginatedResponseOfAmendmentsListItemResponseToJSON(value['data']),
    };
}

