/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfAmendmentSupporterResponse } from './PaginatedResponseOfAmendmentSupporterResponse';
import {
    PaginatedResponseOfAmendmentSupporterResponseFromJSON,
    PaginatedResponseOfAmendmentSupporterResponseFromJSONTyped,
    PaginatedResponseOfAmendmentSupporterResponseToJSON,
    PaginatedResponseOfAmendmentSupporterResponseToJSONTyped,
} from './PaginatedResponseOfAmendmentSupporterResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse
 */
export interface ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse {
    /**
     * 
     * @type {PaginatedResponseOfAmendmentSupporterResponse}
     * @memberof ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse
     */
    data?: PaginatedResponseOfAmendmentSupporterResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse interface.
 */
export function instanceOfApiResponseOfPaginatedResponseOfAmendmentSupporterResponse(value: object): value is ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse {
    return true;
}

export function ApiResponseOfPaginatedResponseOfAmendmentSupporterResponseFromJSON(json: any): ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse {
    return ApiResponseOfPaginatedResponseOfAmendmentSupporterResponseFromJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfAmendmentSupporterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PaginatedResponseOfAmendmentSupporterResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfPaginatedResponseOfAmendmentSupporterResponseToJSON(json: any): ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse {
    return ApiResponseOfPaginatedResponseOfAmendmentSupporterResponseToJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfAmendmentSupporterResponseToJSONTyped(value?: ApiResponseOfPaginatedResponseOfAmendmentSupporterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaginatedResponseOfAmendmentSupporterResponseToJSON(value['data']),
    };
}

