/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfUserGroupListItemResponse } from './PaginatedResponseOfUserGroupListItemResponse';
import {
    PaginatedResponseOfUserGroupListItemResponseFromJSON,
    PaginatedResponseOfUserGroupListItemResponseFromJSONTyped,
    PaginatedResponseOfUserGroupListItemResponseToJSON,
    PaginatedResponseOfUserGroupListItemResponseToJSONTyped,
} from './PaginatedResponseOfUserGroupListItemResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfPaginatedResponseOfUserGroupListItemResponse
 */
export interface ApiResponseOfPaginatedResponseOfUserGroupListItemResponse {
    /**
     * 
     * @type {PaginatedResponseOfUserGroupListItemResponse}
     * @memberof ApiResponseOfPaginatedResponseOfUserGroupListItemResponse
     */
    data?: PaginatedResponseOfUserGroupListItemResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfPaginatedResponseOfUserGroupListItemResponse interface.
 */
export function instanceOfApiResponseOfPaginatedResponseOfUserGroupListItemResponse(value: object): value is ApiResponseOfPaginatedResponseOfUserGroupListItemResponse {
    return true;
}

export function ApiResponseOfPaginatedResponseOfUserGroupListItemResponseFromJSON(json: any): ApiResponseOfPaginatedResponseOfUserGroupListItemResponse {
    return ApiResponseOfPaginatedResponseOfUserGroupListItemResponseFromJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfUserGroupListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfPaginatedResponseOfUserGroupListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PaginatedResponseOfUserGroupListItemResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfPaginatedResponseOfUserGroupListItemResponseToJSON(json: any): ApiResponseOfPaginatedResponseOfUserGroupListItemResponse {
    return ApiResponseOfPaginatedResponseOfUserGroupListItemResponseToJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfUserGroupListItemResponseToJSONTyped(value?: ApiResponseOfPaginatedResponseOfUserGroupListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaginatedResponseOfUserGroupListItemResponseToJSON(value['data']),
    };
}

