/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocietiesFeedViewModel } from './SocietiesFeedViewModel';
import {
    SocietiesFeedViewModelFromJSON,
    SocietiesFeedViewModelFromJSONTyped,
    SocietiesFeedViewModelToJSON,
    SocietiesFeedViewModelToJSONTyped,
} from './SocietiesFeedViewModel';

/**
 * 
 * @export
 * @interface ApiResponseOfSocietiesFeedViewModel
 */
export interface ApiResponseOfSocietiesFeedViewModel {
    /**
     * 
     * @type {SocietiesFeedViewModel}
     * @memberof ApiResponseOfSocietiesFeedViewModel
     */
    data?: SocietiesFeedViewModel | null;
}

/**
 * Check if a given object implements the ApiResponseOfSocietiesFeedViewModel interface.
 */
export function instanceOfApiResponseOfSocietiesFeedViewModel(value: object): value is ApiResponseOfSocietiesFeedViewModel {
    return true;
}

export function ApiResponseOfSocietiesFeedViewModelFromJSON(json: any): ApiResponseOfSocietiesFeedViewModel {
    return ApiResponseOfSocietiesFeedViewModelFromJSONTyped(json, false);
}

export function ApiResponseOfSocietiesFeedViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfSocietiesFeedViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : SocietiesFeedViewModelFromJSON(json['data']),
    };
}

export function ApiResponseOfSocietiesFeedViewModelToJSON(json: any): ApiResponseOfSocietiesFeedViewModel {
    return ApiResponseOfSocietiesFeedViewModelToJSONTyped(json, false);
}

export function ApiResponseOfSocietiesFeedViewModelToJSONTyped(value?: ApiResponseOfSocietiesFeedViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SocietiesFeedViewModelToJSON(value['data']),
    };
}

