/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfAmendmentOpponentResponse } from './PaginatedResponseOfAmendmentOpponentResponse';
import {
    PaginatedResponseOfAmendmentOpponentResponseFromJSON,
    PaginatedResponseOfAmendmentOpponentResponseFromJSONTyped,
    PaginatedResponseOfAmendmentOpponentResponseToJSON,
    PaginatedResponseOfAmendmentOpponentResponseToJSONTyped,
} from './PaginatedResponseOfAmendmentOpponentResponse';

/**
 * 
 * @export
 * @interface ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse
 */
export interface ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse {
    /**
     * 
     * @type {PaginatedResponseOfAmendmentOpponentResponse}
     * @memberof ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse
     */
    data?: PaginatedResponseOfAmendmentOpponentResponse | null;
}

/**
 * Check if a given object implements the ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse interface.
 */
export function instanceOfApiResponseOfPaginatedResponseOfAmendmentOpponentResponse(value: object): value is ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse {
    return true;
}

export function ApiResponseOfPaginatedResponseOfAmendmentOpponentResponseFromJSON(json: any): ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse {
    return ApiResponseOfPaginatedResponseOfAmendmentOpponentResponseFromJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfAmendmentOpponentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PaginatedResponseOfAmendmentOpponentResponseFromJSON(json['data']),
    };
}

export function ApiResponseOfPaginatedResponseOfAmendmentOpponentResponseToJSON(json: any): ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse {
    return ApiResponseOfPaginatedResponseOfAmendmentOpponentResponseToJSONTyped(json, false);
}

export function ApiResponseOfPaginatedResponseOfAmendmentOpponentResponseToJSONTyped(value?: ApiResponseOfPaginatedResponseOfAmendmentOpponentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaginatedResponseOfAmendmentOpponentResponseToJSON(value['data']),
    };
}

