/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an attachment associated with a document, including its identifier and an optional caption.
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * The unique identifier of the document associated with the attachment. This value cannot be null.
     * @type {string}
     * @memberof Attachment
     */
    documentId?: string;
    /**
     * An optional caption describing the attachment. This value can be null.
     * @type {string}
     * @memberof Attachment
     */
    caption?: string | null;
}

/**
 * Check if a given object implements the Attachment interface.
 */
export function instanceOfAttachment(value: object): value is Attachment {
    return true;
}

export function AttachmentFromJSON(json: any): Attachment {
    return AttachmentFromJSONTyped(json, false);
}

export function AttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attachment {
    if (json == null) {
        return json;
    }
    return {
        
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'caption': json['caption'] == null ? undefined : json['caption'],
    };
}

export function AttachmentToJSON(json: any): Attachment {
    return AttachmentToJSONTyped(json, false);
}

export function AttachmentToJSONTyped(value?: Attachment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documentId': value['documentId'],
        'caption': value['caption'],
    };
}

