/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * View model for signal attachment details including pre-built URLs for display.
 * @export
 * @interface AttachmentDetailViewModel
 */
export interface AttachmentDetailViewModel {
    /**
     * The unique identifier of the document in the document service.
     * @type {string}
     * @memberof AttachmentDetailViewModel
     */
    documentId?: string;
    /**
     * Optional caption for the attachment.
     * @type {string}
     * @memberof AttachmentDetailViewModel
     */
    caption?: string | null;
    /**
     * The URL to the thumbnail version of the attachment.
     * @type {string}
     * @memberof AttachmentDetailViewModel
     */
    thumbnailUrl?: string;
    /**
     * The URL to the display-sized version of the attachment.
     * @type {string}
     * @memberof AttachmentDetailViewModel
     */
    displayUrl?: string;
}

/**
 * Check if a given object implements the AttachmentDetailViewModel interface.
 */
export function instanceOfAttachmentDetailViewModel(value: object): value is AttachmentDetailViewModel {
    return true;
}

export function AttachmentDetailViewModelFromJSON(json: any): AttachmentDetailViewModel {
    return AttachmentDetailViewModelFromJSONTyped(json, false);
}

export function AttachmentDetailViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentDetailViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'caption': json['caption'] == null ? undefined : json['caption'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'displayUrl': json['displayUrl'] == null ? undefined : json['displayUrl'],
    };
}

export function AttachmentDetailViewModelToJSON(json: any): AttachmentDetailViewModel {
    return AttachmentDetailViewModelToJSONTyped(json, false);
}

export function AttachmentDetailViewModelToJSONTyped(value?: AttachmentDetailViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documentId': value['documentId'],
        'caption': value['caption'],
        'thumbnailUrl': value['thumbnailUrl'],
        'displayUrl': value['displayUrl'],
    };
}

