/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Capture signal request model.
 * @export
 * @interface CaptureSignalRequest
 */
export interface CaptureSignalRequest {
    /**
     * The title of the signal.
     * @type {string}
     * @memberof CaptureSignalRequest
     */
    title?: string;
    /**
     * The description of the signal.
     * @type {string}
     * @memberof CaptureSignalRequest
     */
    description?: string;
    /**
     * The tags for the signal.
     * @type {Array<string>}
     * @memberof CaptureSignalRequest
     */
    tags?: Array<string>;
    /**
     * The document IDs of attachments to associate with the signal.
     * @type {Array<string>}
     * @memberof CaptureSignalRequest
     */
    attachmentIds?: Array<string>;
    /**
     * Optional latitude coordinate of the signal's location.
     * @type {number}
     * @memberof CaptureSignalRequest
     */
    latitude?: number | null;
    /**
     * Optional longitude coordinate of the signal's location.
     * @type {number}
     * @memberof CaptureSignalRequest
     */
    longitude?: number | null;
}

/**
 * Check if a given object implements the CaptureSignalRequest interface.
 */
export function instanceOfCaptureSignalRequest(value: object): value is CaptureSignalRequest {
    return true;
}

export function CaptureSignalRequestFromJSON(json: any): CaptureSignalRequest {
    return CaptureSignalRequestFromJSONTyped(json, false);
}

export function CaptureSignalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptureSignalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'attachmentIds': json['attachmentIds'] == null ? undefined : json['attachmentIds'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function CaptureSignalRequestToJSON(json: any): CaptureSignalRequest {
    return CaptureSignalRequestToJSONTyped(json, false);
}

export function CaptureSignalRequestToJSONTyped(value?: CaptureSignalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'tags': value['tags'],
        'attachmentIds': value['attachmentIds'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

