/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating a new action opportunity.
 * @export
 * @interface CreateActionOpportunityRequest
 */
export interface CreateActionOpportunityRequest {
    /**
     * The title of the action opportunity.
     * @type {string}
     * @memberof CreateActionOpportunityRequest
     */
    title?: string;
    /**
     * The description of the action opportunity.
     * @type {string}
     * @memberof CreateActionOpportunityRequest
     */
    description?: string;
    /**
     * The ID of the parent idea that spawned this action opportunity.
     * @type {string}
     * @memberof CreateActionOpportunityRequest
     */
    parentIdeaId?: string;
}

/**
 * Check if a given object implements the CreateActionOpportunityRequest interface.
 */
export function instanceOfCreateActionOpportunityRequest(value: object): value is CreateActionOpportunityRequest {
    return true;
}

export function CreateActionOpportunityRequestFromJSON(json: any): CreateActionOpportunityRequest {
    return CreateActionOpportunityRequestFromJSONTyped(json, false);
}

export function CreateActionOpportunityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateActionOpportunityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'parentIdeaId': json['parentIdeaId'] == null ? undefined : json['parentIdeaId'],
    };
}

export function CreateActionOpportunityRequestToJSON(json: any): CreateActionOpportunityRequest {
    return CreateActionOpportunityRequestToJSONTyped(json, false);
}

export function CreateActionOpportunityRequestToJSONTyped(value?: CreateActionOpportunityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'parentIdeaId': value['parentIdeaId'],
    };
}

