/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for creating an invite link.
 * @export
 * @interface CreateTrustInviteLinkRequest
 */
export interface CreateTrustInviteLinkRequest {
    /**
     * An optional private note visible only to the creator.
     * @type {string}
     * @memberof CreateTrustInviteLinkRequest
     */
    note?: string | null;
}

/**
 * Check if a given object implements the CreateTrustInviteLinkRequest interface.
 */
export function instanceOfCreateTrustInviteLinkRequest(value: object): value is CreateTrustInviteLinkRequest {
    return true;
}

export function CreateTrustInviteLinkRequestFromJSON(json: any): CreateTrustInviteLinkRequest {
    return CreateTrustInviteLinkRequestFromJSONTyped(json, false);
}

export function CreateTrustInviteLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTrustInviteLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CreateTrustInviteLinkRequestToJSON(json: any): CreateTrustInviteLinkRequest {
    return CreateTrustInviteLinkRequestToJSONTyped(json, false);
}

export function CreateTrustInviteLinkRequestToJSONTyped(value?: CreateTrustInviteLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
    };
}

