/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostViewModel } from './PostViewModel';
import {
    PostViewModelFromJSON,
    PostViewModelFromJSONTyped,
    PostViewModelToJSON,
    PostViewModelToJSONTyped,
} from './PostViewModel';

/**
 * Cursor-based paginated response wrapper for API endpoints.
 * Provides stable pagination using opaque cursors instead of offset-based pagination.
 * @export
 * @interface CursorPaginatedResponseOfPostViewModel
 */
export interface CursorPaginatedResponseOfPostViewModel {
    /**
     * The items for the current page.
     * @type {Array<PostViewModel>}
     * @memberof CursorPaginatedResponseOfPostViewModel
     */
    items?: Array<PostViewModel>;
    /**
     * Opaque cursor for retrieving the next page of results.
     * Null if no more pages are available.
     * @type {string}
     * @memberof CursorPaginatedResponseOfPostViewModel
     */
    nextCursor?: string | null;
    /**
     * Opaque cursor for retrieving the previous page of results.
     * Null if this is the first page.
     * @type {string}
     * @memberof CursorPaginatedResponseOfPostViewModel
     */
    previousCursor?: string | null;
    /**
     * Indicates whether there is a next page of results.
     * @type {boolean}
     * @memberof CursorPaginatedResponseOfPostViewModel
     */
    hasNextPage?: boolean;
    /**
     * Indicates whether there is a previous page of results.
     * @type {boolean}
     * @memberof CursorPaginatedResponseOfPostViewModel
     */
    hasPreviousPage?: boolean;
    /**
     * The number of items requested for this page.
     * @type {number}
     * @memberof CursorPaginatedResponseOfPostViewModel
     */
    pageSize?: number;
    /**
     * The request ID for tracking.
     * @type {string}
     * @memberof CursorPaginatedResponseOfPostViewModel
     */
    requestId?: string | null;
    /**
     * The timestamp when the response was generated.
     * @type {Date}
     * @memberof CursorPaginatedResponseOfPostViewModel
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the CursorPaginatedResponseOfPostViewModel interface.
 */
export function instanceOfCursorPaginatedResponseOfPostViewModel(value: object): value is CursorPaginatedResponseOfPostViewModel {
    return true;
}

export function CursorPaginatedResponseOfPostViewModelFromJSON(json: any): CursorPaginatedResponseOfPostViewModel {
    return CursorPaginatedResponseOfPostViewModelFromJSONTyped(json, false);
}

export function CursorPaginatedResponseOfPostViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPaginatedResponseOfPostViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(PostViewModelFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'previousCursor': json['previousCursor'] == null ? undefined : json['previousCursor'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function CursorPaginatedResponseOfPostViewModelToJSON(json: any): CursorPaginatedResponseOfPostViewModel {
    return CursorPaginatedResponseOfPostViewModelToJSONTyped(json, false);
}

export function CursorPaginatedResponseOfPostViewModelToJSONTyped(value?: CursorPaginatedResponseOfPostViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(PostViewModelToJSON)),
        'nextCursor': value['nextCursor'],
        'previousCursor': value['previousCursor'],
        'hasNextPage': value['hasNextPage'],
        'hasPreviousPage': value['hasPreviousPage'],
        'pageSize': value['pageSize'],
        'requestId': value['requestId'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

