/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for deamplifying a signal.
 * @export
 * @interface DeamplifySignalResponse
 */
export interface DeamplifySignalResponse {
    /**
     * 
     * @type {number}
     * @memberof DeamplifySignalResponse
     */
    newAmplifyCount?: number;
}

/**
 * Check if a given object implements the DeamplifySignalResponse interface.
 */
export function instanceOfDeamplifySignalResponse(value: object): value is DeamplifySignalResponse {
    return true;
}

export function DeamplifySignalResponseFromJSON(json: any): DeamplifySignalResponse {
    return DeamplifySignalResponseFromJSONTyped(json, false);
}

export function DeamplifySignalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeamplifySignalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'newAmplifyCount': json['newAmplifyCount'] == null ? undefined : json['newAmplifyCount'],
    };
}

export function DeamplifySignalResponseToJSON(json: any): DeamplifySignalResponse {
    return DeamplifySignalResponseToJSONTyped(json, false);
}

export function DeamplifySignalResponseToJSONTyped(value?: DeamplifySignalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newAmplifyCount': value['newAmplifyCount'],
    };
}

