/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to declare a society as affected by a commons.
 * @export
 * @interface DeclareSocietyAffectedByCommonsRequest
 */
export interface DeclareSocietyAffectedByCommonsRequest {
    /**
     * The ID of the commons this society is affected by.
     * @type {string}
     * @memberof DeclareSocietyAffectedByCommonsRequest
     */
    commonsId?: string;
}

/**
 * Check if a given object implements the DeclareSocietyAffectedByCommonsRequest interface.
 */
export function instanceOfDeclareSocietyAffectedByCommonsRequest(value: object): value is DeclareSocietyAffectedByCommonsRequest {
    return true;
}

export function DeclareSocietyAffectedByCommonsRequestFromJSON(json: any): DeclareSocietyAffectedByCommonsRequest {
    return DeclareSocietyAffectedByCommonsRequestFromJSONTyped(json, false);
}

export function DeclareSocietyAffectedByCommonsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeclareSocietyAffectedByCommonsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'commonsId': json['commonsId'] == null ? undefined : json['commonsId'],
    };
}

export function DeclareSocietyAffectedByCommonsRequestToJSON(json: any): DeclareSocietyAffectedByCommonsRequest {
    return DeclareSocietyAffectedByCommonsRequestToJSONTyped(json, false);
}

export function DeclareSocietyAffectedByCommonsRequestToJSONTyped(value?: DeclareSocietyAffectedByCommonsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commonsId': value['commonsId'],
    };
}

