/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a cluster of signals forming an emerging pattern.
 * @export
 * @interface EmergingPatternResponse
 */
export interface EmergingPatternResponse {
    /**
     * The HDBSCAN cluster label.
     * @type {number}
     * @memberof EmergingPatternResponse
     */
    clusterLabel?: number;
    /**
     * IDs of the signals assigned to this cluster.
     * @type {Array<string>}
     * @memberof EmergingPatternResponse
     */
    signalIds?: Array<string>;
    /**
     * Number of signals in this cluster.
     * @type {number}
     * @memberof EmergingPatternResponse
     */
    signalCount?: number;
    /**
     * When this pattern was last updated by a clustering run.
     * @type {Date}
     * @memberof EmergingPatternResponse
     */
    lastUpdatedAt?: Date;
    /**
     * Top TF-IDF keywords for this cluster.
     * @type {Array<string>}
     * @memberof EmergingPatternResponse
     */
    keywords?: Array<string>;
}

/**
 * Check if a given object implements the EmergingPatternResponse interface.
 */
export function instanceOfEmergingPatternResponse(value: object): value is EmergingPatternResponse {
    return true;
}

export function EmergingPatternResponseFromJSON(json: any): EmergingPatternResponse {
    return EmergingPatternResponseFromJSONTyped(json, false);
}

export function EmergingPatternResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmergingPatternResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'clusterLabel': json['clusterLabel'] == null ? undefined : json['clusterLabel'],
        'signalIds': json['signalIds'] == null ? undefined : json['signalIds'],
        'signalCount': json['signalCount'] == null ? undefined : json['signalCount'],
        'lastUpdatedAt': json['lastUpdatedAt'] == null ? undefined : (new Date(json['lastUpdatedAt'])),
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
    };
}

export function EmergingPatternResponseToJSON(json: any): EmergingPatternResponse {
    return EmergingPatternResponseToJSONTyped(json, false);
}

export function EmergingPatternResponseToJSONTyped(value?: EmergingPatternResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clusterLabel': value['clusterLabel'],
        'signalIds': value['signalIds'],
        'signalCount': value['signalCount'],
        'lastUpdatedAt': value['lastUpdatedAt'] == null ? undefined : ((value['lastUpdatedAt']).toISOString()),
        'keywords': value['keywords'],
    };
}

