/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents the filter state that was applied to generate this response.
 * @export
 * @interface FilterStateViewModel
 */
export interface FilterStateViewModel {
    /**
     * The time range filter that was applied.
     * @type {string}
     * @memberof FilterStateViewModel
     */
    timeRange?: string;
    /**
     * The amplification level filter that was applied.
     * @type {string}
     * @memberof FilterStateViewModel
     */
    amplificationLevel?: string;
    /**
     * The search term that was applied.
     * @type {string}
     * @memberof FilterStateViewModel
     */
    searchTerm?: string | null;
    /**
     * The tags that were filtered by.
     * @type {Array<string>}
     * @memberof FilterStateViewModel
     */
    tags?: Array<string>;
    /**
     * The sort option that was applied.
     * @type {string}
     * @memberof FilterStateViewModel
     */
    sortBy?: string;
}

/**
 * Check if a given object implements the FilterStateViewModel interface.
 */
export function instanceOfFilterStateViewModel(value: object): value is FilterStateViewModel {
    return true;
}

export function FilterStateViewModelFromJSON(json: any): FilterStateViewModel {
    return FilterStateViewModelFromJSONTyped(json, false);
}

export function FilterStateViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterStateViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'timeRange': json['timeRange'] == null ? undefined : json['timeRange'],
        'amplificationLevel': json['amplificationLevel'] == null ? undefined : json['amplificationLevel'],
        'searchTerm': json['searchTerm'] == null ? undefined : json['searchTerm'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'sortBy': json['sortBy'] == null ? undefined : json['sortBy'],
    };
}

export function FilterStateViewModelToJSON(json: any): FilterStateViewModel {
    return FilterStateViewModelToJSONTyped(json, false);
}

export function FilterStateViewModelToJSONTyped(value?: FilterStateViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeRange': value['timeRange'],
        'amplificationLevel': value['amplificationLevel'],
        'searchTerm': value['searchTerm'],
        'tags': value['tags'],
        'sortBy': value['sortBy'],
    };
}

