/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroupCharterDto } from './UserGroupCharterDto';
import {
    UserGroupCharterDtoFromJSON,
    UserGroupCharterDtoFromJSONTyped,
    UserGroupCharterDtoToJSON,
    UserGroupCharterDtoToJSONTyped,
} from './UserGroupCharterDto';

/**
 * Request model for forming a new user group.
 * @export
 * @interface FormUserGroupRequest
 */
export interface FormUserGroupRequest {
    /**
     * The ID of the commons this user group will govern.
     * @type {string}
     * @memberof FormUserGroupRequest
     */
    commonsId?: string;
    /**
     * The name of the user group.
     * @type {string}
     * @memberof FormUserGroupRequest
     */
    name?: string;
    /**
     * The philosophy of the user group.
     * @type {string}
     * @memberof FormUserGroupRequest
     */
    philosophy?: string;
    /**
     * 
     * @type {UserGroupCharterDto}
     * @memberof FormUserGroupRequest
     */
    charter?: UserGroupCharterDto;
}

/**
 * Check if a given object implements the FormUserGroupRequest interface.
 */
export function instanceOfFormUserGroupRequest(value: object): value is FormUserGroupRequest {
    return true;
}

export function FormUserGroupRequestFromJSON(json: any): FormUserGroupRequest {
    return FormUserGroupRequestFromJSONTyped(json, false);
}

export function FormUserGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormUserGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'commonsId': json['commonsId'] == null ? undefined : json['commonsId'],
        'name': json['name'] == null ? undefined : json['name'],
        'philosophy': json['philosophy'] == null ? undefined : json['philosophy'],
        'charter': json['charter'] == null ? undefined : UserGroupCharterDtoFromJSON(json['charter']),
    };
}

export function FormUserGroupRequestToJSON(json: any): FormUserGroupRequest {
    return FormUserGroupRequestToJSONTyped(json, false);
}

export function FormUserGroupRequestToJSONTyped(value?: FormUserGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commonsId': value['commonsId'],
        'name': value['name'],
        'philosophy': value['philosophy'],
        'charter': UserGroupCharterDtoToJSON(value['charter']),
    };
}

