/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfo } from './UserInfo';
import {
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
    UserInfoToJSONTyped,
} from './UserInfo';

/**
 * Response returned when querying the current authenticated user.
 * @export
 * @interface GetCurrentUserResponse
 */
export interface GetCurrentUserResponse {
    /**
     * Gets or sets a value indicating whether the operation was successful.
     * @type {boolean}
     * @memberof GetCurrentUserResponse
     */
    success?: boolean;
    /**
     * Gets or sets an error message when Success is false; otherwise null.
     * @type {string}
     * @memberof GetCurrentUserResponse
     */
    error?: string | null;
    /**
     * 
     * @type {UserInfo}
     * @memberof GetCurrentUserResponse
     */
    user?: UserInfo | null;
}

/**
 * Check if a given object implements the GetCurrentUserResponse interface.
 */
export function instanceOfGetCurrentUserResponse(value: object): value is GetCurrentUserResponse {
    return true;
}

export function GetCurrentUserResponseFromJSON(json: any): GetCurrentUserResponse {
    return GetCurrentUserResponseFromJSONTyped(json, false);
}

export function GetCurrentUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : json['error'],
        'user': json['user'] == null ? undefined : UserInfoFromJSON(json['user']),
    };
}

export function GetCurrentUserResponseToJSON(json: any): GetCurrentUserResponse {
    return GetCurrentUserResponseToJSONTyped(json, false);
}

export function GetCurrentUserResponseToJSONTyped(value?: GetCurrentUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'user': UserInfoToJSON(value['user']),
    };
}

