/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for a list item of an idea.
 * @export
 * @interface IdeaListItemResponse
 */
export interface IdeaListItemResponse {
    /**
     * The unique identifier of the idea.
     * @type {string}
     * @memberof IdeaListItemResponse
     */
    id?: string;
    /**
     * The title of the idea.
     * @type {string}
     * @memberof IdeaListItemResponse
     */
    title?: string;
    /**
     * The body content describing the idea.
     * @type {string}
     * @memberof IdeaListItemResponse
     */
    description?: string;
    /**
     * The timestamp when the idea was originally created.
     * @type {Date}
     * @memberof IdeaListItemResponse
     */
    createdAt?: Date;
    /**
     * The timestamp when the idea was last modified or updated.
     * @type {Date}
     * @memberof IdeaListItemResponse
     */
    lastUpdatedAt?: Date;
    /**
     * The current status of the idea (e.g., "Draft", "Published").
     * @type {string}
     * @memberof IdeaListItemResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the IdeaListItemResponse interface.
 */
export function instanceOfIdeaListItemResponse(value: object): value is IdeaListItemResponse {
    return true;
}

export function IdeaListItemResponseFromJSON(json: any): IdeaListItemResponse {
    return IdeaListItemResponseFromJSONTyped(json, false);
}

export function IdeaListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastUpdatedAt': json['lastUpdatedAt'] == null ? undefined : (new Date(json['lastUpdatedAt'])),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function IdeaListItemResponseToJSON(json: any): IdeaListItemResponse {
    return IdeaListItemResponseToJSONTyped(json, false);
}

export function IdeaListItemResponseToJSONTyped(value?: IdeaListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'lastUpdatedAt': value['lastUpdatedAt'] == null ? undefined : ((value['lastUpdatedAt']).toISOString()),
        'status': value['status'],
    };
}

