/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfIdeaListItemResponse } from './PaginatedResponseOfIdeaListItemResponse';
import {
    PaginatedResponseOfIdeaListItemResponseFromJSON,
    PaginatedResponseOfIdeaListItemResponseFromJSONTyped,
    PaginatedResponseOfIdeaListItemResponseToJSON,
    PaginatedResponseOfIdeaListItemResponseToJSONTyped,
} from './PaginatedResponseOfIdeaListItemResponse';

/**
 * View model for the ideas feed page.
 * @export
 * @interface IdeasFeedViewModel
 */
export interface IdeasFeedViewModel {
    /**
     * 
     * @type {PaginatedResponseOfIdeaListItemResponse}
     * @memberof IdeasFeedViewModel
     */
    ideas?: PaginatedResponseOfIdeaListItemResponse;
}

/**
 * Check if a given object implements the IdeasFeedViewModel interface.
 */
export function instanceOfIdeasFeedViewModel(value: object): value is IdeasFeedViewModel {
    return true;
}

export function IdeasFeedViewModelFromJSON(json: any): IdeasFeedViewModel {
    return IdeasFeedViewModelFromJSONTyped(json, false);
}

export function IdeasFeedViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeasFeedViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'ideas': json['ideas'] == null ? undefined : PaginatedResponseOfIdeaListItemResponseFromJSON(json['ideas']),
    };
}

export function IdeasFeedViewModelToJSON(json: any): IdeasFeedViewModel {
    return IdeasFeedViewModelToJSONTyped(json, false);
}

export function IdeasFeedViewModelToJSONTyped(value?: IdeasFeedViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ideas': PaginatedResponseOfIdeaListItemResponseToJSON(value['ideas']),
    };
}

