/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for idea information.
 * @export
 * @interface IdeaResponse
 */
export interface IdeaResponse {
    /**
     * The ID of the idea.
     * @type {string}
     * @memberof IdeaResponse
     */
    id?: string;
    /**
     * The title of the idea.
     * @type {string}
     * @memberof IdeaResponse
     */
    title?: string;
    /**
     * The description of the idea.
     * @type {string}
     * @memberof IdeaResponse
     */
    description?: string;
    /**
     * The pseudonym of the author who created the idea.
     * @type {string}
     * @memberof IdeaResponse
     */
    authorPseudonym?: string;
    /**
     * When the idea was created.
     * @type {Date}
     * @memberof IdeaResponse
     */
    createdAt?: Date;
    /**
     * When the idea was last updated.
     * @type {Date}
     * @memberof IdeaResponse
     */
    lastUpdatedAt?: Date;
    /**
     * The status of the idea.
     * @type {string}
     * @memberof IdeaResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the IdeaResponse interface.
 */
export function instanceOfIdeaResponse(value: object): value is IdeaResponse {
    return true;
}

export function IdeaResponseFromJSON(json: any): IdeaResponse {
    return IdeaResponseFromJSONTyped(json, false);
}

export function IdeaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'authorPseudonym': json['authorPseudonym'] == null ? undefined : json['authorPseudonym'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastUpdatedAt': json['lastUpdatedAt'] == null ? undefined : (new Date(json['lastUpdatedAt'])),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function IdeaResponseToJSON(json: any): IdeaResponse {
    return IdeaResponseToJSONTyped(json, false);
}

export function IdeaResponseToJSONTyped(value?: IdeaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'authorPseudonym': value['authorPseudonym'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'lastUpdatedAt': value['lastUpdatedAt'] == null ? undefined : ((value['lastUpdatedAt']).toISOString()),
        'status': value['status'],
    };
}

