/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a source signal associated with an idea.
 * @export
 * @interface IdeaSourceSignal
 */
export interface IdeaSourceSignal {
    /**
     * The unique identifier of the source signal.
     * @type {string}
     * @memberof IdeaSourceSignal
     */
    id?: string;
    /**
     * The title of the source signal.
     * @type {string}
     * @memberof IdeaSourceSignal
     */
    title?: string;
}

/**
 * Check if a given object implements the IdeaSourceSignal interface.
 */
export function instanceOfIdeaSourceSignal(value: object): value is IdeaSourceSignal {
    return true;
}

export function IdeaSourceSignalFromJSON(json: any): IdeaSourceSignal {
    return IdeaSourceSignalFromJSONTyped(json, false);
}

export function IdeaSourceSignalFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaSourceSignal {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function IdeaSourceSignalToJSON(json: any): IdeaSourceSignal {
    return IdeaSourceSignalToJSONTyped(json, false);
}

export function IdeaSourceSignalToJSONTyped(value?: IdeaSourceSignal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

