/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for joining a society.
 * @export
 * @interface JoinSocietyRequest
 */
export interface JoinSocietyRequest {
    /**
     * The ID of the social contract the participant is agreeing to.
     * @type {string}
     * @memberof JoinSocietyRequest
     */
    socialContractId?: string;
    /**
     * The invite token from the invite link URL, if the participant arrived via an invite link. Stored for attribution.
     * @type {string}
     * @memberof JoinSocietyRequest
     */
    inviteToken?: string | null;
}

/**
 * Check if a given object implements the JoinSocietyRequest interface.
 */
export function instanceOfJoinSocietyRequest(value: object): value is JoinSocietyRequest {
    return true;
}

export function JoinSocietyRequestFromJSON(json: any): JoinSocietyRequest {
    return JoinSocietyRequestFromJSONTyped(json, false);
}

export function JoinSocietyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinSocietyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'socialContractId': json['socialContractId'] == null ? undefined : json['socialContractId'],
        'inviteToken': json['inviteToken'] == null ? undefined : json['inviteToken'],
    };
}

export function JoinSocietyRequestToJSON(json: any): JoinSocietyRequest {
    return JoinSocietyRequestToJSONTyped(json, false);
}

export function JoinSocietyRequestToJSONTyped(value?: JoinSocietyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'socialContractId': value['socialContractId'],
        'inviteToken': value['inviteToken'],
    };
}

