/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for opposing an amendment.
 * @export
 * @interface OpposeAmendmentRequest
 */
export interface OpposeAmendmentRequest {
    /**
     * The reason provided by the participant for opposing the amendment.
     * @type {string}
     * @memberof OpposeAmendmentRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the OpposeAmendmentRequest interface.
 */
export function instanceOfOpposeAmendmentRequest(value: object): value is OpposeAmendmentRequest {
    return true;
}

export function OpposeAmendmentRequestFromJSON(json: any): OpposeAmendmentRequest {
    return OpposeAmendmentRequestFromJSONTyped(json, false);
}

export function OpposeAmendmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpposeAmendmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function OpposeAmendmentRequestToJSON(json: any): OpposeAmendmentRequest {
    return OpposeAmendmentRequestToJSONTyped(json, false);
}

export function OpposeAmendmentRequestToJSONTyped(value?: OpposeAmendmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

