/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroupMemberResponse } from './UserGroupMemberResponse';
import {
    UserGroupMemberResponseFromJSON,
    UserGroupMemberResponseFromJSONTyped,
    UserGroupMemberResponseToJSON,
    UserGroupMemberResponseToJSONTyped,
} from './UserGroupMemberResponse';

/**
 * Generic paginated response wrapper for API endpoints.
 * @export
 * @interface PaginatedResponseOfUserGroupMemberResponse
 */
export interface PaginatedResponseOfUserGroupMemberResponse {
    /**
     * The items for the current page.
     * @type {Array<UserGroupMemberResponse>}
     * @memberof PaginatedResponseOfUserGroupMemberResponse
     */
    items?: Array<UserGroupMemberResponse>;
    /**
     * Indicates whether there is a next page of results.
     * @type {boolean}
     * @memberof PaginatedResponseOfUserGroupMemberResponse
     */
    hasNextPage?: boolean;
    /**
     * The current page number (1-based).
     * @type {number}
     * @memberof PaginatedResponseOfUserGroupMemberResponse
     */
    pageNumber?: number;
    /**
     * The number of items per page.
     * @type {number}
     * @memberof PaginatedResponseOfUserGroupMemberResponse
     */
    pageSize?: number;
    /**
     * The total number of items across all pages.
     * @type {number}
     * @memberof PaginatedResponseOfUserGroupMemberResponse
     */
    totalCount?: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof PaginatedResponseOfUserGroupMemberResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedResponseOfUserGroupMemberResponse interface.
 */
export function instanceOfPaginatedResponseOfUserGroupMemberResponse(value: object): value is PaginatedResponseOfUserGroupMemberResponse {
    return true;
}

export function PaginatedResponseOfUserGroupMemberResponseFromJSON(json: any): PaginatedResponseOfUserGroupMemberResponse {
    return PaginatedResponseOfUserGroupMemberResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfUserGroupMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfUserGroupMemberResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(UserGroupMemberResponseFromJSON)),
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedResponseOfUserGroupMemberResponseToJSON(json: any): PaginatedResponseOfUserGroupMemberResponse {
    return PaginatedResponseOfUserGroupMemberResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfUserGroupMemberResponseToJSONTyped(value?: PaginatedResponseOfUserGroupMemberResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(UserGroupMemberResponseToJSON)),
        'hasNextPage': value['hasNextPage'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
    };
}

