/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AmendmentOpponentResponse } from './AmendmentOpponentResponse';
import {
    AmendmentOpponentResponseFromJSON,
    AmendmentOpponentResponseFromJSONTyped,
    AmendmentOpponentResponseToJSON,
    AmendmentOpponentResponseToJSONTyped,
} from './AmendmentOpponentResponse';

/**
 * Generic paginated response wrapper for API endpoints.
 * @export
 * @interface PaginatedResponseOfAmendmentOpponentResponse
 */
export interface PaginatedResponseOfAmendmentOpponentResponse {
    /**
     * The items for the current page.
     * @type {Array<AmendmentOpponentResponse>}
     * @memberof PaginatedResponseOfAmendmentOpponentResponse
     */
    items?: Array<AmendmentOpponentResponse>;
    /**
     * Indicates whether there is a next page of results.
     * @type {boolean}
     * @memberof PaginatedResponseOfAmendmentOpponentResponse
     */
    hasNextPage?: boolean;
    /**
     * The current page number (1-based).
     * @type {number}
     * @memberof PaginatedResponseOfAmendmentOpponentResponse
     */
    pageNumber?: number;
    /**
     * The number of items per page.
     * @type {number}
     * @memberof PaginatedResponseOfAmendmentOpponentResponse
     */
    pageSize?: number;
    /**
     * The total number of items across all pages.
     * @type {number}
     * @memberof PaginatedResponseOfAmendmentOpponentResponse
     */
    totalCount?: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof PaginatedResponseOfAmendmentOpponentResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedResponseOfAmendmentOpponentResponse interface.
 */
export function instanceOfPaginatedResponseOfAmendmentOpponentResponse(value: object): value is PaginatedResponseOfAmendmentOpponentResponse {
    return true;
}

export function PaginatedResponseOfAmendmentOpponentResponseFromJSON(json: any): PaginatedResponseOfAmendmentOpponentResponse {
    return PaginatedResponseOfAmendmentOpponentResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfAmendmentOpponentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfAmendmentOpponentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(AmendmentOpponentResponseFromJSON)),
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedResponseOfAmendmentOpponentResponseToJSON(json: any): PaginatedResponseOfAmendmentOpponentResponse {
    return PaginatedResponseOfAmendmentOpponentResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfAmendmentOpponentResponseToJSONTyped(value?: PaginatedResponseOfAmendmentOpponentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(AmendmentOpponentResponseToJSON)),
        'hasNextPage': value['hasNextPage'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
    };
}

