/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionOpportunityListResponse } from './ActionOpportunityListResponse';
import {
    ActionOpportunityListResponseFromJSON,
    ActionOpportunityListResponseFromJSONTyped,
    ActionOpportunityListResponseToJSON,
    ActionOpportunityListResponseToJSONTyped,
} from './ActionOpportunityListResponse';

/**
 * Generic paginated response wrapper for API endpoints.
 * @export
 * @interface PaginatedResponseOfActionOpportunityListResponse
 */
export interface PaginatedResponseOfActionOpportunityListResponse {
    /**
     * The items for the current page.
     * @type {Array<ActionOpportunityListResponse>}
     * @memberof PaginatedResponseOfActionOpportunityListResponse
     */
    items?: Array<ActionOpportunityListResponse>;
    /**
     * Indicates whether there is a next page of results.
     * @type {boolean}
     * @memberof PaginatedResponseOfActionOpportunityListResponse
     */
    hasNextPage?: boolean;
    /**
     * The current page number (1-based).
     * @type {number}
     * @memberof PaginatedResponseOfActionOpportunityListResponse
     */
    pageNumber?: number;
    /**
     * The number of items per page.
     * @type {number}
     * @memberof PaginatedResponseOfActionOpportunityListResponse
     */
    pageSize?: number;
    /**
     * The total number of items across all pages.
     * @type {number}
     * @memberof PaginatedResponseOfActionOpportunityListResponse
     */
    totalCount?: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof PaginatedResponseOfActionOpportunityListResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedResponseOfActionOpportunityListResponse interface.
 */
export function instanceOfPaginatedResponseOfActionOpportunityListResponse(value: object): value is PaginatedResponseOfActionOpportunityListResponse {
    return true;
}

export function PaginatedResponseOfActionOpportunityListResponseFromJSON(json: any): PaginatedResponseOfActionOpportunityListResponse {
    return PaginatedResponseOfActionOpportunityListResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfActionOpportunityListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfActionOpportunityListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ActionOpportunityListResponseFromJSON)),
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedResponseOfActionOpportunityListResponseToJSON(json: any): PaginatedResponseOfActionOpportunityListResponse {
    return PaginatedResponseOfActionOpportunityListResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfActionOpportunityListResponseToJSONTyped(value?: PaginatedResponseOfActionOpportunityListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ActionOpportunityListResponseToJSON)),
        'hasNextPage': value['hasNextPage'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
    };
}

