/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonsListItemResponse } from './CommonsListItemResponse';
import {
    CommonsListItemResponseFromJSON,
    CommonsListItemResponseFromJSONTyped,
    CommonsListItemResponseToJSON,
    CommonsListItemResponseToJSONTyped,
} from './CommonsListItemResponse';

/**
 * Generic paginated response wrapper for API endpoints.
 * @export
 * @interface PaginatedResponseOfCommonsListItemResponse
 */
export interface PaginatedResponseOfCommonsListItemResponse {
    /**
     * The items for the current page.
     * @type {Array<CommonsListItemResponse>}
     * @memberof PaginatedResponseOfCommonsListItemResponse
     */
    items?: Array<CommonsListItemResponse>;
    /**
     * Indicates whether there is a next page of results.
     * @type {boolean}
     * @memberof PaginatedResponseOfCommonsListItemResponse
     */
    hasNextPage?: boolean;
    /**
     * The current page number (1-based).
     * @type {number}
     * @memberof PaginatedResponseOfCommonsListItemResponse
     */
    pageNumber?: number;
    /**
     * The number of items per page.
     * @type {number}
     * @memberof PaginatedResponseOfCommonsListItemResponse
     */
    pageSize?: number;
    /**
     * The total number of items across all pages.
     * @type {number}
     * @memberof PaginatedResponseOfCommonsListItemResponse
     */
    totalCount?: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof PaginatedResponseOfCommonsListItemResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedResponseOfCommonsListItemResponse interface.
 */
export function instanceOfPaginatedResponseOfCommonsListItemResponse(value: object): value is PaginatedResponseOfCommonsListItemResponse {
    return true;
}

export function PaginatedResponseOfCommonsListItemResponseFromJSON(json: any): PaginatedResponseOfCommonsListItemResponse {
    return PaginatedResponseOfCommonsListItemResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfCommonsListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfCommonsListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CommonsListItemResponseFromJSON)),
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedResponseOfCommonsListItemResponseToJSON(json: any): PaginatedResponseOfCommonsListItemResponse {
    return PaginatedResponseOfCommonsListItemResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfCommonsListItemResponseToJSONTyped(value?: PaginatedResponseOfCommonsListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CommonsListItemResponseToJSON)),
        'hasNextPage': value['hasNextPage'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
    };
}

