/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectInquiryResponse } from './ProjectInquiryResponse';
import {
    ProjectInquiryResponseFromJSON,
    ProjectInquiryResponseFromJSONTyped,
    ProjectInquiryResponseToJSON,
    ProjectInquiryResponseToJSONTyped,
} from './ProjectInquiryResponse';

/**
 * Generic paginated response wrapper for API endpoints.
 * @export
 * @interface PaginatedResponseOfProjectInquiryResponse
 */
export interface PaginatedResponseOfProjectInquiryResponse {
    /**
     * The items for the current page.
     * @type {Array<ProjectInquiryResponse>}
     * @memberof PaginatedResponseOfProjectInquiryResponse
     */
    items?: Array<ProjectInquiryResponse>;
    /**
     * Indicates whether there is a next page of results.
     * @type {boolean}
     * @memberof PaginatedResponseOfProjectInquiryResponse
     */
    hasNextPage?: boolean;
    /**
     * The current page number (1-based).
     * @type {number}
     * @memberof PaginatedResponseOfProjectInquiryResponse
     */
    pageNumber?: number;
    /**
     * The number of items per page.
     * @type {number}
     * @memberof PaginatedResponseOfProjectInquiryResponse
     */
    pageSize?: number;
    /**
     * The total number of items across all pages.
     * @type {number}
     * @memberof PaginatedResponseOfProjectInquiryResponse
     */
    totalCount?: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof PaginatedResponseOfProjectInquiryResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedResponseOfProjectInquiryResponse interface.
 */
export function instanceOfPaginatedResponseOfProjectInquiryResponse(value: object): value is PaginatedResponseOfProjectInquiryResponse {
    return true;
}

export function PaginatedResponseOfProjectInquiryResponseFromJSON(json: any): PaginatedResponseOfProjectInquiryResponse {
    return PaginatedResponseOfProjectInquiryResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfProjectInquiryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfProjectInquiryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ProjectInquiryResponseFromJSON)),
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedResponseOfProjectInquiryResponseToJSON(json: any): PaginatedResponseOfProjectInquiryResponse {
    return PaginatedResponseOfProjectInquiryResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfProjectInquiryResponseToJSONTyped(value?: PaginatedResponseOfProjectInquiryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ProjectInquiryResponseToJSON)),
        'hasNextPage': value['hasNextPage'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
    };
}

