/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocietyListItemResponse } from './SocietyListItemResponse';
import {
    SocietyListItemResponseFromJSON,
    SocietyListItemResponseFromJSONTyped,
    SocietyListItemResponseToJSON,
    SocietyListItemResponseToJSONTyped,
} from './SocietyListItemResponse';

/**
 * Generic paginated response wrapper for API endpoints.
 * @export
 * @interface PaginatedResponseOfSocietyListItemResponse
 */
export interface PaginatedResponseOfSocietyListItemResponse {
    /**
     * The items for the current page.
     * @type {Array<SocietyListItemResponse>}
     * @memberof PaginatedResponseOfSocietyListItemResponse
     */
    items?: Array<SocietyListItemResponse>;
    /**
     * Indicates whether there is a next page of results.
     * @type {boolean}
     * @memberof PaginatedResponseOfSocietyListItemResponse
     */
    hasNextPage?: boolean;
    /**
     * The current page number (1-based).
     * @type {number}
     * @memberof PaginatedResponseOfSocietyListItemResponse
     */
    pageNumber?: number;
    /**
     * The number of items per page.
     * @type {number}
     * @memberof PaginatedResponseOfSocietyListItemResponse
     */
    pageSize?: number;
    /**
     * The total number of items across all pages.
     * @type {number}
     * @memberof PaginatedResponseOfSocietyListItemResponse
     */
    totalCount?: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof PaginatedResponseOfSocietyListItemResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedResponseOfSocietyListItemResponse interface.
 */
export function instanceOfPaginatedResponseOfSocietyListItemResponse(value: object): value is PaginatedResponseOfSocietyListItemResponse {
    return true;
}

export function PaginatedResponseOfSocietyListItemResponseFromJSON(json: any): PaginatedResponseOfSocietyListItemResponse {
    return PaginatedResponseOfSocietyListItemResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfSocietyListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfSocietyListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(SocietyListItemResponseFromJSON)),
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedResponseOfSocietyListItemResponseToJSON(json: any): PaginatedResponseOfSocietyListItemResponse {
    return PaginatedResponseOfSocietyListItemResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfSocietyListItemResponseToJSONTyped(value?: PaginatedResponseOfSocietyListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(SocietyListItemResponseToJSON)),
        'hasNextPage': value['hasNextPage'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
    };
}

