/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AmendmentSupporterResponse } from './AmendmentSupporterResponse';
import {
    AmendmentSupporterResponseFromJSON,
    AmendmentSupporterResponseFromJSONTyped,
    AmendmentSupporterResponseToJSON,
    AmendmentSupporterResponseToJSONTyped,
} from './AmendmentSupporterResponse';

/**
 * Generic paginated response wrapper for API endpoints.
 * @export
 * @interface PaginatedResponseOfAmendmentSupporterResponse
 */
export interface PaginatedResponseOfAmendmentSupporterResponse {
    /**
     * The items for the current page.
     * @type {Array<AmendmentSupporterResponse>}
     * @memberof PaginatedResponseOfAmendmentSupporterResponse
     */
    items?: Array<AmendmentSupporterResponse>;
    /**
     * Indicates whether there is a next page of results.
     * @type {boolean}
     * @memberof PaginatedResponseOfAmendmentSupporterResponse
     */
    hasNextPage?: boolean;
    /**
     * The current page number (1-based).
     * @type {number}
     * @memberof PaginatedResponseOfAmendmentSupporterResponse
     */
    pageNumber?: number;
    /**
     * The number of items per page.
     * @type {number}
     * @memberof PaginatedResponseOfAmendmentSupporterResponse
     */
    pageSize?: number;
    /**
     * The total number of items across all pages.
     * @type {number}
     * @memberof PaginatedResponseOfAmendmentSupporterResponse
     */
    totalCount?: number;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof PaginatedResponseOfAmendmentSupporterResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedResponseOfAmendmentSupporterResponse interface.
 */
export function instanceOfPaginatedResponseOfAmendmentSupporterResponse(value: object): value is PaginatedResponseOfAmendmentSupporterResponse {
    return true;
}

export function PaginatedResponseOfAmendmentSupporterResponseFromJSON(json: any): PaginatedResponseOfAmendmentSupporterResponse {
    return PaginatedResponseOfAmendmentSupporterResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOfAmendmentSupporterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfAmendmentSupporterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(AmendmentSupporterResponseFromJSON)),
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedResponseOfAmendmentSupporterResponseToJSON(json: any): PaginatedResponseOfAmendmentSupporterResponse {
    return PaginatedResponseOfAmendmentSupporterResponseToJSONTyped(json, false);
}

export function PaginatedResponseOfAmendmentSupporterResponseToJSONTyped(value?: PaginatedResponseOfAmendmentSupporterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(AmendmentSupporterResponseToJSON)),
        'hasNextPage': value['hasNextPage'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
    };
}

