/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Public profile information for a participant, resolved by pseudonym.
 * @export
 * @interface ParticipantProfileResponse
 */
export interface ParticipantProfileResponse {
    /**
     * The participant's internal stable identifier.
     * @type {string}
     * @memberof ParticipantProfileResponse
     */
    userId?: string;
    /**
     * The participant's globally unique pseudonym.
     * @type {string}
     * @memberof ParticipantProfileResponse
     */
    pseudonym?: string;
    /**
     * The UTC timestamp when the participant registered.
     * @type {Date}
     * @memberof ParticipantProfileResponse
     */
    joinedAt?: Date;
}

/**
 * Check if a given object implements the ParticipantProfileResponse interface.
 */
export function instanceOfParticipantProfileResponse(value: object): value is ParticipantProfileResponse {
    return true;
}

export function ParticipantProfileResponseFromJSON(json: any): ParticipantProfileResponse {
    return ParticipantProfileResponseFromJSONTyped(json, false);
}

export function ParticipantProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParticipantProfileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'pseudonym': json['pseudonym'] == null ? undefined : json['pseudonym'],
        'joinedAt': json['joinedAt'] == null ? undefined : (new Date(json['joinedAt'])),
    };
}

export function ParticipantProfileResponseToJSON(json: any): ParticipantProfileResponse {
    return ParticipantProfileResponseToJSONTyped(json, false);
}

export function ParticipantProfileResponseToJSONTyped(value?: ParticipantProfileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'pseudonym': value['pseudonym'],
        'joinedAt': value['joinedAt'] == null ? undefined : ((value['joinedAt']).toISOString()),
    };
}

