/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CursorPaginatedResponseOfPostViewModel } from './CursorPaginatedResponseOfPostViewModel';
import {
    CursorPaginatedResponseOfPostViewModelFromJSON,
    CursorPaginatedResponseOfPostViewModelFromJSONTyped,
    CursorPaginatedResponseOfPostViewModelToJSON,
    CursorPaginatedResponseOfPostViewModelToJSONTyped,
} from './CursorPaginatedResponseOfPostViewModel';

/**
 * Represents posts for a specific thread in the gateway with cursor-based pagination.
 * @export
 * @interface PostsViewModel
 */
export interface PostsViewModel {
    /**
     * Gets or sets the type of entity this thread is about.
     * @type {string}
     * @memberof PostsViewModel
     */
    entityType?: string;
    /**
     * Gets or sets the ID of the entity this thread is about.
     * @type {string}
     * @memberof PostsViewModel
     */
    entityId?: string;
    /**
     * Gets or sets the thread ID for this discourse.
     * @type {string}
     * @memberof PostsViewModel
     */
    threadId?: string;
    /**
     * Gets or sets the total number of all posts in this thread (includes replies).
     * @type {number}
     * @memberof PostsViewModel
     */
    totalPostCount?: number;
    /**
     * Gets or sets the total number of root posts in this thread.
     * @type {number}
     * @memberof PostsViewModel
     */
    totalRootPostCount?: number;
    /**
     * Gets or sets the total number of unique participants.
     * @type {number}
     * @memberof PostsViewModel
     */
    totalParticipants?: number;
    /**
     * Gets or sets when the last post was created.
     * @type {Date}
     * @memberof PostsViewModel
     */
    lastActivityAt?: Date;
    /**
     * 
     * @type {CursorPaginatedResponseOfPostViewModel}
     * @memberof PostsViewModel
     */
    posts?: CursorPaginatedResponseOfPostViewModel;
}

/**
 * Check if a given object implements the PostsViewModel interface.
 */
export function instanceOfPostsViewModel(value: object): value is PostsViewModel {
    return true;
}

export function PostsViewModelFromJSON(json: any): PostsViewModel {
    return PostsViewModelFromJSONTyped(json, false);
}

export function PostsViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostsViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'entityType': json['entityType'] == null ? undefined : json['entityType'],
        'entityId': json['entityId'] == null ? undefined : json['entityId'],
        'threadId': json['threadId'] == null ? undefined : json['threadId'],
        'totalPostCount': json['totalPostCount'] == null ? undefined : json['totalPostCount'],
        'totalRootPostCount': json['totalRootPostCount'] == null ? undefined : json['totalRootPostCount'],
        'totalParticipants': json['totalParticipants'] == null ? undefined : json['totalParticipants'],
        'lastActivityAt': json['lastActivityAt'] == null ? undefined : (new Date(json['lastActivityAt'])),
        'posts': json['posts'] == null ? undefined : CursorPaginatedResponseOfPostViewModelFromJSON(json['posts']),
    };
}

export function PostsViewModelToJSON(json: any): PostsViewModel {
    return PostsViewModelToJSONTyped(json, false);
}

export function PostsViewModelToJSONTyped(value?: PostsViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entityType': value['entityType'],
        'entityId': value['entityId'],
        'threadId': value['threadId'],
        'totalPostCount': value['totalPostCount'],
        'totalRootPostCount': value['totalRootPostCount'],
        'totalParticipants': value['totalParticipants'],
        'lastActivityAt': value['lastActivityAt'] == null ? undefined : ((value['lastActivityAt']).toISOString()),
        'posts': CursorPaginatedResponseOfPostViewModelToJSON(value['posts']),
    };
}

