/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an individual post in the gateway.
 * @export
 * @interface PostViewModel
 */
export interface PostViewModel {
    /**
     * Gets or sets the unique identifier for this post.
     * @type {string}
     * @memberof PostViewModel
     */
    id?: string;
    /**
     * Gets or sets the ID of the participant who authored this post.
     * @type {string}
     * @memberof PostViewModel
     */
    authorId?: string;
    /**
     * Gets or sets the pseudonym of the author.
     * @type {string}
     * @memberof PostViewModel
     */
    authorPseudonym?: string;
    /**
     * Gets or sets the content of the post.
     * @type {string}
     * @memberof PostViewModel
     */
    content?: string;
    /**
     * Gets or sets when the post was created.
     * @type {Date}
     * @memberof PostViewModel
     */
    createdAt?: Date;
    /**
     * Gets or sets the total number of direct replies.
     * @type {number}
     * @memberof PostViewModel
     */
    replyCount?: number;
    /**
     * Gets or sets when the last reply was posted.
     * @type {Date}
     * @memberof PostViewModel
     */
    lastReplyAt?: Date | null;
    /**
     * Gets whether this post has replies.
     * @type {boolean}
     * @memberof PostViewModel
     */
    hasReplies?: boolean;
}

/**
 * Check if a given object implements the PostViewModel interface.
 */
export function instanceOfPostViewModel(value: object): value is PostViewModel {
    return true;
}

export function PostViewModelFromJSON(json: any): PostViewModel {
    return PostViewModelFromJSONTyped(json, false);
}

export function PostViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'authorPseudonym': json['authorPseudonym'] == null ? undefined : json['authorPseudonym'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'replyCount': json['replyCount'] == null ? undefined : json['replyCount'],
        'lastReplyAt': json['lastReplyAt'] == null ? undefined : (new Date(json['lastReplyAt'])),
        'hasReplies': json['hasReplies'] == null ? undefined : json['hasReplies'],
    };
}

export function PostViewModelToJSON(json: any): PostViewModel {
    return PostViewModelToJSONTyped(json, false);
}

export function PostViewModelToJSONTyped(value?: PostViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'authorId': value['authorId'],
        'authorPseudonym': value['authorPseudonym'],
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'replyCount': value['replyCount'],
        'lastReplyAt': value['lastReplyAt'] === null ? null : ((value['lastReplyAt'] as any)?.toISOString()),
        'hasReplies': value['hasReplies'],
    };
}

