/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Amendment } from './Amendment';
import {
    AmendmentFromJSON,
    AmendmentFromJSONTyped,
    AmendmentToJSON,
    AmendmentToJSONTyped,
} from './Amendment';

/**
 * Response model for detailed project information.
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * The project identifier.
     * @type {string}
     * @memberof ProjectResponse
     */
    id?: string;
    /**
     * The owning user group identifier.
     * @type {string}
     * @memberof ProjectResponse
     */
    userGroupId?: string;
    /**
     * The project title.
     * @type {string}
     * @memberof ProjectResponse
     */
    title?: string;
    /**
     * The project description.
     * @type {string}
     * @memberof ProjectResponse
     */
    description?: string;
    /**
     * When the project was created.
     * @type {Date}
     * @memberof ProjectResponse
     */
    createdAt?: Date;
    /**
     * When the project was last updated.
     * @type {Date}
     * @memberof ProjectResponse
     */
    lastUpdatedAt?: Date;
    /**
     * The amendments proposed against this project.
     * @type {Array<Amendment>}
     * @memberof ProjectResponse
     */
    amendments?: Array<Amendment>;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
    return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userGroupId': json['userGroupId'] == null ? undefined : json['userGroupId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastUpdatedAt': json['lastUpdatedAt'] == null ? undefined : (new Date(json['lastUpdatedAt'])),
        'amendments': json['amendments'] == null ? undefined : ((json['amendments'] as Array<any>).map(AmendmentFromJSON)),
    };
}

export function ProjectResponseToJSON(json: any): ProjectResponse {
    return ProjectResponseToJSONTyped(json, false);
}

export function ProjectResponseToJSONTyped(value?: ProjectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userGroupId': value['userGroupId'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'lastUpdatedAt': value['lastUpdatedAt'] == null ? undefined : ((value['lastUpdatedAt']).toISOString()),
        'amendments': value['amendments'] == null ? undefined : ((value['amendments'] as Array<any>).map(AmendmentToJSON)),
    };
}

