/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to propose a new commons.
 * @export
 * @interface ProposeCommonsRequest
 */
export interface ProposeCommonsRequest {
    /**
     * Name of the commons.
     * @type {string}
     * @memberof ProposeCommonsRequest
     */
    name?: string;
    /**
     * Description of the commons.
     * @type {string}
     * @memberof ProposeCommonsRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the ProposeCommonsRequest interface.
 */
export function instanceOfProposeCommonsRequest(value: object): value is ProposeCommonsRequest {
    return true;
}

export function ProposeCommonsRequestFromJSON(json: any): ProposeCommonsRequest {
    return ProposeCommonsRequestFromJSONTyped(json, false);
}

export function ProposeCommonsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProposeCommonsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ProposeCommonsRequestToJSON(json: any): ProposeCommonsRequest {
    return ProposeCommonsRequestToJSONTyped(json, false);
}

export function ProposeCommonsRequestToJSONTyped(value?: ProposeCommonsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

