/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for proposing an amendment to an existing idea.
 * @export
 * @interface ProposeAmendmentRequest
 */
export interface ProposeAmendmentRequest {
    /**
     * Gets or sets the version number of the target idea this amendment applies to.
     * @type {number}
     * @memberof ProposeAmendmentRequest
     */
    targetIdeaVersion?: number;
    /**
     * Gets or sets the proposed title for the amendment.
     * @type {string}
     * @memberof ProposeAmendmentRequest
     */
    proposedTitle?: string;
    /**
     * Gets or sets the proposed body/content for the amendment.
     * @type {string}
     * @memberof ProposeAmendmentRequest
     */
    proposedBody?: string;
    /**
     * Gets or sets the title of the amendment.
     * @type {string}
     * @memberof ProposeAmendmentRequest
     */
    amendmentTitle?: string;
    /**
     * Gets or sets the description of the amendment.
     * @type {string}
     * @memberof ProposeAmendmentRequest
     */
    amendmentDescription?: string;
}

/**
 * Check if a given object implements the ProposeAmendmentRequest interface.
 */
export function instanceOfProposeAmendmentRequest(value: object): value is ProposeAmendmentRequest {
    return true;
}

export function ProposeAmendmentRequestFromJSON(json: any): ProposeAmendmentRequest {
    return ProposeAmendmentRequestFromJSONTyped(json, false);
}

export function ProposeAmendmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProposeAmendmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetIdeaVersion': json['targetIdeaVersion'] == null ? undefined : json['targetIdeaVersion'],
        'proposedTitle': json['proposedTitle'] == null ? undefined : json['proposedTitle'],
        'proposedBody': json['proposedBody'] == null ? undefined : json['proposedBody'],
        'amendmentTitle': json['amendmentTitle'] == null ? undefined : json['amendmentTitle'],
        'amendmentDescription': json['amendmentDescription'] == null ? undefined : json['amendmentDescription'],
    };
}

export function ProposeAmendmentRequestToJSON(json: any): ProposeAmendmentRequest {
    return ProposeAmendmentRequestToJSONTyped(json, false);
}

export function ProposeAmendmentRequestToJSONTyped(value?: ProposeAmendmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetIdeaVersion': value['targetIdeaVersion'],
        'proposedTitle': value['proposedTitle'],
        'proposedBody': value['proposedBody'],
        'amendmentTitle': value['amendmentTitle'],
        'amendmentDescription': value['amendmentDescription'],
    };
}

