/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request used to raise a new concern in the system.
 * @export
 * @interface RaiseConcernRequest
 */
export interface RaiseConcernRequest {
    /**
     * Name of the concern being raised.
     * @type {string}
     * @memberof RaiseConcernRequest
     */
    name?: string;
    /**
     * Tags associated with the raised concern.
     * @type {Array<string>}
     * @memberof RaiseConcernRequest
     */
    tags?: Array<string>;
    /**
     * Ids of signals associated with the concern.
     * @type {Array<string>}
     * @memberof RaiseConcernRequest
     */
    signalIds?: Array<string>;
}

/**
 * Check if a given object implements the RaiseConcernRequest interface.
 */
export function instanceOfRaiseConcernRequest(value: object): value is RaiseConcernRequest {
    return true;
}

export function RaiseConcernRequestFromJSON(json: any): RaiseConcernRequest {
    return RaiseConcernRequestFromJSONTyped(json, false);
}

export function RaiseConcernRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RaiseConcernRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'signalIds': json['signalIds'] == null ? undefined : json['signalIds'],
    };
}

export function RaiseConcernRequestToJSON(json: any): RaiseConcernRequest {
    return RaiseConcernRequestToJSONTyped(json, false);
}

export function RaiseConcernRequestToJSONTyped(value?: RaiseConcernRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'tags': value['tags'],
        'signalIds': value['signalIds'],
    };
}

