/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The result of resolving an invite link token.
 * @export
 * @interface ResolvedInviteLinkResponse
 */
export interface ResolvedInviteLinkResponse {
    /**
     * The internal user ID of the participant who created the invite link.
     * @type {string}
     * @memberof ResolvedInviteLinkResponse
     */
    inviterUserId?: string;
}

/**
 * Check if a given object implements the ResolvedInviteLinkResponse interface.
 */
export function instanceOfResolvedInviteLinkResponse(value: object): value is ResolvedInviteLinkResponse {
    return true;
}

export function ResolvedInviteLinkResponseFromJSON(json: any): ResolvedInviteLinkResponse {
    return ResolvedInviteLinkResponseFromJSONTyped(json, false);
}

export function ResolvedInviteLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolvedInviteLinkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'inviterUserId': json['inviterUserId'] == null ? undefined : json['inviterUserId'],
    };
}

export function ResolvedInviteLinkResponseToJSON(json: any): ResolvedInviteLinkResponse {
    return ResolvedInviteLinkResponseToJSONTyped(json, false);
}

export function ResolvedInviteLinkResponseToJSONTyped(value?: ResolvedInviteLinkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inviterUserId': value['inviterUserId'],
    };
}

