/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfSignalViewModel } from './PaginatedResponseOfSignalViewModel';
import {
    PaginatedResponseOfSignalViewModelFromJSON,
    PaginatedResponseOfSignalViewModelFromJSONTyped,
    PaginatedResponseOfSignalViewModelToJSON,
    PaginatedResponseOfSignalViewModelToJSONTyped,
} from './PaginatedResponseOfSignalViewModel';
import type { FilterStateViewModel } from './FilterStateViewModel';
import {
    FilterStateViewModelFromJSON,
    FilterStateViewModelFromJSONTyped,
    FilterStateViewModelToJSON,
    FilterStateViewModelToJSONTyped,
} from './FilterStateViewModel';

/**
 * View model for the signals feed page, including signals and metadata for filtering.
 * @export
 * @interface SignalsFeedViewModel
 */
export interface SignalsFeedViewModel {
    /**
     * 
     * @type {PaginatedResponseOfSignalViewModel}
     * @memberof SignalsFeedViewModel
     */
    signals?: PaginatedResponseOfSignalViewModel;
    /**
     * All available tags across all signals (for filtering).
     * @type {Array<string>}
     * @memberof SignalsFeedViewModel
     */
    availableTags?: Array<string>;
    /**
     * 
     * @type {FilterStateViewModel}
     * @memberof SignalsFeedViewModel
     */
    appliedFilters?: FilterStateViewModel;
}

/**
 * Check if a given object implements the SignalsFeedViewModel interface.
 */
export function instanceOfSignalsFeedViewModel(value: object): value is SignalsFeedViewModel {
    return true;
}

export function SignalsFeedViewModelFromJSON(json: any): SignalsFeedViewModel {
    return SignalsFeedViewModelFromJSONTyped(json, false);
}

export function SignalsFeedViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalsFeedViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'signals': json['signals'] == null ? undefined : PaginatedResponseOfSignalViewModelFromJSON(json['signals']),
        'availableTags': json['availableTags'] == null ? undefined : json['availableTags'],
        'appliedFilters': json['appliedFilters'] == null ? undefined : FilterStateViewModelFromJSON(json['appliedFilters']),
    };
}

export function SignalsFeedViewModelToJSON(json: any): SignalsFeedViewModel {
    return SignalsFeedViewModelToJSONTyped(json, false);
}

export function SignalsFeedViewModelToJSONTyped(value?: SignalsFeedViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signals': PaginatedResponseOfSignalViewModelToJSON(value['signals']),
        'availableTags': value['availableTags'],
        'appliedFilters': FilterStateViewModelToJSON(value['appliedFilters']),
    };
}

