/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocietyResponse } from './SocietyResponse';
import {
    SocietyResponseFromJSON,
    SocietyResponseFromJSONTyped,
    SocietyResponseToJSON,
    SocietyResponseToJSONTyped,
} from './SocietyResponse';

/**
 * View model for detailed society information.
 * @export
 * @interface SocietyDetailViewModel
 */
export interface SocietyDetailViewModel {
    /**
     * 
     * @type {SocietyResponse}
     * @memberof SocietyDetailViewModel
     */
    society?: SocietyResponse;
}

/**
 * Check if a given object implements the SocietyDetailViewModel interface.
 */
export function instanceOfSocietyDetailViewModel(value: object): value is SocietyDetailViewModel {
    return true;
}

export function SocietyDetailViewModelFromJSON(json: any): SocietyDetailViewModel {
    return SocietyDetailViewModelFromJSONTyped(json, false);
}

export function SocietyDetailViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocietyDetailViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'society': json['society'] == null ? undefined : SocietyResponseFromJSON(json['society']),
    };
}

export function SocietyDetailViewModelToJSON(json: any): SocietyDetailViewModel {
    return SocietyDetailViewModelToJSONTyped(json, false);
}

export function SocietyDetailViewModelToJSONTyped(value?: SocietyDetailViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'society': SocietyResponseToJSON(value['society']),
    };
}

