/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for a society relationship.
 * @export
 * @interface SocietyRelationshipResponse
 */
export interface SocietyRelationshipResponse {
    /**
     * The target society ID.
     * @type {string}
     * @memberof SocietyRelationshipResponse
     */
    targetSocietyId?: string;
    /**
     * The type of relationship as a string (e.g. "PartOf", "Affiliated", "Federated").
     * @type {string}
     * @memberof SocietyRelationshipResponse
     */
    relationshipType?: string;
}

/**
 * Check if a given object implements the SocietyRelationshipResponse interface.
 */
export function instanceOfSocietyRelationshipResponse(value: object): value is SocietyRelationshipResponse {
    return true;
}

export function SocietyRelationshipResponseFromJSON(json: any): SocietyRelationshipResponse {
    return SocietyRelationshipResponseFromJSONTyped(json, false);
}

export function SocietyRelationshipResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocietyRelationshipResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'targetSocietyId': json['targetSocietyId'] == null ? undefined : json['targetSocietyId'],
        'relationshipType': json['relationshipType'] == null ? undefined : json['relationshipType'],
    };
}

export function SocietyRelationshipResponseToJSON(json: any): SocietyRelationshipResponse {
    return SocietyRelationshipResponseToJSONTyped(json, false);
}

export function SocietyRelationshipResponseToJSONTyped(value?: SocietyRelationshipResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetSocietyId': value['targetSocietyId'],
        'relationshipType': value['relationshipType'],
    };
}

