/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A read-only view of a society invite link returned from the API.
 * @export
 * @interface SocietyInviteLinkViewResponse
 */
export interface SocietyInviteLinkViewResponse {
    /**
     * The invite link ID.
     * @type {string}
     * @memberof SocietyInviteLinkViewResponse
     */
    id?: string;
    /**
     * The URL-safe base64url token.
     * @type {string}
     * @memberof SocietyInviteLinkViewResponse
     */
    token?: string;
    /**
     * The ID of the society this invite link is for.
     * @type {string}
     * @memberof SocietyInviteLinkViewResponse
     */
    societyId?: string;
    /**
     * The optional private note visible only to the creator.
     * @type {string}
     * @memberof SocietyInviteLinkViewResponse
     */
    note?: string | null;
    /**
     * Whether the link has been revoked.
     * @type {boolean}
     * @memberof SocietyInviteLinkViewResponse
     */
    isRevoked?: boolean;
    /**
     * UTC timestamp of creation.
     * @type {Date}
     * @memberof SocietyInviteLinkViewResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the SocietyInviteLinkViewResponse interface.
 */
export function instanceOfSocietyInviteLinkViewResponse(value: object): value is SocietyInviteLinkViewResponse {
    return true;
}

export function SocietyInviteLinkViewResponseFromJSON(json: any): SocietyInviteLinkViewResponse {
    return SocietyInviteLinkViewResponseFromJSONTyped(json, false);
}

export function SocietyInviteLinkViewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocietyInviteLinkViewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'token': json['token'] == null ? undefined : json['token'],
        'societyId': json['societyId'] == null ? undefined : json['societyId'],
        'note': json['note'] == null ? undefined : json['note'],
        'isRevoked': json['isRevoked'] == null ? undefined : json['isRevoked'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function SocietyInviteLinkViewResponseToJSON(json: any): SocietyInviteLinkViewResponse {
    return SocietyInviteLinkViewResponseToJSONTyped(json, false);
}

export function SocietyInviteLinkViewResponseToJSONTyped(value?: SocietyInviteLinkViewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'token': value['token'],
        'societyId': value['societyId'],
        'note': value['note'],
        'isRevoked': value['isRevoked'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

