/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOfSocietyListItemResponse } from './PaginatedResponseOfSocietyListItemResponse';
import {
    PaginatedResponseOfSocietyListItemResponseFromJSON,
    PaginatedResponseOfSocietyListItemResponseFromJSONTyped,
    PaginatedResponseOfSocietyListItemResponseToJSON,
    PaginatedResponseOfSocietyListItemResponseToJSONTyped,
} from './PaginatedResponseOfSocietyListItemResponse';

/**
 * View model for the societies list, including paginated society data.
 * @export
 * @interface SocietiesFeedViewModel
 */
export interface SocietiesFeedViewModel {
    /**
     * 
     * @type {PaginatedResponseOfSocietyListItemResponse}
     * @memberof SocietiesFeedViewModel
     */
    societies?: PaginatedResponseOfSocietyListItemResponse;
}

/**
 * Check if a given object implements the SocietiesFeedViewModel interface.
 */
export function instanceOfSocietiesFeedViewModel(value: object): value is SocietiesFeedViewModel {
    return true;
}

export function SocietiesFeedViewModelFromJSON(json: any): SocietiesFeedViewModel {
    return SocietiesFeedViewModelFromJSONTyped(json, false);
}

export function SocietiesFeedViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocietiesFeedViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'societies': json['societies'] == null ? undefined : PaginatedResponseOfSocietyListItemResponseFromJSON(json['societies']),
    };
}

export function SocietiesFeedViewModelToJSON(json: any): SocietiesFeedViewModel {
    return SocietiesFeedViewModelToJSONTyped(json, false);
}

export function SocietiesFeedViewModelToJSONTyped(value?: SocietiesFeedViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'societies': PaginatedResponseOfSocietyListItemResponseToJSON(value['societies']),
    };
}

