/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for a society member.
 * @export
 * @interface SocietyMemberResponse
 */
export interface SocietyMemberResponse {
    /**
     * The membership identifier.
     * @type {string}
     * @memberof SocietyMemberResponse
     */
    membershipId?: string;
    /**
     * The pseudonym of the member, scoped to this society.
     * @type {string}
     * @memberof SocietyMemberResponse
     */
    pseudonym?: string;
    /**
     * The social contract ID agreed to at join time.
     * @type {string}
     * @memberof SocietyMemberResponse
     */
    socialContractId?: string;
    /**
     * When the participant joined.
     * @type {Date}
     * @memberof SocietyMemberResponse
     */
    joinedAt?: Date;
}

/**
 * Check if a given object implements the SocietyMemberResponse interface.
 */
export function instanceOfSocietyMemberResponse(value: object): value is SocietyMemberResponse {
    return true;
}

export function SocietyMemberResponseFromJSON(json: any): SocietyMemberResponse {
    return SocietyMemberResponseFromJSONTyped(json, false);
}

export function SocietyMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocietyMemberResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'membershipId': json['membershipId'] == null ? undefined : json['membershipId'],
        'pseudonym': json['pseudonym'] == null ? undefined : json['pseudonym'],
        'socialContractId': json['socialContractId'] == null ? undefined : json['socialContractId'],
        'joinedAt': json['joinedAt'] == null ? undefined : (new Date(json['joinedAt'])),
    };
}

export function SocietyMemberResponseToJSON(json: any): SocietyMemberResponse {
    return SocietyMemberResponseToJSONTyped(json, false);
}

export function SocietyMemberResponseToJSONTyped(value?: SocietyMemberResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'membershipId': value['membershipId'],
        'pseudonym': value['pseudonym'],
        'socialContractId': value['socialContractId'],
        'joinedAt': value['joinedAt'] == null ? undefined : ((value['joinedAt']).toISOString()),
    };
}

