/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocietyRelationshipResponse } from './SocietyRelationshipResponse';
import {
    SocietyRelationshipResponseFromJSON,
    SocietyRelationshipResponseFromJSONTyped,
    SocietyRelationshipResponseToJSON,
    SocietyRelationshipResponseToJSONTyped,
} from './SocietyRelationshipResponse';

/**
 * Response model for a single society.
 * @export
 * @interface SocietyResponse
 */
export interface SocietyResponse {
    /**
     * The unique identifier of the society.
     * @type {string}
     * @memberof SocietyResponse
     */
    id?: string;
    /**
     * The name of the society.
     * @type {string}
     * @memberof SocietyResponse
     */
    name?: string;
    /**
     * The description of the society.
     * @type {string}
     * @memberof SocietyResponse
     */
    description?: string;
    /**
     * The pseudonym of the creator.
     * @type {string}
     * @memberof SocietyResponse
     */
    createdByPseudonym?: string;
    /**
     * When the society was created.
     * @type {Date}
     * @memberof SocietyResponse
     */
    createdAt?: Date;
    /**
     * The tags associated with the society.
     * @type {Array<string>}
     * @memberof SocietyResponse
     */
    tags?: Array<string>;
    /**
     * Whether this society has geographic bounds.
     * @type {boolean}
     * @memberof SocietyResponse
     */
    hasGeographicBounds?: boolean;
    /**
     * The geographic bounds as JSON, or null.
     * @type {string}
     * @memberof SocietyResponse
     */
    geographicBoundsJson?: string | null;
    /**
     * The center coordinates as JSON, or null.
     * @type {string}
     * @memberof SocietyResponse
     */
    centerJson?: string | null;
    /**
     * The relationships to other societies.
     * @type {Array<SocietyRelationshipResponse>}
     * @memberof SocietyResponse
     */
    relationships?: Array<SocietyRelationshipResponse>;
    /**
     * The number of active members.
     * @type {number}
     * @memberof SocietyResponse
     */
    activeMemberCount?: number;
    /**
     * The ID of the current active social contract, or null if not yet available.
     * @type {string}
     * @memberof SocietyResponse
     */
    currentSocialContractId?: string | null;
}

/**
 * Check if a given object implements the SocietyResponse interface.
 */
export function instanceOfSocietyResponse(value: object): value is SocietyResponse {
    return true;
}

export function SocietyResponseFromJSON(json: any): SocietyResponse {
    return SocietyResponseFromJSONTyped(json, false);
}

export function SocietyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocietyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdByPseudonym': json['createdByPseudonym'] == null ? undefined : json['createdByPseudonym'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'hasGeographicBounds': json['hasGeographicBounds'] == null ? undefined : json['hasGeographicBounds'],
        'geographicBoundsJson': json['geographicBoundsJson'] == null ? undefined : json['geographicBoundsJson'],
        'centerJson': json['centerJson'] == null ? undefined : json['centerJson'],
        'relationships': json['relationships'] == null ? undefined : ((json['relationships'] as Array<any>).map(SocietyRelationshipResponseFromJSON)),
        'activeMemberCount': json['activeMemberCount'] == null ? undefined : json['activeMemberCount'],
        'currentSocialContractId': json['currentSocialContractId'] == null ? undefined : json['currentSocialContractId'],
    };
}

export function SocietyResponseToJSON(json: any): SocietyResponse {
    return SocietyResponseToJSONTyped(json, false);
}

export function SocietyResponseToJSONTyped(value?: SocietyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'createdByPseudonym': value['createdByPseudonym'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'tags': value['tags'],
        'hasGeographicBounds': value['hasGeographicBounds'],
        'geographicBoundsJson': value['geographicBoundsJson'],
        'centerJson': value['centerJson'],
        'relationships': value['relationships'] == null ? undefined : ((value['relationships'] as Array<any>).map(SocietyRelationshipResponseToJSON)),
        'activeMemberCount': value['activeMemberCount'],
        'currentSocialContractId': value['currentSocialContractId'],
    };
}

