/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SortDirection } from './SortDirection';
import {
    SortDirectionFromJSON,
    SortDirectionFromJSONTyped,
    SortDirectionToJSON,
    SortDirectionToJSONTyped,
} from './SortDirection';

/**
 * Describes a single sort operation against a logical field.
 * @export
 * @interface SortDescriptor
 */
export interface SortDescriptor {
    /**
     * Logical field name to sort by. Mapping to actual data model is responsibility of the consumer.
     * @type {string}
     * @memberof SortDescriptor
     */
    field?: string;
    /**
     * 
     * @type {SortDirection}
     * @memberof SortDescriptor
     */
    direction?: SortDirection;
}



/**
 * Check if a given object implements the SortDescriptor interface.
 */
export function instanceOfSortDescriptor(value: object): value is SortDescriptor {
    return true;
}

export function SortDescriptorFromJSON(json: any): SortDescriptor {
    return SortDescriptorFromJSONTyped(json, false);
}

export function SortDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortDescriptor {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'direction': json['direction'] == null ? undefined : SortDirectionFromJSON(json['direction']),
    };
}

export function SortDescriptorToJSON(json: any): SortDescriptor {
    return SortDescriptorToJSONTyped(json, false);
}

export function SortDescriptorToJSONTyped(value?: SortDescriptor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'direction': SortDirectionToJSON(value['direction']),
    };
}

