/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for suggesting a structured action on a signal.
 * @export
 * @interface SuggestActionRequest
 */
export interface SuggestActionRequest {
    /**
     * The action type name (e.g. MakeACall, VisitAWebpage).
     * Must match the Name of a value returned by GET /api/action-types.
     * @type {string}
     * @memberof SuggestActionRequest
     */
    actionType?: string | null;
    /**
     * The phone number to call. Required when ActionType is MakeACall.
     * @type {string}
     * @memberof SuggestActionRequest
     */
    phoneNumber?: string | null;
    /**
     * The URL to visit. Required when ActionType is VisitAWebpage.
     * @type {string}
     * @memberof SuggestActionRequest
     */
    url?: string | null;
    /**
     * Optional free-text context applicable to any action type.
     * @type {string}
     * @memberof SuggestActionRequest
     */
    details?: string | null;
}

/**
 * Check if a given object implements the SuggestActionRequest interface.
 */
export function instanceOfSuggestActionRequest(value: object): value is SuggestActionRequest {
    return true;
}

export function SuggestActionRequestFromJSON(json: any): SuggestActionRequest {
    return SuggestActionRequestFromJSONTyped(json, false);
}

export function SuggestActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestActionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'actionType': json['actionType'] == null ? undefined : json['actionType'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'url': json['url'] == null ? undefined : json['url'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function SuggestActionRequestToJSON(json: any): SuggestActionRequest {
    return SuggestActionRequestToJSONTyped(json, false);
}

export function SuggestActionRequestToJSONTyped(value?: SuggestActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actionType': value['actionType'],
        'phoneNumber': value['phoneNumber'],
        'url': value['url'],
        'details': value['details'],
    };
}

