/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for updating or reopening a project inquiry body.
 * @export
 * @interface UpdateProjectInquiryRequest
 */
export interface UpdateProjectInquiryRequest {
    /**
     * The updated body text.
     * @type {string}
     * @memberof UpdateProjectInquiryRequest
     */
    newBody?: string;
}

/**
 * Check if a given object implements the UpdateProjectInquiryRequest interface.
 */
export function instanceOfUpdateProjectInquiryRequest(value: object): value is UpdateProjectInquiryRequest {
    return true;
}

export function UpdateProjectInquiryRequestFromJSON(json: any): UpdateProjectInquiryRequest {
    return UpdateProjectInquiryRequestFromJSONTyped(json, false);
}

export function UpdateProjectInquiryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectInquiryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newBody': json['newBody'] == null ? undefined : json['newBody'],
    };
}

export function UpdateProjectInquiryRequestToJSON(json: any): UpdateProjectInquiryRequest {
    return UpdateProjectInquiryRequestToJSONTyped(json, false);
}

export function UpdateProjectInquiryRequestToJSONTyped(value?: UpdateProjectInquiryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newBody': value['newBody'],
    };
}

