/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroupContestationRulesDto } from './UserGroupContestationRulesDto';
import {
    UserGroupContestationRulesDtoFromJSON,
    UserGroupContestationRulesDtoFromJSONTyped,
    UserGroupContestationRulesDtoToJSON,
    UserGroupContestationRulesDtoToJSONTyped,
} from './UserGroupContestationRulesDto';
import type { UserGroupMembershipRulesDto } from './UserGroupMembershipRulesDto';
import {
    UserGroupMembershipRulesDtoFromJSON,
    UserGroupMembershipRulesDtoFromJSONTyped,
    UserGroupMembershipRulesDtoToJSON,
    UserGroupMembershipRulesDtoToJSONTyped,
} from './UserGroupMembershipRulesDto';
import type { UserGroupShunningRulesDto } from './UserGroupShunningRulesDto';
import {
    UserGroupShunningRulesDtoFromJSON,
    UserGroupShunningRulesDtoFromJSONTyped,
    UserGroupShunningRulesDtoToJSON,
    UserGroupShunningRulesDtoToJSONTyped,
} from './UserGroupShunningRulesDto';

/**
 * Charter data transfer object.
 * @export
 * @interface UserGroupCharterDto
 */
export interface UserGroupCharterDto {
    /**
     * 
     * @type {UserGroupContestationRulesDto}
     * @memberof UserGroupCharterDto
     */
    contestationRules?: UserGroupContestationRulesDto;
    /**
     * 
     * @type {UserGroupMembershipRulesDto}
     * @memberof UserGroupCharterDto
     */
    membershipRules?: UserGroupMembershipRulesDto;
    /**
     * 
     * @type {UserGroupShunningRulesDto}
     * @memberof UserGroupCharterDto
     */
    shunningRules?: UserGroupShunningRulesDto;
}

/**
 * Check if a given object implements the UserGroupCharterDto interface.
 */
export function instanceOfUserGroupCharterDto(value: object): value is UserGroupCharterDto {
    return true;
}

export function UserGroupCharterDtoFromJSON(json: any): UserGroupCharterDto {
    return UserGroupCharterDtoFromJSONTyped(json, false);
}

export function UserGroupCharterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupCharterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'contestationRules': json['contestationRules'] == null ? undefined : UserGroupContestationRulesDtoFromJSON(json['contestationRules']),
        'membershipRules': json['membershipRules'] == null ? undefined : UserGroupMembershipRulesDtoFromJSON(json['membershipRules']),
        'shunningRules': json['shunningRules'] == null ? undefined : UserGroupShunningRulesDtoFromJSON(json['shunningRules']),
    };
}

export function UserGroupCharterDtoToJSON(json: any): UserGroupCharterDto {
    return UserGroupCharterDtoToJSONTyped(json, false);
}

export function UserGroupCharterDtoToJSONTyped(value?: UserGroupCharterDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contestationRules': UserGroupContestationRulesDtoToJSON(value['contestationRules']),
        'membershipRules': UserGroupMembershipRulesDtoToJSON(value['membershipRules']),
        'shunningRules': UserGroupShunningRulesDtoToJSON(value['shunningRules']),
    };
}

