/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroupCharterResponse } from './UserGroupCharterResponse';
import {
    UserGroupCharterResponseFromJSON,
    UserGroupCharterResponseFromJSONTyped,
    UserGroupCharterResponseToJSON,
    UserGroupCharterResponseToJSONTyped,
} from './UserGroupCharterResponse';

/**
 * Represents detailed information about a user group.
 * @export
 * @interface UserGroupDetailResponse
 */
export interface UserGroupDetailResponse {
    /**
     * The unique identifier of the user group.
     * @type {string}
     * @memberof UserGroupDetailResponse
     */
    id?: string;
    /**
     * The identifier of the commons this group governs.
     * @type {string}
     * @memberof UserGroupDetailResponse
     */
    commonsId?: string;
    /**
     * The name of the commons this group governs.
     * @type {string}
     * @memberof UserGroupDetailResponse
     */
    commonsName?: string;
    /**
     * The name of the user group.
     * @type {string}
     * @memberof UserGroupDetailResponse
     */
    name?: string;
    /**
     * The philosophy of the user group, if set.
     * @type {string}
     * @memberof UserGroupDetailResponse
     */
    philosophy?: string | null;
    /**
     * The pseudonym of the participant who founded the group.
     * @type {string}
     * @memberof UserGroupDetailResponse
     */
    foundedByPseudonym?: string;
    /**
     * The timestamp when the group was formed.
     * @type {Date}
     * @memberof UserGroupDetailResponse
     */
    formedAt?: Date;
    /**
     * The current number of members in the group.
     * @type {number}
     * @memberof UserGroupDetailResponse
     */
    memberCount?: number;
    /**
     * The join policy of the group.
     * @type {string}
     * @memberof UserGroupDetailResponse
     */
    joinPolicy?: string;
    /**
     * Whether the requesting participant is a member of the group.
     * @type {boolean}
     * @memberof UserGroupDetailResponse
     */
    isMember?: boolean;
    /**
     * 
     * @type {UserGroupCharterResponse}
     * @memberof UserGroupDetailResponse
     */
    charter?: UserGroupCharterResponse;
}

/**
 * Check if a given object implements the UserGroupDetailResponse interface.
 */
export function instanceOfUserGroupDetailResponse(value: object): value is UserGroupDetailResponse {
    return true;
}

export function UserGroupDetailResponseFromJSON(json: any): UserGroupDetailResponse {
    return UserGroupDetailResponseFromJSONTyped(json, false);
}

export function UserGroupDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'commonsId': json['commonsId'] == null ? undefined : json['commonsId'],
        'commonsName': json['commonsName'] == null ? undefined : json['commonsName'],
        'name': json['name'] == null ? undefined : json['name'],
        'philosophy': json['philosophy'] == null ? undefined : json['philosophy'],
        'foundedByPseudonym': json['foundedByPseudonym'] == null ? undefined : json['foundedByPseudonym'],
        'formedAt': json['formedAt'] == null ? undefined : (new Date(json['formedAt'])),
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'joinPolicy': json['joinPolicy'] == null ? undefined : json['joinPolicy'],
        'isMember': json['isMember'] == null ? undefined : json['isMember'],
        'charter': json['charter'] == null ? undefined : UserGroupCharterResponseFromJSON(json['charter']),
    };
}

export function UserGroupDetailResponseToJSON(json: any): UserGroupDetailResponse {
    return UserGroupDetailResponseToJSONTyped(json, false);
}

export function UserGroupDetailResponseToJSONTyped(value?: UserGroupDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'commonsId': value['commonsId'],
        'commonsName': value['commonsName'],
        'name': value['name'],
        'philosophy': value['philosophy'],
        'foundedByPseudonym': value['foundedByPseudonym'],
        'formedAt': value['formedAt'] == null ? undefined : ((value['formedAt']).toISOString()),
        'memberCount': value['memberCount'],
        'joinPolicy': value['joinPolicy'],
        'isMember': value['isMember'],
        'charter': UserGroupCharterResponseToJSON(value['charter']),
    };
}

