/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Approval settings for membership.
 * @export
 * @interface UserGroupApprovalSettingsDto
 */
export interface UserGroupApprovalSettingsDto {
    /**
     * The threshold for approval decisions, represented as a decimal between 0 and 1.
     * @type {number}
     * @memberof UserGroupApprovalSettingsDto
     */
    approvalThreshold?: number;
    /**
     * Indicates whether veto power is enabled.
     * @type {boolean}
     * @memberof UserGroupApprovalSettingsDto
     */
    vetoEnabled?: boolean;
}

/**
 * Check if a given object implements the UserGroupApprovalSettingsDto interface.
 */
export function instanceOfUserGroupApprovalSettingsDto(value: object): value is UserGroupApprovalSettingsDto {
    return true;
}

export function UserGroupApprovalSettingsDtoFromJSON(json: any): UserGroupApprovalSettingsDto {
    return UserGroupApprovalSettingsDtoFromJSONTyped(json, false);
}

export function UserGroupApprovalSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupApprovalSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'approvalThreshold': json['approvalThreshold'] == null ? undefined : json['approvalThreshold'],
        'vetoEnabled': json['vetoEnabled'] == null ? undefined : json['vetoEnabled'],
    };
}

export function UserGroupApprovalSettingsDtoToJSON(json: any): UserGroupApprovalSettingsDto {
    return UserGroupApprovalSettingsDtoToJSONTyped(json, false);
}

export function UserGroupApprovalSettingsDtoToJSONTyped(value?: UserGroupApprovalSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approvalThreshold': value['approvalThreshold'],
        'vetoEnabled': value['vetoEnabled'],
    };
}

