/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Specifies the policies that determine how users can join a group.
 * @export
 * @enum {string}
 */
export enum UserGroupJoinPolicyDto {
    Open = 'Open',
    InviteOnly = 'InviteOnly',
    Approval = 'Approval'
}


export function instanceOfUserGroupJoinPolicyDto(value: any): boolean {
    for (const key in UserGroupJoinPolicyDto) {
        if (Object.prototype.hasOwnProperty.call(UserGroupJoinPolicyDto, key)) {
            if (UserGroupJoinPolicyDto[key as keyof typeof UserGroupJoinPolicyDto] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserGroupJoinPolicyDtoFromJSON(json: any): UserGroupJoinPolicyDto {
    return UserGroupJoinPolicyDtoFromJSONTyped(json, false);
}

export function UserGroupJoinPolicyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupJoinPolicyDto {
    return json as UserGroupJoinPolicyDto;
}

export function UserGroupJoinPolicyDtoToJSON(value?: UserGroupJoinPolicyDto | null): any {
    return value as any;
}

export function UserGroupJoinPolicyDtoToJSONTyped(value: any, ignoreDiscriminator: boolean): UserGroupJoinPolicyDto {
    return value as UserGroupJoinPolicyDto;
}

