/* tslint:disable */
/* eslint-disable */
/**
 * BindingChaos.Web.Gateway
 * BindingChaos Web Gateway API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents the approval settings for a user group membership policy.
 * @export
 * @interface UserGroupApprovalSettingsResponse
 */
export interface UserGroupApprovalSettingsResponse {
    /**
     * The fraction of approvals required for a join request to succeed.
     * @type {number}
     * @memberof UserGroupApprovalSettingsResponse
     */
    approvalThreshold?: number;
    /**
     * Whether any member may veto a join request.
     * @type {boolean}
     * @memberof UserGroupApprovalSettingsResponse
     */
    vetoEnabled?: boolean;
}

/**
 * Check if a given object implements the UserGroupApprovalSettingsResponse interface.
 */
export function instanceOfUserGroupApprovalSettingsResponse(value: object): value is UserGroupApprovalSettingsResponse {
    return true;
}

export function UserGroupApprovalSettingsResponseFromJSON(json: any): UserGroupApprovalSettingsResponse {
    return UserGroupApprovalSettingsResponseFromJSONTyped(json, false);
}

export function UserGroupApprovalSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupApprovalSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'approvalThreshold': json['approvalThreshold'] == null ? undefined : json['approvalThreshold'],
        'vetoEnabled': json['vetoEnabled'] == null ? undefined : json['vetoEnabled'],
    };
}

export function UserGroupApprovalSettingsResponseToJSON(json: any): UserGroupApprovalSettingsResponse {
    return UserGroupApprovalSettingsResponseToJSONTyped(json, false);
}

export function UserGroupApprovalSettingsResponseToJSONTyped(value?: UserGroupApprovalSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approvalThreshold': value['approvalThreshold'],
        'vetoEnabled': value['vetoEnabled'],
    };
}

